### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by userefe** [qbcore-framework/qb-core#1001]
### Summary

I give myself mechanic job and it works but it doesn’t work after I restart the mechanic script or when I log out of the server and back in, even still I have mechanic job.

### Reproduction

ı use /setjob [ID] [mechanic_bennys] [2] command and it works but after I restart the mechanic script or when I log out of the server and back in or restart the server it doesn't work.

### Expected behavior

Active mechanic can use mechanic menu, after restart the mechanic script or active mechanic log out of the server and back in or restart the server.

### Actual behavior

after I restart the mechanic script or when I log out of the server and back in or restart the server, even still I have mechanic job. Also unemployed players, polices and players can use mechanic when there is no active mechanic in server. Active mechanic log out and back in server then waow active mechanic can't use mechanic menu and also other players can't use mechanic menu because there is an active mechanic but active mechanic cant use mechanic menu, shame:))

### Additional context

[https://dosya.co/6rtp3drhxmvs/tgiann-mekanikv2.rar.html](url)

![fivem script error](https://github.com/qbcore-framework/qb-core/assets/139073838/1b49e60d-b3e7-4b88-a630-a093fbdb6e7f)
![cl_bennys lua741](https://github.com/qbcore-framework/qb-core/assets/139073838/ba9913fb-7a73-422e-87cb-0d533a939903)
![events lua189](https://github.com/qbcore-framework/qb-core/assets/139073838/71cd7a95-2690-4747-8be3-9c9057077813)

### Last Updated

today

### Custom Resources

tgiann-mekanikv2

### Resource Rename

no

**Comment by userefe** [comment]
solved!!! 741 code line should be on 742 code line and you should add this code ''if PlayerData.job == nil then PlayerData = QBCore.Functions.GetPlayerData() end'' at 741 code line, see you guys.

**Comment by CashBoi69** [comment]
how do you open the carry menu in game i cant seem to find a keybind

**Comment by Bongmasta406** [comment]
can you please close this Bug report 

> solved!!! 741 code line should be on 742 code line and you should add this code ''if PlayerData.job == nil then PlayerData = QBCore.Functions.GetPlayerData() end'' at 741 code line, see you guys.
