### ISSUE TITLE
[BUG] Quick Disappearing Menu

### ISSUE THREAD

**Issue by joshking20** [qbcore-framework/qb-core#1007]
### Summary

When attempting to utilize any basic qb core menu while in the server the menu will show up but it will disappear very quickly or as soon as you move the mouse in any direction. 

### Reproduction

1. started the server.
2. when utilizing any QB core menu, the menu will disappear before any action could be pressed.

### Expected behavior

i expected to be able to use the menu as intended.

### Actual behavior

The menu populates then disappears just enough to see it. Then once you attempt to choose and action the menu disappears.

### Additional context

we have reached out to our server provider due to the server already being establish with QB core when purchased. They advised that they could not see any errors in our logs, and they did not have a direct solution to the problem.

we are currently running QB Target and QB Menu on our ZAP Hosted Server.

### Last Updated

recently purchased the server as of two days ago. 

### Custom Resources

All QB core resources

### Resource Rename

no.

**Comment by Bongmasta406** [comment]
Can you provide an actual Bug, with errors happening or a video recreating the bug, so we can better assist, as there is lack of info to really help.
