### ISSUE TITLE
[BUG] QBCore.Functions.AddJob

### ISSUE THREAD

**Issue by web-caos** [qbcore-framework/qb-core#1017]
### Summary

QBCore.Functions.AddJob not working?

### Reproduction

1. Add a job thru external script with QBCore.Functions.AddJob or exports['qb-core']:AddJob
2. Try to manage employee thru BossMenu
3. BossMenu doesn't find the added Job (or find it at begin but after a restart the Job get lost)

### Expected behavior

BossMenu should find the added job like others.

### Actual behavior

BossMenu dont find the job added thru the function or thru the exports.
Tried different ensure ordering, but nothing, at some point qb-management cant find the job in the table.

### Last Updated

today

### Custom Resources

qb-core, qb-management, custom script

### Resource Rename

No

**Comment by web-caos** [comment]
Adding info: Server Side i can retrieve the shared jobs, but in client side i get only the jobs in the config file

**Comment by GhzGarage** [comment]
There seems to be a sync issue with this, i've been made aware of it and finding the exact cause

**Comment by GhzGarage** [comment]
Can you try this https://github.com/qbcore-framework/qb-core/pull/988

**Comment by web-caos** [comment]
Yes, at the moment seems to fix the issue and client/server shared are in sync ;)
