### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gangstaaaaa** [qbcore-framework/qb-core#1019]
### Summary

when giving a player admin permission through adminmenu nothing saves after a server restarted making it not save or have permissions

### Reproduction

1. opened admin menu
2. friend joined
3. added their permission on the highest rank through the adminmenu
4. doesn't save after restarting the server

### Expected behavior

we expected a short way to add permission instead of going into server.cfg and add it

### Actual behavior

nothing saved

### Last Updated

today

### Custom Resources

none

### Resource Rename

qb-adminmenu

**Comment by Gangstaaaaa** [comment]
if i need to explain it better let me know

**Comment by djraymond1** [comment]
when you give admin permission via the menu it always leaves if you want the person to always have admin then you have to add them to the server cfg
