### ISSUE TITLE
Qb-core player.lua & qb-inventory error[BUG]

### ISSUE THREAD

**Issue by Bloodwolf707** [qbcore-framework/qb-core#1024]
### Summary

Qb-core player.lua & qb-inventory error

### Reproduction

i added the newest version of  qb-core & qb-invenotry and now everytime 
me and my player base load in, we load into a blackscreen.

### Expected behavior

i expected to load into my server without any issues.

### Actual behavior

[script:qb-multichara] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @qb-core/server/player.lua:183: No such export LoadInventory in resource qb-inventory

### Additional context

somebody tried to update this version of qb-core and didnt know what they were doing and broke it for everyone!

### Last Updated

today

### Custom Resources

n/a

### Resource Rename

no

**Comment by Domme03** [comment]
Still the issue?

**Comment by FransFX** [comment]
HasItem Function Also Broken

**Comment by MattiVboiii** [comment]
got the same export atm, any fix found? @Bloodwolf707

**Comment by Rtextbook** [comment]
im on fine with all of the latest, the only issue i see is stashes all inventories but players are reproducing in database
