### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adtgamer** [qbcore-framework/qb-core#1033]
### Summary

database erro

### Reproduction

[QBCORE] - A database error occurred while connecting to the server. (Is the SQL server on?)
![image](https://github.com/qbcore-framework/qb-core/assets/88980214/a8bbd107-470f-49b4-b486-db9917f06e34)

### Expected behavior

![image](https://github.com/qbcore-framework/qb-core/assets/88980214/189c04bf-3c5a-4e34-bc88-21c0bfdeaaf2)
Connection rejected by [adt](https://forum.cfx.re/u/adt)'s server: [QBCORE] - A database error occurred while connecting to the server. (Is the SQL server on?)

This is not a message from FiveM

### Actual behavior

Connection rejected by [adt](https://forum.cfx.re/u/adt)'s server: [QBCORE] - A database error occurred while connecting to the server. (Is the SQL server on?)

This is not a message from FiveM

### Additional context

Connection rejected by [adt](https://forum.cfx.re/u/adt)'s server: [QBCORE] - A database error occurred while connecting to the server. (Is the SQL server on?)

This is not a message from FiveM

### Last Updated

today

### Custom Resources

note

### Resource Rename

not

**Comment by djraymond1** [comment]
so the error is in front of you (Is the SQL server on?)

**Comment by Qwerty1Verified** [comment]
Seems like it's an issue with the server rather than qb-core. Feel free to create a support post in the discord channel.

**Comment by adtgamer** [comment]
with the old qbcore there is no error. updated today
When placing the old one there is no error.
When I update to this new one I get the error

**Comment by Qwerty1Verified** [comment]
Which error? The SQL error, or the native error? The error in the screenshot seems to relate to the recent commit that updates a QBCore function to use that native function. That native function does exist though, are your artifacts up to date?
