### ISSUE TITLE
[BUG] spawn selector always spawning at legion

### ISSUE THREAD

**Issue by ryan11444** [qbcore-framework/qb-core#1047]
### Summary

spawn selector always spawning at legion

### Reproduction

Nothing. It seemed to be working as far as I knew because on my 1st character it works properly. But every other player that joins and even any extra characters I create, the spawn selector always spawns at legion no matter what they pick. Unless they join /logout and select their character again, then it suddenly works. Also can't seem to store owned vehicles in the garages... Anyone know why this may be happening?

### Expected behavior

to be working...

### Actual behavior

not working...

### Last Updated

3 days ago

### Custom Resources

n/a

### Resource Rename

no

**Comment by alirezagood** [comment]
i had the same issue.
 i got it fixed by disabling qb-community-service
