### ISSUE TITLE
We are able to buy items from the store even without money[BUG]

### ISSUE THREAD

**Issue by NotOppi** [qbcore-framework/qb-core#1048]
### Summary

We are able to buy items from the store even without money

### Reproduction

1. Have no money
2. Buy an item from the store
3. Get the item (Tried with multiple store scripts so I assume it the way that QB-Core manages the money)

### Expected behavior

To not let you buy the item if you do not have enough money.

### Actual behavior

You can buy as many items you want if you do not have money.

### Last Updated

Couple of days - Using latest version of QB-Core

### Custom Resources

-

### Resource Rename

-

**Comment by nitrou5** [comment]
Do you happen to have money in your bank account? as it takes money from your bank account if you have no cash.
