### ISSUE TITLE
[BUG] Inventory Dupe

### ISSUE THREAD

**Issue by Saniity** [qbcore-framework/qb-core#1075]
### Summary

While eating/drnking or using an item that uses a progress bar, open your inv and swap any item with the item youre using over and over until the progress bar is finished

### Reproduction

1. use any usable item that uses the progress bar
2. open your inventory and take another item and swap it back and forth with the used item until the progress bar completes
3. boom duplicated item
4. clip https://youtu.be/R--9uDOyY7Y

### Expected behavior

Inventory to be not accessable while using an item that uses a progressbar

### Actual behavior

Inventory is accessable causing multiple dupe methods

### Last Updated

today

### Custom Resources

no

### Resource Rename

qb-inventory

**Comment by Rtextbook** [comment]
you can disable the use of inventory during progress bar.
