### ISSUE TITLE
[BUG] script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:93: attempt to call a nil valve (field IsPlayerBanned")

### ISSUE THREAD

**Issue by fivemplayer23444** [qbcore-framework/qb-core#1085]
### Summary

error in qb-core script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:93: attempt to call a nil valve (field IsPlayerBanned")

### Reproduction

script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:93: attempt to call a nil valve (field IsPlayerBanned")

### Expected behavior

script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:93: attempt to call a nil valve (field IsPlayerBanned")

### Actual behavior

dk

### Last Updated

didnt

### Custom Resources

none

### Resource Rename

no

**Comment by Lazylllama** [comment]
If you aren't going tlhe follow the form of creating a issue, they don't open one at all. This says nothing.
