### ISSUE TITLE
[BUG]: ps-inventory-main-main

### ISSUE THREAD

**Issue by BeardedSavage** [qbcore-framework/qb-core#1086]
### Summary

Getting error for ps-inventory-main-main under qb-mechanicjob

### Reproduction

Used item toolbox to inspect a vehicle. When trying to select option on toolbox menu it closes out and throw an error in the F8 menu.

### Expected behavior

To repair selected area with materials

### Actual behavior

Nothing

### Last Updated

Two days ago to latest qb-core framework

### Custom Resources

ps-inventory; ps-hud; ox_target

### Resource Rename

no

**Comment by Lazylllama** [comment]
What error are you getting? @BeardedSavage
