### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smcinroy1991** [qbcore-framework/qb-core#1090]
### Summary

Fire

### Reproduction

when driving cars are just randomly going on fire , this is just any car tryed different mechanic jobs but still does nothing 

### Expected behavior

drive normally

### Actual behavior

just driving normally , then car goes on fire then try to fix it then goes on car again

### Last Updated

yesterday

### Custom Resources

zdiscord

### Resource Rename

n

**Comment by MonsieurBibo** [comment]
Did you actually set `Config.UseDistanceDamage` to `false` in [qb-mechanicjob](https://github.com/qbcore-framework/qb-mechanicjob/blob/main/config/config.lua#L12)? Because otherwise, vehicles will become damaged while being driven and may catch fire if they are significantly damaged.
