### ISSUE TITLE
[BUG] nitrous item can't be used

### ISSUE THREAD

**Issue by daddygambler** [qbcore-framework/qb-core#1092]
### Summary

Hello i have problem because nitrous item is not possible to use

### Reproduction

Hello. I tried to use nitrous item in qbcore. I using ox_inventory. Everything like repairkit etc working well but problem exist only wiith nitrous. I can't do nothing with nitrous - not possible to use that item. How can i fix it?

### Expected behavior

working nitrous item

### Actual behavior

I tried to use nitrous item in qbcore. I using ox_inventory. Everything like repairkit etc working well but problem exist only wiith nitrous. I can't do nothing with nitrous - not possible to use that item. How can i fix it?

### Last Updated

3 weeks

### Custom Resources

nothing

### Resource Rename

no

**Comment by martin-lechene** [comment]
Check your qb-core/shared/item.lua and search your item and check if can use.

**Comment by daddygambler** [comment]
yes i have it and 'usable' is set to 'true'

**Comment by martin-lechene** [comment]
I think the problem is not with qb-core but with what else could have been added around it. Check more information on [qb-mechanicjob ](https://github.com/qbcore-framework/qb-mechanicjob) and send screen or more info on potential error.

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-mechanicjob/blob/6003c8b8a5f956dd5948e78ce5ee59346cced6ab/server/main.lua#L285
