### ISSUE TITLE
[SUGGESTION] FiveManage support

### ISSUE THREAD

**Issue by MrMallenby** [qbcore-framework/qb-core#1096]
### The problem

Script makers are starting to use [FiveManage](https://www.fivemanage.com/) for webhooks & image hosting etc and currently that results in needing to split where your logs are between discord and fivemanage

### Ideal solution

Add support for fivemanage, probably as an option so you can choose either fivemanage or discord depending on your needs as this would fix the issue of having logs etc in multiple locations making things more of a hassle for admins

**Comment by MrMallenby** [comment]
All the webhook related things in once place with search functionality instead of 10+ different channels on a discord server

**Comment by Cocodrulo** [comment]
But in QBCore there is not discord log. I'm talking about qb-core resource

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-smallresources/blob/71fd3eac5f12788694460a2364b9a21b5bf73166/server/logs.lua#L99
