### ISSUE TITLE
[BUG] qb-core your license is being checked

### ISSUE THREAD

**Issue by ChristianDCG26** [qbcore-framework/qb-core#1105]
### Summary

License Check

### Reproduction

How do I turn this off?
![Captura de pantalla (30)](https://github.com/qbcore-framework/qb-core/assets/160181088/08f1b9e3-b470-41c2-9da3-1feb10fd758f)

### Expected behavior

.

### Actual behavior

.

### Last Updated

.

### Custom Resources

no

### Resource Rename

qb-core

**Comment by Greazynugz** [comment]
having same issue. did you find fix?
