### ISSUE TITLE
[BUG] GetTotalWeight Missing export

### ISSUE THREAD

**Issue by Mikezaooo** [qbcore-framework/qb-core#1108]
### Summary

The GetTotalWeight export is missing

### Reproduction

Simply call https://github.com/qbcore-framework/qb-core/blob/main/server/player.lua#L575

### Expected behavior

Expected to return the total weight of passed items.

### Actual behavior

Return missing export at inventory

### Last Updated

today

### Custom Resources

no

### Resource Rename

qb-core

**Comment by GhzGarage** [comment]
Thanks https://github.com/qbcore-framework/qb-inventory/commit/afed825a9a74251f650c29f809c64fbf52d82991
