### ISSUE TITLE
[BUG] Error QB-Core

### ISSUE THREAD

**Issue by Furia4** [qbcore-framework/qb-core#1113]
### Summary

[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: bad argument #1 to 'next' (table expected, got nil) [      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252) [      script:qb-core] > runMicrotasks (<anonymous>:0) [      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96) [      script:qb-core]  [      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:456) [      script:qb-core] > handler (@qb-core/server/events.lua:105) [      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252) [      script:qb-core] > runMicrotasks (<anonymous>:0) [      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

### Reproduction

Just update the qb-core

### Expected behavior

Give me a solucion please

### Actual behavior

Show many errors in server 

### Last Updated

Today 

### Custom Resources

Yes many … qb-inventory, qb-multichar, qb-citywall

### Resource Rename

No

**Comment by JustinMurphyy** [comment]
Could be SQL Port or Database issue if it is searching for a table and returns a nil value. 
 (table expected, got nil) -processTicksAndRejections.

- Make sure you ran the qbcore.sql 
- maybe SQL Port is not active
- check load order in server.cfg
