### ISSUE TITLE
[BUG]Can't use weapon's ammo

### ISSUE THREAD

**Issue by 0Lamplight0** [qbcore-framework/qb-core#1116]
### Summary

Can't use weapon's ammo

### Reproduction

Can't use weapon's ammo

### Expected behavior

Can't use weapon's ammo

### Actual behavior

Can't use weapon's ammo

### Additional context

Can't use weapon's ammo

### Last Updated

today

### Custom Resources

qb all!

### Resource Rename

o

**Comment by Scartane** [comment]
hey @0Lamplight0 
Do a fresh install of qb-weapons since the problem come from here : [Fixes the gun reload](https://github.com/qbcore-framework/qb-weapons/commit/556b01a5985dbc3568b9f9152a719bf7c5615f9d)
