### ISSUE TITLE
[SUGGESTION] Make use of Lua OAL

### ISSUE THREAD

**Issue by EinS4ckZwiebeln** [qbcore-framework/qb-core#1120]
### The problem

Not really a problem per se, but enabling Lua OAL would benefit the performance of QBCore. 
Why isn't this done yet, or is there anything that would cause issues with this that I'm not aware of?

### Ideal solution

Enable Lua OAL by adding `use_experimental_fxv2_oal "yes"` to the fxmanifest.

**Comment by Z3rio** [comment]
OAL can possibly break some of the code, as native returns are changed, and so on.
So this is 110% doable, but we'd have to do some extensive testing to make sure everything works as its meant to.
