### ISSUE TITLE
[BUG] Item dropping on ground

### ISSUE THREAD

**Issue by jayjoe1** [qbcore-framework/qb-core#1121]
### Summary

When dropping an Item on the ground and reopening the inventory the item is on the ground but u cant pick it up anymore

### Reproduction

1. open qb-inventory 2.drop item on ground 3.close inventory 4.open inventory 

here is a pic what it looks like
![Bild_2024-06-18_101202195](https://github.com/qbcore-framework/qb-core/assets/173141766/408e7d72-202e-4e91-9784-82e8266a0bdf)
![Bild_2024-06-18_101241748](https://github.com/qbcore-framework/qb-core/assets/173141766/f9bca2df-b286-492c-9741-dc3a8296f591)

### Expected behavior

How /what do i change so i can pick the items back up to my inventory

### Actual behavior

-

### Additional context

-

### Last Updated

this week

### Custom Resources

-

### Resource Rename

-

**Comment by NotPhelps** [comment]
check your f8 this sound more like a issue with the inventory

**Comment by jayjoe1** [comment]
there is no f8 errors thats the thing
