### ISSUE TITLE
female health[BUG]

### ISSUE THREAD

**Issue by NotPhelps** [qbcore-framework/qb-core#1122]
### Summary

female get 175 health there has been a few fixes that have come out none that work with the new core or a real permeant fix 

### Reproduction

become a female mp and youlls see it right away and if you full heal and leave and join back they go right back to 175hp

### Expected behavior

have feamle health the same as males

### Actual behavior

feamles join with 175 each time

### Last Updated

a week ago

### Custom Resources

n/a

### Resource Rename

n/a

**Comment by Mycroft-Studios** [comment]
this is more something for the multicharacter
