### ISSUE TITLE
Framedrop issues

### ISSUE THREAD

**Issue by nick-perry14** [qbcore-framework/qb-core#113]
After installing the standard QB server, with a clean install, I notice that every couple of seconds, my frames cut to 40 for 1 singular frame, and my game rubber bands.  I know this must be an issue with QB since my esx server (running off the SAME box) does not suffer from the same issue, while being updated to the same server artifacts.  Not sure what is causing this, but my frames are higher, however more inconsistent.

**Comment by BJDubb** [comment]
>  my frames cut to 40 for 1 singular frame, and my game rubber bands.
Sounds like a client problem to me. The qb framework hasn't had a significant impact on my FPS and "rubber banding" is a network issue, unrelated to qb.

**Comment by nick-perry14** [comment]
> >  my frames cut to 40 for 1 singular frame, and my game rubber bands.
> 
> Sounds like a client problem to me. The qb framework hasn't had a significant impact on my FPS and "rubber banding" is a network issue, unrelated to qb.

See, I'd agree with you if not for the fact that I have another fivem server that works flawlessly on the same box.  That's why I'm thinking it might be qb.

**Comment by BJDubb** [comment]
It could be your implementation of qb then. Have you tried reinstalling? Are there any scripts dependent on qb that could be the cause. Im not sure how good you are with general resource debugging, but try typing `resmon 1` in your F8 console and seeing what the cause might be.

Hope this helps :)

**Comment by GhzGarage** [comment]
Run some profilers and post them here

**Comment by nick-perry14** [comment]
This sounds weird, but profiler recording stops it...?

**Comment by BerkieBb** [comment]
post it here let us have a look

**Comment by nick-perry14** [comment]
It will not let me post them on github, since I can't post .zips (for some reason) and .bins are not supported

**Comment by BerkieBb** [comment]
Post a screenshot of it if you can
