### ISSUE TITLE
[SUGGESTION] What version ?

### ISSUE THREAD

**Issue by phongvants123** [qbcore-framework/qb-core#1132]
### The problem

How to check the version of QB Core framework

### Ideal solution

How to check the version of QB Core framework, i've searching near and far, but could not find the version of the QB Core anywhere ?

**Comment by CxCore-xyz** [comment]
in the fxmanifest.lua

**Comment by nick-perry14** [comment]
Marking for closure as question answered.

**Comment by phongvants123** [comment]
But when i installed it thourh txadmin or zap , it said that version 4 ? 
In fxmanifest.lua it said version '1.2.6' ? 
So how to compare ?

**Comment by nick-perry14** [comment]
FX manifest is the correct place for the version
