### ISSUE TITLE
[BUG] Shop open with keybind not working

### ISSUE THREAD

**Issue by promiiss033** [qbcore-framework/qb-core#1136]
### Summary

cant open the shop with key E

### Reproduction

dont have target enabled in the server config, but for someresone qb-shops wont open, error:
qb-shops client > Main > 34, no such export keypressed in resource qb-core

local function listenForControl()
    if listen then return end
    CreateThread(function()
        listen = true
        while listen do
            if IsControlJustPressed(0, 38) then -- E
                exports['qb-core']:KeyPressed()
                TriggerServerEvent('qb-shops:server:openShop', { shop = currentShop })
                listen = false
                break
            end
            Wait(0)
        end
    end)
end

### Expected behavior

..

### Actual behavior

..

### Additional context

..

### Last Updated

latest version fresh install qb server

### Custom Resources

n/a

### Resource Rename

no

**Comment by kaynegraham** [comment]
Do you have the latest version of both resources, and is the core started before all other resources?

**Comment by promiiss033** [comment]
> Do you have the latest version of both resources, and is the core started before all other resources?

Its a fresh install so yes i assume

**Comment by brandon1808** [comment]
Do you have target turn on on your server ?

**Comment by TeamCR7** [comment]
-- TRY THIS --



local listen = false
local currentShop = {} -- Ensure this is properly defined elsewhere

local function listenForControl()
    if listen then return end
    CreateThread(function()
        listen = true
        while listen do
            if IsControlJustPressed(0, 38) then -- E key
                exports['qb-core']:KeyPressed()
                TriggerServerEvent('qb-shops:server:openShop', currentShop)
                listen = false
                break
            end
            Wait(0)
        end
    end)
end
