### ISSUE TITLE
weapons holding ammo 

### ISSUE THREAD

**Issue by hellbreezy420** [qbcore-framework/qb-core#1137]
### Summary

you can pull out the weapon im running all latest and i depoloyed a fresh server even 

### Reproduction

to reproduce the issue 
pull out weapon from inventory 
reload weapon 
put weapon back in inventory 
weapon ammo gone again no shooting 

### Expected behavior

when i pull up to a robbery after reloading my gun at the house I expect to still have my ammo in my gun when I get to the store  

### Actual behavior

i reload my gun at my house when i get to the store i have no ammo again never shot or anything 

### Additional context

soo it seems like every time i put the weapon up to where its not in my hand and only in inventory it dumps the clip 

### Last Updated

today and still no changes 

### Custom Resources

qb-target

### Resource Rename

no

**Comment by brandon1808** [comment]
Are you able to show a video so we can see the issues that your having

**Comment by hellbreezy420** [comment]
i dont have a video only discord and to stream it

**Comment by hellbreezy420** [comment]
its been like that Strate from tx deployer soo deply a new city 
then spawn a weapon 
reload the weapon 
then put the gun back in your inventory 
it instantly dumps the clip

**Comment by hellbreezy420** [comment]
> Are you able to show a video so we can see the issues that your having

there is error 
but that's how to recreate the issue

**Comment by hellbreezy420** [comment]
its a issue with qb weapons i got a different vs of qb weapons given to me and works fine
