### ISSUE TITLE
[BUG] Getting Teleported Back Into Vehicle

### ISSUE THREAD

**Issue by dthepriman** [qbcore-framework/qb-core#1140]
### Summary

For some reason, when exiting a spawned vehicle (from any job), I can’t get out of it. I can press F to get out, the ped gets out for a second but then It gets teleported back into the vehicle for no absolute reason. Can someone help please?

### Reproduction

I am currently using the latest QBCore base server build, did not modify anything other than the job file configs.

### Expected behavior

To let me out of vehicles...?

### Actual behavior

It teleports me back into the spawned vehicle

### Last Updated

today

### Custom Resources

nope

### Resource Rename

nope

**Comment by MadMarchel** [comment]
I have the same problem once i leave the server i get an error in the console

[      script:qb-core] SCRIPT ERROR: Execution of native 00000000afe92319 in script host failed: Tried to access invalid entity: 131073
[      script:qb-core] > SpawnVehicle (@qb-core/server/functions.lua:346)
[      script:qb-core] > ? (@qb-core/server/events.lua:254)
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:456)
[      script:qb-core] > handler (@qb-core/server/events.lua:128)

I've reinstalled qb-core after and still does not work

**Comment by minipunch** [comment]
Same!

Happening when spawning a police vehicle with qb-policejob on a pretty fresh copy of qb

**Comment by minipunch** [comment]
FIX: update your server artifact version ✔️
