### ISSUE TITLE
[BUG] attempt to index a nil value (global 'QBCore')

### ISSUE THREAD

**Issue by LFRobertooo01** [qbcore-framework/qb-core#1142]
### Summary

Pongo el script del admni menu de origen u me da este error

### Reproduction

poner el script 

### Expected behavior

q funcionara

### Actual behavior

q no funciono

### Additional context

![unnamed](https://github.com/user-attachments/assets/f976d5d9-60c2-4176-9c11-991c4cbf440f)

### Last Updated

hoy

### Custom Resources

qbcore

### Resource Rename

no

**Comment by GhzGarage** [comment]
Update your qb-adminmenu
