### ISSUE TITLE
[BUG] attempt to index a nil value (global 'qbcore')

### ISSUE THREAD

**Issue by LFRobertooo01** [qbcore-framework/qb-core#1143]
### Summary

Me sale estos errores y nose xq y no puedo solucionarlo

### Reproduction

poner el script 

### Expected behavior

q funcionara y no diese error

### Actual behavior

q me dio error

### Additional context

![unnamed](https://github.com/user-attachments/assets/998822cc-70df-4aef-9365-39c5dfa06a31)
![eor](https://github.com/user-attachments/assets/68eacea1-c9a5-42d7-abe8-86bde3a99b97)

### Last Updated

hoy

### Custom Resources

no

### Resource Rename

no

**Comment by GhzGarage** [comment]
Update your qb-policejob
