### ISSUE TITLE
[BUG]Two overlapping MLOs

### ISSUE THREAD

**Issue by JaysonLLL** [qbcore-framework/qb-core#1144]
### Summary

Two overlapping MLOs

### Reproduction

There are two overlapping MLOs at the airport arrival hall, how can I fix this?
Eliminating all possibilities, only qb is left.
It is not clear which script caused GTAV's original airport MLO to load.
![image](https://github.com/user-attachments/assets/6efbdbc2-5aa9-4417-9581-c78c3d9d0969)

### Expected behavior

Airport MLO should be displayed normally

### Actual behavior

Two overlapping MLOs

### Last Updated

today

### Custom Resources

Shmannworks-Airport

### Resource Rename

Shmannworks-Airport

**Comment by GhzGarage** [comment]
We don't have any MLO's at the airport
