### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CollapsedLegacy** [qbcore-framework/qb-core#1145]
### Summary

Hi, some of my players hop into my city and get the multicharacter stuck on their screen and need to refly.

### Reproduction

Not too sure, I asked them and it's only sometimes

### Expected behavior

n/a

### Actual behavior

n/a

### Additional context

https://cdn.discordapp.com/attachments/1291957909189824542/1291957909739147365/image.png?ex=67089491&is=67074311&hm=f9ea0ec0190e559873cd14dfb2fc8c4d1295fa4c7fa81ecf4403893cb2bce717& 

https://cdn.discordapp.com/attachments/1293085253916819507/1293085301501329428/image.png?ex=67081148&is=6706bfc8&hm=067603ab19be5e5e11a111977fa6488d20eb0a04c0dc95766c5d604ed606a4f2&

### Last Updated

today

### Custom Resources

n/a

### Resource Rename

n/a

**Comment by GhzGarage** [comment]
Ask for support in discord

https://discord.gg/qbcore
