### ISSUE TITLE
I wanted to give a suggestion for shared.lua

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-core#121]
The file is divided into a number of files Why
Ease of modification and access to what you need
Ease of tracking errors
create folder name shared
and put this file in shared folder

    vehicles.lua
    jobs.lua
    weapons.lua
    shared.lua -- for item
    I think the issue of the amendment is very important
    shared file 4554 line big file

I hope the suggestion will be of interest
It will be a wonderful modification to the project

**Comment by GhzGarage** [comment]
Feel free to personalize it like that for your own purposes
