### ISSUE TITLE
Cant Get Pass Checking Ban status

### ISSUE THREAD

**Issue by WhirlyBird321** [qbcore-framework/qb-core#127]
Hi There i am new to developing with this framework. But when ever I try load into the server it checks everything but when gets tho the part where it says "Chaecking If you are banned." It loads for about 30 seconds then I get the error 
[      script:qb-core] > handler (@qb-core/server/events.lua:40)
[ script:connectqueue] QUEUE: WhirlyBird[steam:1100001176dfd9b] was placed 1/1 in queue
[ script:ghmattimysql] [MySQL] [ERROR] [qb-core] An error happens for query "SELECT * FROM bans WHERE license=? : ["license:97470cc628a2266cf5a681899fead086094fbd94"]": connect ECONNREFUSED 127.0.0.1:3306
[      script:qb-core] SCRIPT ERROR: @qb-core/server/functions.lua:227: attempt to index a nil value (local 'result')
[      script:qb-core] > handler (@qb-core/server/events.lua:40)

please help I really want to make a qbus fivem server.

**Comment by GhzGarage** [comment]
Your database is not connected

**Comment by WhirlyBird321** [comment]
> Your database is not connected

I'm using PHP my admin how would I link it?

**Comment by GhzGarage** [comment]
ghmattimysql/config.json

**Comment by Chiefink5** [comment]
where do i find `ghmattimysql/config.json`?
