### ISSUE TITLE
Possible dupe method

### ISSUE THREAD

**Issue by Elior2739** [qbcore-framework/qb-core#129]
Hi!,

I found on a server a dupe method that is really to do
you just move item to a stash and exit right away.

From what I saw its because the database not updating when a item removes from a player inventory
I hope you will fix it soon because QBCore is a really good framework for RolePlay.

What I did to fix this is call `QBCore.Player.UpdateInventory()` every time item removes/adds to the player
I don't think what I did is a good idea but its pretty easy to fix like this

I hope you will fix this soon 😄

**Comment by GhzGarage** [comment]
The inventory saves on player save event event which is already done on exit

**Comment by Rtextbook** [comment]
noticing database is writing a new slot for the stashes and glovesboxes all around anytime you interact or something like that. then i delete them all out restart join up and its the items that were there orig. or what ever i leave left.
