### ISSUE TITLE
this is normal warining ?

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-core#133]
[ script:ghmattimysql] [MariaDB:10.4.20-MariaDB] [WARNING] [qb-banking] [517ms] SELECT * FROM bank_accounts WHERE account_type=? : ["Business"]
[ script:ghmattimysql] [MariaDB:10.4.20-MariaDB] [WARNING] [qb-core] [517ms] SELECT * FROM permissions : []
[ script:ghmattimysql] [MariaDB:10.4.20-MariaDB] [WARNING] [qb-houses] [515ms] SELECT * FROM houselocations : []
[ script:ghmattimysql] [MariaDB:10.4.20-MariaDB] [WARNING] [qb-spawn] [516ms] SELECT * FROM houselocations : []
[ script:ghmattimysql] [MariaDB:10.4.20-MariaDB] [WARNING] [qb-lapraces] [514ms] SELECT * FROM lapraces : []
[ script:ghmattimysql] [MariaDB:10.4.20-MariaDB] [WARNING] [qb-houses] [516ms] SELECT * FROM player_houses : []

**Comment by GhzGarage** [comment]
Yes
