### ISSUE TITLE
[SUGGESTION] Add some unclonable characteristic on an ID

### ISSUE THREAD

**Issue by nick-perry14** [qbcore-framework/qb-core#144]
Right now, it is possible for someone to steal an ID of another user.  There is nothing preventing this user from using that ID in a traffic stop to frame another user.  In real life, IDs have pictures which helps this.  As of now, players could be using other player's ids and there's no way for police to verify it at all.

Maybe add the civ's fingerprint-ID to the license?

**Comment by sinfuljosh** [comment]
logistically verifying a player with the fingerprint on the ID would require taking the player to a facility to process their fingerprint or have a new device similar to a brethalyzer that would be used. 

better alternative would be including the a face pic of the owner of the ID like you would in real world. as well as the ability for police to remove a players mask is needed, they could then compare face between ID and the player.  
(additionally if a player undergoes the knife and gets a new appearance they have to pay the city to have their ID picture updated)

**Comment by nick-perry14** [comment]
> logistically verifying a player with the fingerprint on the ID would require taking the player to a facility to process their fingerprint or have a new device similar to a brethalyzer that would be used.
> 
> better alternative would be including the a face pic of the owner of the ID like you would in real world. as well as the ability for police to remove a players mask is needed, they could then compare face between ID and the player.
> (additionally if a player undergoes the knife and gets a new appearance they have to pay the city to have their ID picture updated)

100% agree, though the only way I could see that being feasible would be to (whenever a player changes their physical appearance, not clothing) to take a new mugshot-type photo and save it in the meta-data of the item as a base64 string.  That way a nui could pop up with the person's photo decoded from base64.  I'd prefer your solution, though it may be a logistical nightmare
