### ISSUE TITLE
I'm to stupid to set myself admin

### ISSUE THREAD

**Issue by PC1up** [qbcore-framework/qb-core#146]
So I tried to become admin permissions on my own server  and tried the following steps:
1. Opened phpMyAdmin
2. Went to 'permissions' table
3. Clicked on "Insert"
4. Filled out 'name' with the name in the 'players' table
5. Filled out 'license' with the license in the 'players' table
6. Wrote 'god' into 'permission'

I also tried to use 'admin' instead of 'god', neither of them worked

**Comment by Mr-Pleb** [comment]
Have you restarted server?

**Comment by PC1up** [comment]
Yea I'm actually stupid. Restarting the server fixed it. ty
