### ISSUE TITLE
Whitelist with rockstar licenses

### ISSUE THREAD

**Issue by jaxonfromkh** [qbcore-framework/qb-core#148]
Qb is not compatible with steam now so how to get rockstar license if u are a normal player that want to register the whitelist

**Comment by BerkieBb** [comment]
You need a rockstar license to play gta5, otherwise you have a cracked version of the game to play FiveM

**Comment by jaxonfromkh** [comment]
And where i can find the license from if i got the original gta v already?

**Comment by BerkieBb** [comment]
When you join the server your license gets saved in the players table in your database

**Comment by jaxonfromkh** [comment]
No i want to know is any way for normal player check their license key for themself to register whitelist

**Comment by BerkieBb** [comment]
There is probably a way but I don't know it

**Comment by jaxonfromkh** [comment]
Pls tell me when u can find it thank you
