### ISSUE TITLE
can add array job

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-core#152]
QBCore.Functions.TriggerCallback('', function(result)
if result then
end
end, {'police', 'taxi', 'ambulance'})

Can these features be added to core ?

 QBCore.Functions.TriggerCallback('', function(result)
if result then
end
end, {'police', 'admin'})

**Comment by Developer-Bear** [comment]
@vanillla1 I don't understand what you're requesting here

**Comment by vanillla1** [comment]
@Developer-Bear look this https://github.com/qbcore-framework/qb-core/pull/101
