### ISSUE TITLE
weapon_bread weapon not working

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-core#156]
["weapon_bread"] 				 = {["name"] = "weapon_bread", 				 	["label"] = "Baquette", 				["weight"] = 1000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "baquette.png", 			["unique"] = true, 		["useable"] = false, 	["description"] = "Bread..?"},

https://ibb.co/7tHTx1n

**Comment by BerkieBb** [comment]
That's because you need the model for the bread, I think it's on gta5mods.com, search it up
