### ISSUE TITLE
Player metadata major problem!

### ISSUE THREAD

**Issue by maguhd** [qbcore-framework/qb-core#170]
Every player on my server gets the same metadata every now and then.
![Screenshot_12](https://user-images.githubusercontent.com/54622859/131354735-8281c4dd-c4eb-40a4-8dca-1591b1a8a67d.png)

After 1 player connects then his metadata sometimes remains the same, sometimes changes to his metadata.
![Screenshot_13](https://user-images.githubusercontent.com/54622859/131354854-18e9a027-146d-43d8-9598-6461c5a2b371.png)

I don't know what causes this.

**Comment by GhzGarage** [comment]
Neither do i
