### ISSUE TITLE
Question about playerConnecting

### ISSUE THREAD

**Issue by AvarianKnight** [qbcore-framework/qb-core#180]
https://github.com/qbcore-framework/qb-core/blob/512b1c9d9f13be3c508a0fdeddb3e0c27f4e0d3b/server/events.lua#L7

I had a question regarding the playerDropped event and how it is implemented.

Why does it check for reconnecting and if the source is a temp id (though servers can get to ids 65k+ before being tempids)

Would it not be better to implement it like

```lua
AddEventHandler('playerDropped', function(reason) 
	local src = source
	if QBCore.Players[src] then
		local Player = QBCore.Players[src]
		TriggerEvent("qb-log:server:CreateLog", "joinleave", "Dropped", "red", "**".. GetPlayerName(src) .. "** ("..Player.PlayerData.license..") left..")
		Player.Functions.Save()
		QBCore.Players[src] = nil
	end
end)
```

It makes the code more readable and removes checks that won't be needed

**Comment by GhzGarage** [comment]
Honestly not sure why it was coded like that but i've changed it per your recommendation as it seems the logical route
