### ISSUE TITLE
Wash Marked money?

### ISSUE THREAD

**Issue by ProbablyGeorgeP** [qbcore-framework/qb-core#185]
testing out the framework, how do i wash the money i get from a storerobbery

**Comment by QBCORE** [comment]
they should add something like this in qb-traphouse 

my function here its not verified 
-----------------------------------------------------------------------------------------------
function SellTimeout(traphouseId, slot, itemName, amount, info)
    Citizen.CreateThread(function()
        if itemName == "markedbills" then
            SetTimeout(math.random(30000, 50000), function()
                if Config.TrapHouses[traphouseId].inventory[slot] ~= nil then
                    RemoveHouseItem(traphouseId, slot, itemName, 1)
                    Config.TrapHouses[traphouseId].money = Config.TrapHouses[traphouseId].money + math.ceil(info.worth / 100 * 80)
                    TriggerClientEvent('qb-traphouse:client:SyncData', -1, traphouseId, Config.TrapHouses[traphouseId])
                end
            end)
        elseif itemName == "cash_roll" then
            SetTimeout(math.random(10000, 15000), function()
                if Config.TrapHouses[traphouseId].inventory[slot] ~= nil then
                    RemoveHouseItem(traphouseId, slot, itemName, 1)
                    Config.TrapHouses[traphouseId].money = Config.TrapHouses[traphouseId].money + math.ceil(info.worth / 100 * 65)
                    TriggerClientEvent('qb-traphouse:client:SyncData', -1, traphouseId, Config.TrapHouses[traphouseId])
                end
            end)
        elseif itemName == "cash_stack" then
            SetTimeout(math.random(10000, 15000), function()
                if Config.TrapHouses[traphouseId].inventory[slot] ~= nil then
                    RemoveHouseItem(traphouseId, slot, itemName, 1)
                    Config.TrapHouses[traphouseId].money = Config.TrapHouses[traphouseId].money + math.ceil(info.worth / 100 * 65)
                    TriggerClientEvent('qb-traphouse:client:SyncData', -1, traphouseId, Config.TrapHouses[traphouseId])
                end
            end)
        else
            for i = 1, amount, 1 do
                local SellData = Config.AllowedItems[itemName]
                SetTimeout(SellData.wait, function()
                    if Config.TrapHouses[traphouseId].inventory[slot] ~= nil then
                        RemoveHouseItem(traphouseId, slot, itemName, 1)
                        Config.TrapHouses[traphouseId].money = Config.TrapHouses[traphouseId].money + SellData.reward
                        TriggerClientEvent('qb-traphouse:client:SyncData', -1, traphouseId, Config.TrapHouses[traphouseId])
                    end
                end)
                if amount > 1 then
                    Citizen.Wait(SellData.wait)
                end
            end
        end
    end)
end

----------------------------------------------

function CanItemBeSaled(item)
    local retval = false
    if Config.AllowedItems[item] ~= nil then
        retval = true
    elseif item == "markedbills" then
        retval = true
    elseif item == "cash_roll" then
        retval = true
    elseif item == "cash_stack" then
        retval = true
    end
    return retval
end

**Comment by ProbablyGeorgeP** [comment]
Let me get this straight, if i add this to qb traphouse i will be able to wash marked bills from store robberies? Also where do i add this, which .lua?

**Comment by QBCORE** [comment]
not working yet this function am tryin to fix it now .. if i fix it i'll send it to you gimme few moments

**Comment by QBCORE** [comment]
i fix it how do i send u the resource !!?

**Comment by ProbablyGeorgeP** [comment]
Email? gpogue10@outlook.com

**Comment by QBCORE** [comment]
check your mail and there is another interior that im using u need to change it

**Comment by ProbablyGeorgeP** [comment]
thankyou

**Comment by ProbablyGeorgeP** [comment]
i take it the money wash is an interaction inside the trap house?

**Comment by ProbablyGeorgeP** [comment]
it doesnt work

**Comment by QBCORE** [comment]
don't use command giveitem cash_roll you should rob a store try it

**Comment by ProbablyGeorgeP** [comment]
do you have discord? Im having some issues with this, is add me George P#5036

**Comment by GhzGarage** [comment]
Marked bills are washed via the traphouse

**Comment by ProbablyGeorgeP** [comment]
The qb_traphouse resource i was sent just literally does not work
