### ISSUE TITLE
HungerRate issue wiith oxMySql

### ISSUE THREAD

**Issue by SepticLime** [qbcore-framework/qb-core#188]
[      script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:96: attempt to perform arithmetic on a nil value (field 'HungerRate')

**Comment by IdrisDose** [comment]
You need to add the option to the config :)

**Comment by SepticLime** [comment]
>  QBConfig.Player.HungerRate = 4.2 -- Rate at which hunger goes down. 
>  QBConfig.Player.ThirstRate = 3.8 -- Rate at which thirst goes down.

I have added to config already.

QBConfig.Player = {}
QBConfig.Player.MaxWeight = 120000 -- Max weight a player can carry (currently 120kg, written in grams)
QBConfig.Player.MaxInvSlots = 41 -- Max inventory slots for a player
QBConfig.Player.HungerRate = 4.2 -- Rate at which hunger goes down.
QBConfig.Player.ThirstRate = 3.8 -- Rate at which thirst goes down.
QBConfig.Player.Bloodtypes = {
    "A+",
    "A-",
    "B+",
    "B-",
    "AB+",
    "AB-",
    "O+",
    "O-",
}

**Comment by am3nd01m** [comment]
What is this oxmysql? my server is all bugged after updating with oxmysql changes

**Comment by SepticLime** [comment]
> What is this oxmysql? my server is all bugged after updating with oxmysql changes

Ensure you have newest version of oxmysql, version 1.2. Update all QBCore scripts and database. Ensure oxmysql before qb-core in cfg. 


oxmysql pretty much ditches steam and ghmatti
