### ISSUE TITLE
What is oxmysql

### ISSUE THREAD

**Issue by am3nd01m** [qbcore-framework/qb-core#191]
My server stopped working when I updated the scripts with the "export oxmysql..."
What is this?

**Comment by IdrisDose** [comment]
OXMySQL is the successor to ghmattimysql:

If you're on their discord it explains what the go is and how to update to it.

**Comment by Laalalaaalaa** [comment]
How do you update it if you’re not on the discord?

**Comment by GhzGarage** [comment]
Why do you have to be on the discord to update?

**Comment by Laalalaaalaa** [comment]
> Why do you have to be on the discord to update?

The above comment said if you’re on the discord it explains it :/ I’m not sure what has happened but my whole server will not work

**Comment by GhzGarage** [comment]
So join the discord for support or go back to use ghmattimysql

**Comment by Laalalaaalaa** [comment]
What do I do to fix it?

**Comment by evanillaa** [comment]
my bro ghmattimysql become a thing of the past
Write your entire problem in Discord
look up to link
https://github.com/qbcore-framework

**Comment by ProbablyGeorgeP** [comment]
> OXMySQL is the successor to ghmattimysql:
> 
> If you're on their discord it explains what the go is and how to update to it.

how do i find the discord?
