### ISSUE TITLE
Why is the multi used for gui.lua?

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-core#194]
Can import be used gui.lua?
Instead of using files everywhere
We are trying to access the virtuous files
Plato's virtuous files

https://github.com/qbcore-framework/qb-mechanicjob/tree/main/client
https://github.com/qbcore-framework/qb-towjob/tree/main/client
https://github.com/qbcore-framework/qb-truckerjob/tree/main/client
https://github.com/qbcore-framework/qb-taxijob/tree/main/client
https://github.com/qbcore-framework/qb-ambulancejob/blob/main/client/gui.lua
https://github.com/qbcore-framework/qb-diving/tree/main/client
https://github.com/qbcore-framework/qb-houses/tree/main/client
https://github.com/qbcore-framework/qb-newsjob/tree/main/client
https://github.com/qbcore-framework/qb-apartments/tree/main/client
https://github.com/qbcore-framework/qb-garages/tree/main/client
https://github.com/qbcore-framework/qb-policejob/tree/main/client

**Comment by GhzGarage** [comment]
We are in the process of making a menu system for the framework that will replace all these

**Comment by evanillaa** [comment]
Can we get a stable version soon?
@GhzGarage
