### ISSUE TITLE
got this error in Functions.IsPlayerBanned

### ISSUE THREAD

**Issue by jaxonfromkh** [qbcore-framework/qb-core#208]
![image](https://user-images.githubusercontent.com/61196803/134141016-2c328848-b010-438e-a3a8-11580444cbe4.png)

**Comment by PeppeStan** [comment]
Hi, can you tell us a little bit more about what happened and in wich time (maybe in a certain situation)

**Comment by jaxonfromkh** [comment]
It's pop up sometime when player load the character but it didn't got any error with database or any function its just pop up this error code in console only
