### ISSUE TITLE
QB-Core & FivePD

### ISSUE THREAD

**Issue by dpelicano** [qbcore-framework/qb-core#209]
Is QB-Core & FivePD compatible? If so, how do I set that up?

**Comment by PeppeStan** [comment]
Hi, this is an Issue section generally used for issues with code and scripts, for any questions please use discord with the proper channel: https://discord.gg/qbcore  
About FivePD and QB-Core, those are two frameworks or gamemodes, so there is no way you can "set that up" in a simple way, you can try to use qb-core and implement scripts and mods for police and jobs or just use FivePd if you are not able to do it.

Regards, Peppe
