### ISSUE TITLE
issue with qb-clothing

### ISSUE THREAD

**Issue by supermatrixxx** [qbcore-framework/qb-core#210]
Hello, Im having some problems with custom player models (streaming) and qb-clothing store. Characters were tested using vMenu and all added components worked excellent, opening them with qb-clothing loads them and everything is fine, but right after changing component:HEAD or component:HAIR just completely glitches out geometry (check provided imgur link). This only happens with Heads and Hair, with everything else no issues what so ever. I've tested with many different player models and It's always the same story, changing head or hair glitches out geometry completely. Please anyone share their opinions about this weird bug. https://imgur.com/mrljPf5

**Comment by PeppeStan** [comment]
Does it gives you some kind of warning server side or consolle side? Try the hairs not with the various skin in the game but with the customizable player model (mp_freemode)
Some usefull tutorial - https://forum.cfx.re/t/how-to-streaming-addon-clothes-and-ped-props-for-mp-freemode-models/458854

**Comment by supermatrixxx** [comment]
Is there any link between qb-character and custom streamed peds?

**Comment by evanillaa** [comment]
My experience was bad there are problems between qbcore and addon ped

**Comment by supermatrixxx** [comment]
I know that I'm streaming my custom ped correctly, Its just that qb-clothing does not read properly given .ymt file for a specific addon ped. I've noticed that it does not matter which player model you pick from the store, it will always display 44 available heads and that is the root cause for this weird geometry bug. Anyway, is there like other scripts that works on qb but will not have this wierd glitch?

**Comment by supermatrixxx** [comment]
Also, this glitch only appears if all ped components are divided (like this: https://imgur.com/Pn9Nb7W ), but if you stream ped, that has all .ydd files compressed together (and same with .ytd files) then there are no issues. But with this comes another problem, memory limits, so yeah, i have no clue what to do.

**Comment by evanillaa** [comment]
add your comment here please
https://github.com/qbcore-framework/qb-multicharacter/issues/25
@supermatrixxx

**Comment by supermatrixxx** [comment]
which one?

**Comment by Shotoki** [comment]
I also came across this.  any update to this issue?
