### ISSUE TITLE
SQL : ghmattimysql -> OXMYSQL

### ISSUE THREAD

**Issue by sony3black** [qbcore-framework/qb-core#212]
Hello,

I would like to understand, why you have to change the SQL system?

what are the differences ?

**Comment by MrWhitee4** [comment]
Becuase QBCORE switched to OXMYSQL. "ghmattimysql" is not being updated anymore and doesn't use MySQL2 and OXMYSQL does.

**Comment by sony3black** [comment]
I guess it's more faster?
