### ISSUE TITLE
GetVehicleProperties

### ISSUE THREAD

**Issue by BlacknGoldy** [qbcore-framework/qb-core#213]
Hi
after the new update when im trying to buy a car, custom a car, or even with admin menu buy a car for my self im getting this error all the time

Attempt to call a nil value (field 'GetVehicleProperties')
in all scripts is about that QBCore.Functions.GetVehicleProperties(veh)
any solution ?

**Comment by MrWhitee4** [comment]
Have you updated the vehicleshop to the current version of GitHub? Have you updated QBCORE and switched to OXMYSQL? For me it works perfectly fine and I cannot replicate the issue.

**Comment by BlacknGoldy** [comment]
fix it ^^
