### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SoStressful** [qbcore-framework/qb-core#218]
**Describe the bug**
When you update to the latest QBCore update it causes Handcuffing and Sharing of contact details to stop working. There is no script error client-side or server-side.

**To Reproduce**
1. Update to the latest QBCore update
2. Try to share contact details or handcuff someone
3. Look at the top right-hand corner of your screen
4. "No one is nearby"

**Expected behavior**
A successful handcuff or shared contact details.

**Screenshots**
https://i.imgur.com/puNumXr.jpeg

**Questions (please complete the following information):**
 - When you last updated: Every update released.
 - Are you using custom resource? N/A
 - Have you renamed `qb-` to something custom? No

**Additional context**
Tested on someone else's server that also updated and received the same outcome.

**Comment by lildiznick** [comment]
Also get the same "No one Nearby" message when jailing through radial menu.

**Comment by googleoblivion** [comment]
![image](https://user-images.githubusercontent.com/2222973/134770478-35a18540-340a-4d2e-a420-0bf099fad895.png)
I don't know the difference in these styles of creating a table. Reverting back this one line solves this bug.

**Comment by GhzGarage** [comment]
Thanks for the report I will fix this as soon as possible

**Comment by GhzGarage** [comment]
Try this https://github.com/qbcore-framework/qb-core/commit/ddc396d2c99799c60dd1cf94f7f659177ededb90
