### ISSUE TITLE
[BUG] Last Location

### ISSUE THREAD

**Issue by Hiperinio** [qbcore-framework/qb-core#219]
**Describe the bug**
When you updated to the latests qbcore version via TXAdmin Last Location is not working

**To Reproduce**
1. Log in to the server and spawn.
2. TP Random to the map and disconnect
3. Relog to the game and select Last Location
4. You will be spawned on the Airport

**Expected behavior**
Spawn to the last location you was before the log out.

**Questions (please complete the following information):**
 - When you last updated: Few hours ago, clean server from TXAdmin
 - Are you using custom resource? which ones?: No
 - Have you renamed `qb-` to something custom?: No

**Comment by lildiznick** [comment]
Had this happen in my server after update as well.  Except, it spawned me at the luxury car dealer.  That was the last location I had exited the game from prior to update.

**Comment by GhzGarage** [comment]
Do you have onesync enabled?

**Comment by Hiperinio** [comment]
> Do you have onesync enabled?

yes

**Comment by GhzGarage** [comment]
Hmm I’m not too sure then because as long as that is enabled it saves for me and a few others that I had test it. I’ll keep trying

**Comment by Reversy** [comment]
Same here

**Comment by GhzGarage** [comment]
Fixed https://github.com/qbcore-framework/qb-core/commit/34c574daf295ff1c3f1ebe4447d51a2a82b9ebdc
