### ISSUE TITLE
[SUGGESTION] : Review closed suggestions

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-core#223]
Review closed suggestions

https://github.com/qbcore-framework/qb-core/pull/211

https://github.com/qbcore-framework/qb-core/pull/195

https://github.com/qbcore-framework/qb-core/pull/147

**Comment by evanillaa** [comment]
And we want a clear example of isLoggedIn how to using
In the project scripts

**Comment by evanillaa** [comment]
https://github.com/qbcore-framework/qb-core/pull/200

**Comment by evanillaa** [comment]
and thank you for new update

**Comment by xenfovn** [comment]
https://github.com/qbcore-framework/qb-core/pull/214

**Comment by GhzGarage** [comment]
> And we want a clear example of isLoggedIn how to using
> In the project scripts

https://github.com/qbcore-framework/qb-afk/blob/main/client/main.lua

**Comment by evanillaa** [comment]
> 
> 
> > And we want a clear example of isLoggedIn how to using
> > In the project scripts
> 
> https://github.com/qbcore-framework/qb-afk/blob/main/client/main.lua

Can it be summed up in one or two lines?
The real benefit of the new update?
Will it affect the performance of the scripts in general?
Is the change assuming that one of the servers is running another core?
Do scripts project will run smoothly?

**Comment by evanillaa** [comment]
https://github.com/qbcore-framework/qb-core/pull/200#pullrequestreview-759216752

**Comment by darknight2590** [comment]
https://github.com/qbcore-framework/qb-core/issues/138

https://github.com/qbcore-framework/qb-core/issues/139
