### ISSUE TITLE
[BUG] Multiple bugs after major update

### ISSUE THREAD

**Issue by EvilGnome93** [qbcore-framework/qb-core#224]
**Describe the bug**
I encountered a few bugs after the major update.
- Cornerselling doesn't work anymore
- /ooc and /staffchat doesn't work
- Can't take out a cop car from the garage

**To Reproduce**
- Do the things mentioned above, and check f8

**Expected behavior**
No errors lol

**Questions (please complete the following information):**
 - When you last updated: Today (lastest major)
 - Are you using custom resource? which ones? For this; no
 - Have you renamed `qb-` to something custom? no

**Comment by Reversy** [comment]
Same for qb-drugs deliveries

**Comment by EvilGnome93** [comment]
Drugs issue has been resolved after the last updates updates for me
![PD](https://user-images.githubusercontent.com/74958801/134798541-f03de03d-cde7-4bb6-a060-7988a74311e9.jpg)
![Chat](https://user-images.githubusercontent.com/74958801/134798543-4ef22e17-3b23-41a6-96ce-5008e90f82d9.jpg)
.

**Comment by HATE-dev** [comment]
> Drugs issue has been resolved after the last updates updates for me
> 
> Pictures form the other :
> ![PD](https://user-images.githubusercontent.com/74958801/134798541-f03de03d-cde7-4bb6-a060-7988a74311e9.jpg)
> ![Chat](https://user-images.githubusercontent.com/74958801/134798543-4ef22e17-3b23-41a6-96ce-5008e90f82d9.jpg)
> .

Did you checked your config?  Check config for "Config.AuthorizedVehicles" and make sure you added right model names.

**Comment by EvilGnome93** [comment]
> Did you checked your config?  Check config for "Config.AuthorizedVehicles" and make sure you added right model names.

Never touched that... we're still using default cars. Its just happening after major update

**Comment by EvilGnome93** [comment]
Fixxed the police car issue.
But still having issues with /ooc and /staffchat

**Comment by Bigbearbeasttv** [comment]
Could not reproduce. All chats work fine with newest updates for me.

**Comment by EvilGnome93** [comment]
> Could not reproduce. All chats work fine with newest updates for me.

You're using the default chat or a external?

**Comment by Bigbearbeasttv** [comment]
Live Server external, dev server default. Both work fine without issue for me.

**Comment by EvilGnome93** [comment]
> Live Server external, dev server default. Both work fine without issue for me.

Uch so weird, never touched the chat script :( i'll try to find en source and redownload it

**Comment by GhzGarage** [comment]
discord.gg/qbcore
