### ISSUE TITLE
[BUG] qb-houses error code

### ISSUE THREAD

**Issue by LateNightRP** [qbcore-framework/qb-core#226]
**Describe the bug**
I encountered a bugs with qb-houses after the major update.

**To Reproduce**
1. Set myself for the realestate job to make a house.
2. Created a house with a garage.
3. Set myself as unemployed to purchase the house.
4. Purchased the house, and was able to go inside and place down "setstash" and "setoutift" just fine.
5. Had no issues till I restarted the server. When i logged back in I was not able to enter the house. That is when this error code appeared in F8. 
6. Weird thing is if I restart my game and make another house it works just fine, till I restart the server. Then both houses thro this error code. 

**Expected behavior**
Expected nothing to happen.

**Screenshots**
[Photo of F8 Error Code](https://cdn.discordapp.com/attachments/859528707814981653/891624295854407710/218_20210926041405_1_2.png)

**Questions (please complete the following information):**
 - When you last updated: Today (lastest major)
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by LateNightRP** [comment]
My apologies. I just realized I posted this in qb-core.

**Comment by Eralpozcan** [comment]
I tried this issue as you did. After purchasing,I will set stash/outfits, I exited the game and restarted the server. However, when I entered, the house was still stay and I was able to get in and out of the house. I did not encounter any problems.


Did you specify a tier greater than 7 when creating the house?

**Comment by LifeStyleRolePlay** [comment]
I've also replicated these steps but could not get the error that you did.

**Comment by HATE-dev** [comment]
Check your server for any sql errors and try with fresh resource.

**Comment by GhzGarage** [comment]
discord.gg/qbcore for support on this
