### ISSUE TITLE
Spawn character[BUG]

### ISSUE THREAD

**Issue by Slay3rIQ** [qbcore-framework/qb-core#234]
I have created a character but after updating the core I am now spawning in game as Michael.

**Comment by ihyajb** [comment]
Could not reproduce, Using more recent QBCore resources

**Comment by Slay3rIQ** [comment]
> Could not reproduce, Using more recent QBCore resources

I have download the core like a week ago -.-

**Comment by Bigbearbeasttv** [comment]
Use the latest version and check for errors. Latest build has no spawn issues.
