### ISSUE TITLE
[BUG] QBShared.Weapons Breaking qb-weapons

### ISSUE THREAD

**Issue by WolfieValeo** [qbcore-framework/qb-core#235]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Use Ammo to reload weapon
2. Ammo acts like its being used but doesnt actually use or remove
3. See error

**Expected behavior**
Reload ammo into weapon

**Screenshots**
https://i.imgur.com/qcHxcvg.png

**Questions (please complete the following information):**
 - When you last updated: Fully updated as of tonight.
 - Are you using custom resource? which ones? N/A
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

**Comment by nagsterFVZ** [comment]
Looking at that line it would appear you are getting a nil value for QBCore.Shared.Weapons this would probably mean that something is wrong in your qb-core/shared.lua. Have you made any changes to it and are you using any custom weapons?

**Comment by WolfieValeo** [comment]
Not using any addon weapons, nor have i changed anything to do with weapons. it worked fine before the large core update but hasn't since. ive matched my shared lua with the default one for the same section several times and both are the same.

**Comment by GhzGarage** [comment]
![20211001201658_1](https://user-images.githubusercontent.com/57848836/135699341-1cf8d1f5-5e26-4f66-9eba-e1868ff620d1.jpg)
