### ISSUE TITLE
[BUG] Weapons will not receive ammo after core update

### ISSUE THREAD

**Issue by bruinp8n** [qbcore-framework/qb-core#236]
**Describe the bug**
Every player that pulls out a weapon, it says 0, 0 for ammo,

I went through and tried to debug what the issue could be in both weapons and inventory.  

The hashkey, weapon name, and ammo values are all what they should be, but when I put a print statement to check the weapon ammo in the gun right after it is set, it returns -2147483648... no matter what weapon that is pulled out, it always returns this value
            
            GiveWeaponToPed(ped, GetHashKey(weaponName), ammo, false, false)
            SetPedAmmo(ped, GetHashKey(weaponName), ammo)
            SetCurrentPedWeapon(ped, GetHashKey(weaponName), true)
            print(GetAmmoInPedWeapon(ped, GetHashKey(weaponName)))

If you try to add ammo, qb-weapons throws a "Max capacity" notification error, So I went to "weapon:client:AddAmmo" in qb-weapons and added a print after:

local found, maxAmmo = GetMaxAmmo(ped, weapon)
print(maxAmmo)

It always returns -2147483648 aswell... no matter what weapon I switch to.   I can't for the life of me figure this out, this appeared affter I updated the major qb-core changes.

Ultimately, weapons don't appear to receive any ammo attempted to be added.

**To Reproduce**
1. Pull a weapon out (0 ammo, 0 clip), item info still shows proper values

**Expected behavior**
Weapon should display ammo and be fireable, aswell as should be able to add ammo

**Screenshots**
![image](https://user-images.githubusercontent.com/60456694/135058368-41b1581d-0bc8-481c-9b28-ed2621446229.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] yesterday
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] a few custom scripts mostly core scripts, nothing effecting this
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
qb-inventory/qb-weapons is right from repo, most all my scripts are.

Im using latest stable artifact aswell.

**Comment by bruinp8n** [comment]
i don't know  what to do, it makes absolutely no sense and im not sure how to fix

**Comment by bruinp8n** [comment]
I tried to check were the ammo is set, here is the code and here is the print statement in qb-inventory under useWeapon:

![image](https://user-images.githubusercontent.com/60456694/135169021-20a05873-56c5-4a33-9c88-dd99799fe776.png)

![image](https://user-images.githubusercontent.com/60456694/135169049-791c6019-2a85-4263-9236-8336adfbbe8e.png)

**Comment by Bigbearbeasttv** [comment]
Also Could not reproduce. Running Latest TXAdmin Build. I also testing with /setammo and everything worked as it should. could not find any issues with latest.

**Comment by bruinp8n** [comment]
So the native SetPedAmmo call doesnt appear to be working from all my extensive testing, or if it is working, it unsets itself in the same frame to -2147483648... Also if i call GetMaxAmmo on any of the weapons it also returns  -2147483648... 

i am completely dumfounded.  Is it possible i missed something in the core update that would cause something like this?

**Comment by bruinp8n** [comment]
go ahead and close, narrowed it down to a typo on an export causing fivem natives to not work properly

**Comment by Flek26** [comment]
> go ahead and close, narrowed it down to a typo on an export causing fivem natives to not work properly

how did you fix this??
