### ISSUE TITLE
Disconnect - Reconnect leads to a black screen

### ISSUE THREAD

**Issue by dbiegunski** [qbcore-framework/qb-core#24]
![image](https://user-images.githubusercontent.com/9666925/122494463-67a89b80-cfb7-11eb-96c4-0054c9627644.png)
![image](https://user-images.githubusercontent.com/9666925/122494500-7d1dc580-cfb7-11eb-8f22-aa2f6d511771.png)

I have to kill FiveM and relaunch FiveM to join properly.

Default FiveM resources have been updated from https://github.com/citizenfx/cfx-server-data/tree/master/resources but no luck.

**Comment by ImpulseFPS** [comment]
wasn't this fixed yesterday?

**Comment by GhzGarage** [comment]
Add ensure basic-gamemode to your server.cfg

The recipe server.cfg has been updated to prevent this black screen. Thanks
