### ISSUE TITLE
Random dying

### ISSUE THREAD

**Issue by Slay3rIQ** [qbcore-framework/qb-core#240]
Hello,

I was searching for some coords when I randomly died. I can't revive myself with a command or admin menu. Also the time counter stays on 300 seconds. I was in NoClip and Godmode so it shouldn't happen it all. 

![unknown](https://user-images.githubusercontent.com/90642225/135162150-a8126794-65aa-46c2-8d2a-52b9dbf5fa9d.png)

**Comment by Bigbearbeasttv** [comment]
You probably do not have the latest build.

**Comment by Slay3rIQ** [comment]
> You probably do not have the latest build.

I have the last core and the last scripts from everything. I also get this and yeah I know it says qb-assets but it comes from this github.

![image](https://user-images.githubusercontent.com/90642225/135171406-530c70d0-f40b-4621-a515-98195e205c05.png)

**Comment by evanillaa** [comment]
There is no file in the project named qb-assest
look your error
@Slay3rIQ

**Comment by Slay3rIQ** [comment]
> There is no file in the project named qb-assest look your error @Slay3rIQ

I also dont have a qb-assets in my server. I download the ambulance-job from this github.
