### ISSUE TITLE
[BUG] when i updated my server side main to the latest one

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-core#241]
![image](https://user-images.githubusercontent.com/78902920/135197340-d1d510de-9bfd-4df0-a8b4-ef4a0e9f57f4.png)
so when ever i put this code in i started to get QBCore is Nil on every script i have , so i had to rework to the last version folder i download to get back where it was at

**Comment by Eralpozcan** [comment]
The simplest solution for these situations seems to me to add to your fxmanifest file:

```
shared_scripts { 
	'@qb-core/import.lua',
}
```
make such an addition.When you do this part.

`
QBCore=nil
Citizen.CreateThread(function()
	while QBCore == nil do
		TriggerEvent('QBCore:GetObject', function(obj) QBCore = obj end)
		Citizen.Wait(0)
	end
end)`

You can remove these parts. And that will optimize for you.

**Comment by migogang2x** [comment]
When added to resource.lua of script like my phone it wont work ive been having this same problem but update fixes alot of other problems also x/. i also deleted QBcore = nil in server side and client still wont work and most my scripts run with that code

**Comment by migogang2x** [comment]
FIXXX!!!! what you need to do is where it says. QBcore = nil or QBcore == nil in server or client file change it to 

exports['qb-core']:GetCoreObject()

compared the files and in the core it actually says.....


-- To use this export in a script instead of manifest method
-- Just put this line of code below at the very top of the script
-- local QBCore = exports['qb-core']:GetCoreObject()

**Comment by Crowley0527** [comment]
lines?

**Comment by migogang2x** [comment]
relaplace 

QBCore = nil
TriggerEvent('QBCore:GetObject', function(obj) QBCore = obj end)

with 

QBcore = exports['qb-core']:GetCoreObject()  

top of server file

QBCore = nil

with

QBcore = exports['qb-core']:GetCoreObject() 

this 1 happens in server and client


Citizen.CreateThread(function() 
    while true do
        Citizen.Wait(10)
        if QBCore == nil then
            TriggerEvent("QBCore:GetObject", function(obj) QBCore = obj end)    
            Citizen.Wait(200)
        end
    end
end)



change if QBCore == nil then
            TriggerEvent("QBCore:GetObject", function(obj) QBCore = obj end) 

to 

QBcore = exports['qb-core']:GetCoreObject() 

should look like

Citizen.CreateThread(function() 
    while true do
        Citizen.Wait(10)
        if QBCore == nil then
            TriggerEvent("QBCore:GetObject", function(obj) QBCore = obj end)    
            Citizen.Wait(200)
        end
    end
end)

found in server side

**Comment by migogang2x** [comment]
now the import.lua isnt working right with the mods i didnt even touch. my local host works but as soon as i upload vps it breaks oxmysql so i had to redownload it and delete the 1 you gave me now aj-inventory qb-core and anti throw errors for import.lau because its not worded right . ill post fix

**Comment by Eralpozcan** [comment]
The case we propose should actually work. We are currently working. You're doing something wrong, but I don't think we understand what it is.
It works very stable in the original repo, I update it every day.
The import.lua solution was made before the last update and it is still valid and I am actively using it. You can get a more detailed and faster solution to your questions on discord.


[Discord QBCore](discord.gg/qbcore)

**Comment by migogang2x** [comment]
issue resolved qb-core must start first sorry

**Comment by Eralpozcan** [comment]
@GhzGarage Please Close. Problem is fix.
