### ISSUE TITLE
Updated to new core half of scripts wont work ?

### ISSUE THREAD

**Issue by mobius6666** [qbcore-framework/qb-core#242]
Was this intentional just seems crazy for nearly half of my paid scripts to go out the window when updating ? 

This just one example of a script error and they are all getting the same can i do something to stop this and still have the update ?

@osm-hostage/server/server.lua:49: attempt to index a nil value (global 'QBCore')

**Comment by GhzGarage** [comment]
If they are throwing that error then they are most likely using some super old method of getting the core. Look at client/main.lua and I’ve noted what to put in your script. No I didn’t intentionally break your paid resources lol

**Comment by mobius6666** [comment]
Not saying you did was just wondering if there's a fix ? Sorry if I came off like that I just wanted to know if there was a fix. it had worked on the new core I downloaded about 2 weeks ago. My apologies again

**Comment by GhzGarage** [comment]
Either update your other resources or just use the core from before the major update commit
