### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mallingdk** [qbcore-framework/qb-core#243]
[      script:oxmysql] [ERROR] qb-core was unable to execute a query!
[      script:oxmysql]         Undefined array parameter #1
[      script:oxmysql]         SELECT * FROM bans WHERE license = ? []
[      script:qb-core] SCRIPT ERROR: @qb-core/server/functions.lua:268: attempt to index a nil value (local 'result')

**Comment by Rhydium** [comment]
Please join the [QBCore Discord](https://discord.gg/qbcore) for support.
