### ISSUE TITLE
[SUGGESTION] Replace Blackout Native

### ISSUE THREAD

**Issue by meistroburger** [qbcore-framework/qb-core#244]
**Is your feature request related to a problem? Please describe.**
Currently If you're using "/blackout" or cut the power of city, the vehicle lights will also go off. FiveM created a new native for this: https://docs.fivem.net/natives/?_0xE2B187C0939B3D32 that turns off all the lights but keep the vehicle lights on.

**Difference (Old/New)**

_Current_
SetArtificialLightsState(
	state --[[ boolean ]]
)

_New_
SetArtificialLightsStateAffectsVehicles(
	toggle --[[ boolean ]]
)

**Comment by Eralpozcan** [comment]
[qb-weathersync](https://github.com/qbcore-framework/qb-weathersync/blob/main/client/client.lua )

Please check line:75, 76

**Comment by meistroburger** [comment]
> [qb-weathersync](https://github.com/qbcore-framework/qb-weathersync/blob/main/client/client.lua) We are already using it. Please check line:75, 76

Thankyou <3

**Comment by meistroburger** [comment]
This can be closed
