### ISSUE TITLE
[BUG] qb-blackjack is missing components

### ISSUE THREAD

**Issue by sml4real** [qbcore-framework/qb-core#245]
**Describe the bug**
The blackjack script doesnt seem to be working.. It says that in the left down corner that ''qb-blackjack are missing components or such'' 

**Expected behavior**
I hope some1 knows what the problem can be.. been trying for ages to get this to work! 

**Questions (please complete the following information):**
 - When you last updated: 2 weeks.
 - Are you using custom resource? which ones? Only some maps.
 - Have you renamed `qb-` to something custom? no.

**Comment by Eralpozcan** [comment]
Do the last update. What is your server build version?

**Comment by sml4real** [comment]
> Do the last update. What is your server build version?

That might work yes.. But is there a smart way of saving some work iv done with the scripts? Been manualy making everything swedish and such.. Or is it only to swith out the qb-core folder?

**Comment by Eralpozcan** [comment]
Just update qb-core and qb-blackjack. Of course note that the new qb-core uses oxmysql.

**Before doing this, if your server build version is low, you can upgrade. This may be a simple solution for you.** 2060 or 2182 or 2372

**Comment by MrPandaCoding** [comment]
hey when i launched my server it keeps saying that qb-blackjack is missing an object. just looking for some help on this issue im also running the most recent build for qb-core.
