### ISSUE TITLE
[BUG] Player Last Location doesn't save

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-core#247]
So aparently when ever you log out nothing save's , Such As money / job doesn't save

**Comment by GhzGarage** [comment]
Just made a new character, gave myself $1M, did a /logout to trigger a save, checked database and everything is working how it should

**Comment by GhzGarage** [comment]
![image](https://user-images.githubusercontent.com/57848836/135699386-d55ffbe5-e592-450a-9d41-e7413252056a.png)

**Comment by Kromanic** [comment]
its when they log back in

**Comment by Kromanic** [comment]
Here is a video to show the issue https://youtu.be/Y5veb0DDCyo

**Comment by Kromanic** [comment]
what can i do to fix this ?
