### ISSUE TITLE
[BUG] OOC dosn't work

### ISSUE THREAD

**Issue by Kingsage311** [qbcore-framework/qb-core#251]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'chat'
2. Type '/ooc test'
3. Use this item 'N/A' (item's name from shared.lua if applicable)

**Expected behavior**

I was expecting the "QBCore.Commands.Add('ooc', 'OOC Chat Message" to work as ecpexed and it had before the "QBCore = exports['qb-core']:GetSharedObject()" update i've been useing a version of buzzee's chat that /ooc has worked after a update it throws a error 

**Screenshots**

https://i.imgur.com/xKyyqp8.png

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Fully up to date
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] a version of buzzee's chat
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by Kingsage311** [comment]
will do thank you

**Comment by ArtysXV** [comment]
@Skillgjii From where I can get this newest chat from fivem?

**Comment by Solositeous** [comment]
@ArtysXV You can get the newest version from here https://github.com/citizenfx/cfx-server-data/tree/master/resources/%5Bgameplay%5D/chat. If the issue still happens after that let us know.
