### ISSUE TITLE
[SUGGESTION]：Hope to add features that can change the face and hair color of NPCPeds

### ISSUE THREAD

**Issue by ZZG994521** [qbcore-framework/qb-core#264]
**Is your feature request related to a problem? Please describe.**
I uesing qb-clothing.
And I encountered some troubles when using qb-clothing：
1、I cannot change the face and hair color of NPCPed. When I tried to change their face and hair color, I didn’t see any changes, or it was impossible to change them.
2、When I added an additional Ped module, when I tried to change its face and hair color, a strange phenomenon appeared… Torn head model

**Describe the feature you'd like**
1、I hope that the face and hair color of NPCPeds can be changed normally.
2、I hope that the additional Ped modules can be used normally without the above errors.

**Describe alternatives you've considered**
I have tried to replace qb-clothing with raid_clothes or other clothing scripts, but in fact, they are encoded differently, so that they cannot work correctly.

**Additional context**
1、I am quite sure that most NPCPeds have the function of changing their face and hair color.
2、I am also very sure that the Ped module I added does not have any errors, because I have tested it with other clothing scripts. This bad phenomenon can only occur in qb-clothing.
3、This link is an error that occurred when replacing the face and hair of the ped model added：https://media.discordapp.net/attachments/841605043479773204/894514279716376577/20211003174838_1_2_LI.jpg

**Comment by GhzGarage** [comment]
This belongs on qb-clothing
