### ISSUE TITLE
[BUG]: No notifications after newest update

### ISSUE THREAD

**Issue by CptNoHand** [qbcore-framework/qb-core#266]
**Describe the bug**
I don't get any notfiy's anymore after update

**To Reproduce**
1. Set a job
2. type /job in chat
3. no notification

**Expected behavior**
To get a notification

**Questions (please complete the following information):**
 - When you last updated: just a few minutes ago
 - Are you using custom resource? which ones? a lot, but revert it got me notifications again
 - Have you renamed `qb-` to something custom? no

**Comment by GhzGarage** [comment]
It's fixed now sorry about that
