### ISSUE TITLE
[ script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetchSync in resource oxmysql

### ISSUE THREAD

**Issue by SDeeb23** [qbcore-framework/qb-core#272]
I start the server with qbCore and its dependencies installed, and I try to join and it gives me this error 

[ script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetchSync in resource oxmysql

**Comment by Solositeous** [comment]
@SDeeb23 @T0mSp1ce do you both have oxmysql installed and is it started before you start qbCore?

**Comment by KrelaTv** [comment]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export newPlayer in resource npwd

PLS HELP!

**Comment by SLOsamo** [comment]
[  script:es_extended] SCRIPT ERROR: @oxmysql/lib/MySQL.lua:94: No such export query in resource oxmysql

PLS HELP!!

**Comment by tgtgcuh** [comment]
script:qb-core] SCRIPT ERROR: error object is not a string
[      script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:12: attempt to index a nil value (field 'Players')

**Comment by ScottFmF** [comment]
SCRIPT ERROR: @esx_addoninventory/server/main.lua:9: No such export RegisterStash in resource ox_inventory help is me I don't know what to do anymore I can't solve it

**Comment by poolshark120502** [comment]
![image](https://github.com/qbcore-framework/qb-core/assets/72841575/a091501c-8ec3-4dad-b02e-5fc761360fcd)
