### ISSUE TITLE
HANDCUFFS NOT WORKING AS USABLE ITEM [BUG]

### ISSUE THREAD

**Issue by whiskeythrottle718** [qbcore-framework/qb-core#273]
**Describe the bug**
handcuffs can no longer be used on your hotbar to handcuff a player
 i tried it on a fresh install and it doesnt work

having the handcuffs be able to be used in the hotbar was one of the best features of the policejob by far

**Comment by alp1x** [comment]
> **Describe the bug** handcuffs can no longer be used on your hotbar to handcuff a player i tried it on a fresh install and it doesnt work
> 
> having the handcuffs be able to be used in the hotbar was one of the best features of the policejob by far

https://github.com/qbcore-framework/qb-policejob/pull/134#discussion_r729736559
