### ISSUE TITLE
Error with the job

### ISSUE THREAD

**Issue by 7R3C3** [qbcore-framework/qb-core#290]
cfx> [ script:qb-policejob] SCRIPT ERROR: @qb-policejob/server/main.lua:17: attempt to call a nil value (field 'GetQBPlayers')
[ script:qb-policejob] > fn (@qb-policejob/server/main.lua:1059)

Getting this error, just put the script in and started it

**Comment by GhzGarage** [comment]
discord.gg/qbcore
