### ISSUE TITLE
[BUG] Can't see each other

### ISSUE THREAD

**Issue by Wiggie-Scripts** [qbcore-framework/qb-core#292]
People can't see each other

**Comment by Rival819** [comment]
It's also not artifact problem I cant say this. Also qb-shops if you had too many shops in there then the NPC in cars starts going ghost mode. Something is wrong with the last qb-core after a number of resources. (Passed 330 resources) qbcore starts acting up. We are having the same problem right now, had to delete some shops from qb-shops to get my peds back in cars showing up......

But after 30 players on the server if we make and event then most people wont see others....some do....some dont....it's annoying has hell and always comes back on the fault of the Dev.....annoying has hell.
