### ISSUE TITLE
[SUGGESTION] we need a chat script plz

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-core#303]
[SUGGESTION] we need a chat script plz

**Comment by evanillaa** [comment]
chat Already exists

**Comment by OxGhali** [comment]
i mean a developed one

**Comment by BerkieBb** [comment]
https://github.com/citizenfx/cfx-server-data/tree/master/resources/%5Bgameplay%5D/chat
Here, a developed chat
