### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by caccoi** [qbcore-framework/qb-core#308]
![Screenshot 2021-11-03 222726](https://user-images.githubusercontent.com/92968509/140247528-925fe8a9-aeac-439b-b4a1-76d0da68d4c7.png)

Show this error when type /logout or using log out feature in apartment

**Comment by zfbx** [comment]
Where's the rest of the issue template?... with the questions on if you're using the latest qbcore and other important helpful information?...

**Comment by caccoi** [comment]
> Where's the rest of the issue template?... with the questions on if you're using the latest qbcore and other important helpful information?...

Only that error showing up.

**Comment by JericoFX** [comment]
Use the template and fill all the infomation or the issue will be closed
