### ISSUE TITLE
Question about evidence in Policejob.

### ISSUE THREAD

**Issue by cristianoccc** [qbcore-framework/qb-core#310]
I was looking around and checking out how the evidence script was working, untill I hit a roadblock. I successfully got the bulletcasings, and the gun's serial number, but what do I do now? Is there any way I can check who is the owner of the gun? or any way to link the person to the serial number? Thanks in advance.

**Comment by jnccloud** [comment]
At this point in time, on my server, we use it to compare casings at the scene vs suspects apprehended and the firearms they are carrying. It encourages more RP, but there are times I wish I could just go to the crime lab and run a background check on the serial. Maybe this could be more of a court/DOJ function in the future.

**Comment by Mojito-Fivem** [comment]
@cristianoccc the serial number is randomly generated when a gun enters circulation, there's no way to track this back to the original owner unless we put some hidden metadata inside of the item with it. I think the idea of it is just to cross-reference the bullet casing and location with the gun.
