### ISSUE TITLE
[BUG] All My server players Getting This after this last update

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-core#318]
![unknown](https://user-images.githubusercontent.com/71113131/141182010-919abbcd-a225-444a-863b-424cce9916cb.png)

**Comment by GhzGarage** [comment]
Getting what?

**Comment by OxGhali** [comment]
this colors .. and sorry not all of them but a lot of them havinn this colors and i think the issue is on weathersync cuz when i changed the weather This problem did not appear

**Comment by xenfovn** [comment]
CHECK YOUR MOD OR OTHER SCRIPT

**Comment by jnccloud** [comment]
They are probably using a graphics mod. It has to do with some of the fog and snow options in the northern side of the map. To stop this problem in general on my server I made these changes in qb-weathersync/config.lua to prevent the weather from automatically changing to these:

```lua
Config.AvailableWeatherTypes = { -- DON'T TOUCH EXCEPT IF YOU KNOW WHAT YOU ARE DOING
    'EXTRASUNNY',
    'CLEAR',
    -- 'NEUTRAL',
    -- 'SMOG',
    -- 'FOGGY',
    -- 'OVERCAST',
    'CLOUDS',
    -- 'CLEARING',
    'RAIN',
    'THUNDER',
    'SNOW',
    -- 'BLIZZARD',
    'SNOWLIGHT',
    'XMAS',
    'HALLOWEEN',
}
```

**Comment by evanillaa** [comment]
go to the discord
