### ISSUE TITLE
[BUG] An issue with /me command. When you enter the command the chat suggestion is stuck. It does not fade out

### ISSUE THREAD

**Issue by arogyamagar** [qbcore-framework/qb-core#321]
An issue with /me command. When you enter the command the chat suggestion is stuck. It does not fade out

**Comment by Zael98** [comment]
think i find the solution, some commands are bad writed the help of the command, for example: the command me (default command of qb-core) QBCore.Commands.Add('me', 'Show local message', {{ name = 'id', help = 'Player ID' } }, false, function(source, args)  and i change it to: 
QBCore.Commands.Add('me', 'Show local message', {}, false, function(source, args)
after this dont happen more, is probably happen with more commands so i will change all the commands who give the problem.
for the moment for me is fixed after change 4 commands. if someone have the problem probably this will be the solution.
Test it and give me feedback about the solution. This work for me.

**Comment by nggcasey** [comment]
Confirmed issue and solution by @Zael98 

qb-core > server > commands.lua

Is a syntax error...replace this

`QBCore.Commands.Add('me', 'Show local message', {name = 'message', help = 'Message to respond with'}, false, function(source, args)`

with this

`QBCore.Commands.Add('me', 'Show local message', { {name = 'message', help = 'Message to respond with'} }, false, function(source, args)`
