### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zviux** [qbcore-framework/qb-core#322]
![image](https://user-images.githubusercontent.com/92739528/141327685-0dd3b10d-9fbe-4e5d-b507-07fa6d64f1c8.png)
I need help, my server is not working. I have reset the server for the 7th time and it doesn't work. I am using the qbus txadmin recipe. It works for first, but when I restart the server it stops working, I spawn as the default skin somewhere on the map.

**Comment by JericoFX** [comment]
You need to use the template fisrt, you don't bring any Information, screenshots, console, etc etc

**Comment by Zviux** [comment]
I did it several times

**Comment by JericoFX** [comment]
so there is no reason to not doing it, you need to follow the template, with that information is impossible to track any error

**Comment by roobr** [comment]
Please provide some more information, if you can put specific errors and detailed bugs we might be able to help you.
If not you might find better help in the qbcore discord

**Comment by GhzGarage** [comment]
discord.gg/qbcore
