### ISSUE TITLE
[BUG] Paycheck seems scuffed

### ISSUE THREAD

**Issue by Hazzer278** [qbcore-framework/qb-core#326]
Sometimes you get a paycheck and sometimes you won't get a paycheck and then sometimes its delayed as hell

To reproduce I started up my server and loaded in managed to grab 2 successfull paychecks 1 after the other
then I F8 quit , Upon reloading into the server I then couldn't get a paycheck at all in the 20-30 mins I was in for

Then if I restart the server and load back in I can grab a paycheck / the sequence above starts again

Updated yesterday/today along with other QBCore updates  to keep up 

If this is a me thing and can't be reproduced by anyone let me know and I'll see if I've forgot something 

Thankyou to whomever fixes this ahaha<3

**Comment by GhzGarage** [comment]
Are you on duty

**Comment by Hazzer278** [comment]
Yeah was on duty both times loading in

**Comment by Neaw92** [comment]
I am having the same issue. My officers on my server have been saying the same thing, they only sometimes get paid. I have noticed it happening as well.

**Comment by jnccloud** [comment]
> Are you on duty

I've had the same issues, this is the server error that happens whenever the payroll stops working until restart of qb-core:

`[script:qb-core] SCRIPT ERROR: @qb-core/server/functions.lua:116: attempt to index a nil value (local 'Player')`

Could this be because someone has dropped from the server and the Player table hasn't removed them before processing?

**Comment by xenfovn** [comment]
I am having the same issue

**Comment by jnccloud** [comment]
This paycheckloop function works for me, it's from https://github.com/qbcore-framework/qb-core/commit/3d47bd8589acb6873e32ef13f25d6106d0433657 -- you can just replace the function in `server/functions.lua` until this is patched

```lua
function PaycheckLoop()
    local Players = QBCore.Functions.GetPlayers()
    for i = 1, #Players, 1 do
        local Player = QBCore.Functions.GetPlayer(Players[i])
        if Player.PlayerData.job and Player.PlayerData.job.onduty and Player.PlayerData.job.payment > 0 then
            Player.Functions.AddMoney('bank', Player.PlayerData.job.payment)
            TriggerClientEvent('QBCore:Notify', Players[i], 'You received your paycheck of $' .. Player.PlayerData.job.payment)
        end
    end
    SetTimeout(QBCore.Config.Money.PayCheckTimeOut * (60 * 1000), PaycheckLoop)
end
```

**Comment by lexicon-necropsy** [comment]
I noticed that paychecks aren't being paid for whitelisted jobs, too. It works on server restarts once, maybe twice and then it stops working.

**Comment by JesusShaves** [comment]
I'm having the same issue as well. I will test the function @jnccloud posted and report back.

**Comment by GhzGarage** [comment]
Should be fixed

**Comment by Hazzer278** [comment]
Can verify on this one that with the new paycheck loop that is in the current QBCore works fine with 0 problems

**Comment by MaDHouSe79** [comment]
i disable the PaycheckLoop function, and i rebuild the paycheck system so you only get pay if you have more then 10min onduty, and if you go offduty after 10 min than you get a message in your phone that you get a paycheck and can pick it up by the bank, works just fine, no timers no lag, noting. :)

**Comment by Xdelic** [comment]
> 

Do you have an example of how you built this? this would help me out greatly as im new to coding and trying to figure this out for my city im helping a buddy build.

**Comment by koolaash** [comment]
did anyone find any solution for this issue i am facing same issue in my server as well along with policejob blips
