### ISSUE TITLE
[BUG] Slot ID Order Usage Item

### ISSUE THREAD

**Issue by renzuzu** [qbcore-framework/qb-core#330]
**Describe the bug**

item meta info ordering bug:
when using item it give incorrect meta info
if use order is Slot id 2 to Slot id 1

**To Reproduce**

`Slot 1`
local item 'vehicle_shell'
local amount = 1
local slot nil
local info = 'blista'

`Slot 2`
local item 'vehicle_shell'
local amount = 1
local slot nil
local info = 'tempesta'
```
code:

setter:

Functions.AddItem(item,amount,slot or false,info)

getter:

QBCore.Functions.CreateUseableItem(source,data)
print(data.info)
```

**Expected behavior**
return unique meta info for both items (triggered from code above)
**Screenshots**
Video of bug Use Order Slot 2 to Slot 1 : 
https://streamable.com/4hum93

Video of No Bug Order Usage Slot 1 to Slot 2
https://streamable.com/wvxb82

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 tried using latest qb-core and qb-inventory, same result
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 no
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 no

**Additional context**
im not sure if this is the right category, this could be a qb-inventory bug itself. (hot key slots)
as other slots working fine (non hot keys)
if i move all items to >=6 slots it will work on any order.

**Comment by Mojito-Fivem** [comment]
I can't reproduce this.

```js
const QBCore = global.exports['qb-core'].GetCoreObject()

setImmediate(() => {
    const Player = QBCore.Functions.GetPlayer(1)

    const item1 = 'grapejuice'
    const info1 = {
        uniqueData: '12323123'
    }

    Player.Functions.AddItem(item1, 1, 1, info1)

    const item2 = 'grapejuice'
    const info2 = {
        uniqueData: '707005040'
    }

    Player.Functions.AddItem(item2, 1, 2, info2)
})
```
I'm running this code from runcode and I get both items.

In qb-inventory I've added debug to [client/main.lua:651](https://github.com/qbcore-framework/qb-inventory/blob/5b99483d72a242d30dab868e83b358467654f2b5/client/main.lua#L651)
```lua
RegisterNUICallback("UseItem", function(data, cb)
    QBCore.Debug(data)  -- Added Debug
    TriggerServerEvent("inventory:server:UseItem", data.inventory, data.item)
end)
```

And this is the resulting debug print:

![Debug Output](https://i.imgur.com/3tGcswk.png)

This is exactly as expected, slot 2 comes first and contains the correct unique data followed by slot 1 also with the correct data.

**Comment by Mojito-Fivem** [comment]
The same output is obtained when using hotkeys and adding Debug [here](https://github.com/qbcore-framework/qb-inventory/blob/5b99483d72a242d30dab868e83b358467654f2b5/server/main.lua#L830)

**Comment by Mojito-Fivem** [comment]
The same also occurs when using an item with the `unique` trait and leaving the slot to be `null`

**Comment by renzuzu** [comment]
I will try to debug this again, and give more valuable info.

The only thing i notice is when using a slot 2 first before slot 1, after using the slot 2 the item from slot 1 will be moved to slot 2..as you can see in the video.

If thats not normal thats maybe the case that might be the one causing the data dupe..atleast how i called it.

But i will still debug it to make sure, this could be only in my end.

**Comment by Mojito-Fivem** [comment]
@renzuzu from my screenshot above that's exactly what I did, run the same code I did and see if you can do that same. If you can provide an actual snippet of code that you can reliably reproduce this from do send.

**Comment by renzuzu** [comment]
i havent reproduce anything again, this could be a related to some fxserver version.
i remember fixing some table,var duping in the past, using 4680 now..

inside the event or function
its like a 
```
local test = sometable
--needed to be
test = {}
--or 
test = nil
--in the end of event
```
so the next request are not cached or duped. (specially if its json array)

maybe thats why its unproducible ,

from 
https://github.com/renzuzu/renzu_projectcars

the snippet is simple

```
              RegisterUsableItem(name, function(source,item,data)
                    local item = item
                    local source = source
                    local xPlayer = GetPlayerFromId(source)
                    local meta = ItemMeta(name,item,xPlayer,data)
                    local ply = Player(source).state
                    if Config.EnableZoneOnly and ply.buildzone or not Config.EnableZoneOnly or GlobalState.GarageInside[xPlayer.identifier] then
                        TriggerClientEvent('renzu_projectcars:spawnnewproject',source,meta)
                        xPlayer.removeInventoryItem(name, 1)
                    else
                        TriggerClientEvent('renzu_notify:Notify', source, 'error','ProjectCars', Locale[Config.Locale].not_inzone)
                    end
                end)
```

ItemMeta Function
```
function ItemMeta(name,data,xPlayer,ox)
	local xPlayer <const> = xPlayer
	local name <const> = name
	if Config.framework == 'ESX' then
		local Inventory = exports.ox_inventory:Inventory()
		local item = Inventory.Search(xPlayer.source, 1, name)
		local source = tonumber(xPlayer.source)
		local meta = nil
		local slot = nil
		if ox and ox.slot then
			-- thanks to linden
			-- new ox updated latest https://github.com/overextended/ox_inventory/commit/a7028a23cc890a3ad357fe0d3784d81d0b2d078d and https://github.com/overextended/es_extended/commit/d7f5b969a83421825bfd82a972dc5ada9898f2f5
			meta = ox.metadata.type
		else
			-- old ox logic
			if not Using[source] then
				Using[source] = {}
			end
			while not Using[source][name] do Wait(100) end
			slot = Using[source][name]
			for k2,v in pairs(item) do
				if v.slot == slot then
					meta = v.metadata.type
				end
			end
		end
		return meta
	else
		local data <const> = data
		return data.info
	end
end
```
feel free to close if problem is not from qb.
i just cant believe im still using this fx ver :D

**Comment by Mojito-Fivem** [comment]
Could you post actual QBCore code like a simple command and not a snippet from your own project which I only see ESX code in
