### ISSUE TITLE
[BUG] I update the qb-core and players cant join appear coulnt not load resource 

### ISSUE THREAD

**Issue by Ranger194** [qbcore-framework/qb-core#332]
I update the QB-Core and now the players when try to join appear a message "coulnt not  load qb-skillbar,  policejob, multicharacter etc etc etc,

**Comment by VyrusDev** [comment]
Currently Having the same issue did anyone find a fix?

**Comment by Giana** [comment]
This issue is still present for me even after this update from which this was marked done.

**Comment by GhzGarage** [comment]
Got a picture?

**Comment by Giana** [comment]
Sure thing. If I go back to an older version of qb-core I was using in the server, I can connect without this issue. Otherwise the previous version and the newest version from a couple hours ago give me this specific qb-skillbar error.

https://i.ibb.co/P6jn6Y3/skillbar.png
