### ISSUE TITLE
[BUG] When i add a car in the shared.lua some cars they go automatically to some players in their garages

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-core#337]
[BUG] When i add a car in the shared.lua some cars they go automatically to some players in their garages

**Comment by Mojito-Fivem** [comment]
Repro? There's no way this behaviour happens without a wonky garage script

**Comment by OxGhali** [comment]
no i didn't edit the script is the same from this qbcoreframework with the last update

**Comment by Mojito-Fivem** [comment]
ok but do you have a way to actually reproduce this or is this just heresay

**Comment by JericoFX** [comment]
How is this even possible? you need a script that send a car to the player's garage

**Comment by OxGhali** [comment]
i don't know why it's happening look when i add a car or two in the shared then i go to sell them in luxury cars shop so those cars i sold
they go to the players who i sell it to them and they go automaticly to players they are not even in the luxury car shop
