### ISSUE TITLE
[SUGGESTION] PVP (Enabled/Disabled) Option

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/qb-core#345]
**Is your feature request related to a problem? Please describe.**
Kind of, I don't like being shot in the face randomly, and I'm sure I'm not alone here.

**Describe the feature you'd like**
Nice and simple. Some servers like to have it as a PVE to where you just chill, enjoy the systems in place and do your own thing without having the fear of being randomly shot in the face at any moment.

**Describe alternatives you've considered**
Unless you want to put a bunch of other systems in place and rules that are just downright ridiculous to curb this without having an actual PVE option, would be just nice to be able to toggle it.

**Additional context**
Thank you for your consideration.

**Comment by Mitroxs** [comment]
So disable server wide PVP or a option for each player?

**Comment by Duguayster** [comment]
Server wide, making a PVE server while enjoying the QBCore platform.

Just a toggleable option in the config would be cool.

I found the friendly fire code in the client/events.lua and got pvp turned off. Just thought be a nice feature to have.

**Comment by Mitroxs** [comment]
> Server wide, making a PVE server while enjoying the QBCore platform.
> 
> Just a toggleable option in the config would be cool.
> 
> I found the friendly fire code in the client/events.lua and got pvp turned off. Just thought be a nice feature to have.
#352

**Comment by Mitroxs** [comment]
@GhzGarage Someone close this as my last PR was related to this issue

**Comment by JajarGaming** [comment]
> **Is your feature request related to a problem? Please describe.** Kind of, I don't like being shot in the face randomly, and I'm sure I'm not alone here.
> 
> **Describe the feature you'd like** Nice and simple. Some servers like to have it as a PVE to where you just chill, enjoy the systems in place and do your own thing without having the fear of being randomly shot in the face at any moment.
> 
> **Describe alternatives you've considered** Unless you want to put a bunch of other systems in place and rules that are just downright ridiculous to curb this without having an actual PVE option, would be just nice to be able to toggle it.
> 
> **Additional context** Thank you for your consideration.

Close this "Issue"
