### ISSUE TITLE
[BUG] QB-SharedVehicles now has no vehicle models section, and addon cars do not load into vehicle shop

### ISSUE THREAD

**Issue by KennyBowers** [qbcore-framework/qb-core#348]
Since i updated my QB-Core, the vehicle models table has disappeared, and since then the vehicle shop wouldnt load addon vehicles, it recognises the add on catagories, but not the vehicles.

Hopefully im just having a dumb moment and someone can point out what ive missed

**Comment by Mojito-Fivem** [comment]
The vehicle models table was removed a long time ago, you must be using an old vehicleshop

**Comment by KennyBowers** [comment]
I reset the server to update it all, but that didn't work either

**Comment by NugiTv** [comment]
I'm having this issue right now.

**Comment by KennyBowers** [comment]
Anyone found a fix for this? or whats causing it?

**Comment by GameMango36** [comment]
Unable to reproduce so no fix.

**Comment by PhoenixYeti** [comment]
im having this problem to, im not using the base dealership however and im able to sell people the cars from this dealership however when they are stored in the garages they disapea
![Desktop_Screenshot_2021 12 12_-_14 21 10 29](https://user-images.githubusercontent.com/96113486/145973297-97cdabb6-dfe5-4e6c-ab1b-051714d7f58a.png)
r
