### ISSUE TITLE
BUG: sql file doesnt create the playeritems table

### ISSUE THREAD

**Issue by mooseh** [qbcore-framework/qb-core#35]
when loading into my server I get the following message 
```[qb-core] An error happens for query "SELECT * FROM `playeritems` WHERE `citizenid` = '****' : []": ER_NO_SUCH_TABLE: Table 'mooseh_fivem.playeritems' doesn't exist``

```
I checked the SQL file and it doesn't create the playeritems table, making for a bad install from the get go.

**Comment by mooseh** [comment]
found a fix in KASH4's Repo
```
CREATE TABLE `playeritems` (
  `id` int(11) NOT NULL,
  `citizenid` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `amount` int(11) NOT NULL,
  `info` text DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  `slot` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by GhzGarage** [comment]
That table already exists...

https://github.com/qbcore-framework/qb-inventory/blob/main/qb-inventory.sql
