### ISSUE TITLE
[BUG] Vanish 

### ISSUE THREAD

**Issue by killzone185** [qbcore-framework/qb-core#353]
**Vanish Cars**
While players are in the server there are certain vehicles with npc driving. A player can jump on top of the cars and they disappear. This happens more then often.

**To Reproduce**
Jump on a car and boom gone

**Expected behavior**
Nothing 

**Screenshots**

**Questions (please complete the following information):**
 - 11/29/2021
 - No
 - No

**Additional context**
nothing

**Comment by Mojito-Fivem** [comment]
Can't reproduce

**Comment by killzone185** [comment]
It happens all the time time. It's not on all npc it's on some

**Comment by Mojito-Fivem** [comment]
I'm on latest artifact (5049) as of writing, canary client, onesync infinity and latest qb-core build and I can't reproduce this at all. I'm fairly certain what you're describing isn't a bug with qb-core but with your resources
