### ISSUE TITLE
[SUGGESTION] example variables without calls 

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-core#364]
**Is your feature request related to a problem? Please describe.**

Why can't we use for example variables without calls for example

```
local Player = QBCore.Functions.GetPlayerData()
if Player.job.name == "taxi" then
```
I saw many projects that I can choose for example
isPolice
isDead
isTaxi
isDuty
without calling
if isPolice  and isDuty then

**Comment by Mojito-Fivem** [comment]
You can make a simple wrapper for this yourself, this appears to be just ripped from nopixel code iirc so I don't see why such a feature needs to exist in qb-core

**Comment by darknight2590** [comment]
Can a simple explanation of how this works? I wish more clarification and help?
@darknight2590

**Comment by Mojito-Fivem** [comment]
Umm, no. I'm not gonna tell you on a github issue how to steal NoPixel code

**Comment by darknight2590** [comment]
You are talking in another area
My question is not related to the topic you are talking about

**Comment by darknight2590** [comment]
https://github.com/Crishe93/policeblip/blob/f6fa3a2939cd714018e583a39e91baea5423d2e9/client.lua
https://github.com/gabrielhz/nitropoint/blob/5a4b19aa68b45a84013deedee94e3063732f17ec/nitro-data/resources/%5Bvrp%5D/vrp_control_people/client.lua
