### ISSUE TITLE
[BUG] Interior Furniture vanishes and reappears.

### ISSUE THREAD

**Issue by DynOBear** [qbcore-framework/qb-core#368]
**Describe the bug**
When inside of an interior, furniture placed below my characters waste vanish and reappear as I move my third person camera. Certain x y z coordinates are below of where its happening. My thought is that you can move the interior up and fix it but I don't know what that would do to everything else like furniture or other players housing.

**To Reproduce**
1. Go to '(X: -1126.36) (Y: 382.59) (Z: 50 to 40)'
2. Crate the Franklins house interior
3. Place items that are below the waist of the character that are located on the floor on the black surface of the main story.
4. Items glitch and appear and disappear while moving you third person cameras around.

**Screenshots**

**Questions (please complete the following information):**
-Will the interior furniture move with the interior or stay planed when the interior is moved up or down.
-What other things may be affected by fixing this issue

**Additional context**
I am not the server owner or a Dev, I am simply a player who is trying to find a solution to the issue. Excuse my possible ignorance on the topic i am doing as much research as I can to solve the issue.

![VanishingFurniture1](https://user-images.githubusercontent.com/95674749/145151354-34bb2603-508e-44a7-8c26-139cc7d97323.jpg)

![VanishingFurniture2](https://user-images.githubusercontent.com/95674749/145151357-cd59b594-90a2-4506-b715-878a6db549e9.jpg)

**Comment by Mojito-Fivem** [comment]
This is the qb-core repository

**Comment by DynOBear** [comment]
> This is the qb-core repository

I’m sorry I have no clue what that is… could you elaborate? Is this fixable?

**Comment by Mojito-Fivem** [comment]
> > This is the qb-core repository
> 
> I’m sorry I have no clue what that is… could you elaborate? Is this fixable?

You're currently posting an issue in the repository for qb-core, when your issue seems to be with qb-housing. You're more likely to get help with your problem if you post it in the correct repository
