### ISSUE TITLE
Deactivate other players points

### ISSUE THREAD

**Issue by JDittmerCOM** [qbcore-framework/qb-core#370]
Is it possible to deactivate the player points somewhere?

Because in RP you don't have to know where the other players are on the map. 

![FiveM_GTAProcess_95JuU4EWVq](https://user-images.githubusercontent.com/11929467/145402669-ae7e5137-1929-449c-9a69-6a4e5fcaca1b.png)

**Comment by BlueSky-fur** [comment]
thats a blip of a medic. and youre a cop most likely.

**Comment by JDittmerCOM** [comment]
All right, thanks for answer.

Meanwhile I was able to remove the points on the map :)
