### ISSUE TITLE
[Micro-optimization] Localize PlayerId()

### ISSUE THREAD

**Issue by AvarianKnight** [qbcore-framework/qb-core#373]
Very minor optimization, but PlayerId() only needs to be called once, instead of being called for each nearby player

https://github.com/qbcore-framework/qb-core/blob/f41e23b69a604d0d4ad35dfff7c59b44611d6f7e/client/functions.lua#L188-L198

**Comment by LifeGoal** [comment]
You should make a pull request for this if you want it implemented! :)
