### ISSUE TITLE
[BUG] Problem with ?

### ISSUE THREAD

**Issue by tvasa** [qbcore-framework/qb-core#376]
**Describe the bug**
Hello, i am using your Qb framework And have problems with apartmens,phone,blips.
When i join on server, so one time everything okey. Next time after server restart or resourse ensure. The blips,phone,apartmens doesnt show and dont work. 

Approximately three restars Is everything okey.

Where can be problem ? Thanks for you time
Best regards.

**Comment by Mojito-Fivem** [comment]
This description is not helpful and this is not the repository for blips, phone nor apartments

**Comment by MAMBA7777** [comment]
I can't enter a local citizen's vehicle, when I click "f" to loot their vehicle citizen-run with their vehicle. How can I solve that
