### ISSUE TITLE
[BUG] Shared Editing

### ISSUE THREAD

**Issue by TheInvinsible77** [qbcore-framework/qb-core#379]
So I went into the shared.lua to start creating new items and job grades. I created some new grades for police here is the list:
	['police'] = {
		label = 'Law Enforcement',
		defaultDuty = true,
		grades = {
            ['0'] = {
                name = 'Recruit',
                payment = 50
            },
			['1'] = {
                name = 'Trooper',
                payment = 75
            },
			['2'] = {
                name = 'Trooper First Class',
                payment = 100
            },
			['3'] = {
                name = 'Master Trooper',
                payment = 125
            },
			['4'] = {
                name = 'Corporal',
                payment = 150
            },
			['5'] = {
				name = 'Master Corporal',
				payment = 175
			},
			['6'] = {
				name = 'Sergeant',
				payment = 200
			},
			['7'] = {
				name = 'Master Sergeant',
				payment = 225
			},
			['8'] = {
				name = 'Lieutenant',
				payment = 250
			},
			['9'] = {
				name = 'Captain',
				payment = 275
			},
			['10'] = {
				name = 'Major',
				payment = 300
			},
			['11'] = {
				name = 'Lt. Colonel',
				isboss = true
				payment = 325
			},
			['12'] = {
				name = 'Colonel',
				isboss = true
				payment = 350
			},
        },
},

Once I created them i loaded into the server and went to chose my character like usual. Once I chose the character I wanted I was stuck loading and the location choices didnt come up (menu that lets you choose last location.) insted I was stuck in a black screen so I looked in my server console and saw thses errors
[script:qb-multichara] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:141: SCRIPT ERROR: @qb-core/server/player.lua:117: attempt to index a nil value (field 'Shared')
[script:qb-multichara] > CheckPlayerData (@qb-core/server/player.lua:117)
[script:qb-multichara] > ref (@qb-core/server/player.lua:25)
[script:qb-multichara] > safeCallback (@oxmysql/oxmysql.js:19903)
[script:qb-multichara] > <unknown> (@oxmysql/oxmysql.js:19923)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:qb-multichara] 
[script:qb-multichara] (nil stack trace)SCRIPT ERROR: @qb-core/server/events.lua:16: attempt to index a nil value (field 'Shared')
[      script:qb-core] > handler (@qb-core/server/events.lua:16)
[      script:qb-core] > routeMessage (@chat/sv_chat.lua:187)
[      script:qb-core] > handler (@chat/sv_chat.lua:218)

I tried to go through and look at the lines but I didnt wanna make anything worse so I stopped myself from tinkering before I had to reset the server again. Anyway I've had this with other scripts as well where I change a file and then its not regocnized anymore like lua stops reazing it. And the same thing happened before when I tried to add an Item to the shared.lua. I realized I couldnt fix it and changed everything back but I got the same errors. I tried to just erase what I wrote and rewrite the origional. I still got the errors though and the only way I found to fix it was to grab a fresh file off github. How can I fix this so I can add Items and jobs? I would really appreciate the help.

**Comment by TheInvinsible77** [comment]
it doesnt show in here but spacing was all correct in notepad++ it had the space at the beginning of each line.

**Comment by TheInvinsible77** [comment]
Little Update: So I am still having issues with the item adding but I managed to find a temp fix kinda for the job grades. apparently the line isboss = true was causing issues but not I need to figure out how to get that in aswell without breaking it again can you help with that?

**Comment by mschiegg** [comment]
@TheInvinsible77  You forgot the comma after isboss = true

This
```
['12'] = {
name = 'Colonel',
isboss = true
payment = 350
},
```
should be
```
['12'] = {
name = 'Colonel',
isboss = true,
payment = 350
},
```
and so on

**Comment by TheInvinsible77** [comment]
> 

thank you so much I knew I was forgetting something stupid like that

**Comment by LifeGoal** [comment]
> thank you so much I knew I was forgetting something stupid like that

Close the issue
