### ISSUE TITLE
[BUG] QBCore.Functions.HasItem

### ISSUE THREAD

**Issue by LifeGoal** [qbcore-framework/qb-core#380]
**Describe the bug**
When trying to use QBCore.Functions.HasItem, it doesn't work. If it returns anything, it just returns false even tho you have the item on you.

**To Reproduce**
1. Use QBCore.Functions.HasItem in any resource
2. Use print(QBCore.Functions.HasItem("weapon_knife") or whatever
3. See for yourself

**Expected behavior**
It should return the right values instead of just false or nothing at all.

**Questions (please complete the following information):**
 - When you last updated: Using the latest version of QB-Core
 - Are you using custom resource? which ones? Does this really matter for this issue?...
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Comment by Nyxonn** [comment]
Got the same problem

**Comment by Nyxonn** [comment]
It always returns false value, no matter if i have this item or not

**Comment by Mojito-Fivem** [comment]
Can't Reproduce
```lua
local QBCore = exports['qb-core']:GetCoreObject()
return QBCore.Functions.HasItem("phone")
```

returns true

**Comment by LifeGoal** [comment]
@Mojito-Fivem if you are trying to check for multiple items in one single function, like this:
```lua
local phone = QBCore.Functions.HasItem("phone")
local phone2 = QBCore.Functions.HasItem("phone2") -- Cuts the whole function here
local phone3 = QBCore.Functions.HasItem("phone3")
```

What I did to solve this myself with some spaghetti code is that I added Citizen.Wait(0) between every `QBCore.Functions.HasItem(item)` which made it work for some reason.

So like this: 
```lua
local phone = QBCore.Functions.HasItem("phone")
Citizen.Wait(0)
local phone2 = QBCore.Functions.HasItem("phone2") -- Doesn't cut anymore
Citizen.Wait(0)
local phone3 = QBCore.Functions.HasItem("phone3") -- This one also works
```

Not 100% sure how promises etc works, as I've not played with them yet. But I guess that is the cause and that you have to (for some reason) add those Waits to make it work. At least it did for me, so I guess that it would for everyone else too!

**Comment by evanillaa** [comment]
Can be used amount with this functios ?
```
local QBCore = exports['qb-core']:GetCoreObject()
return QBCore.Functions.HasItem("phone", 1)
```

**Comment by Mojito-Fivem** [comment]
> @Mojito-Fivem if you are trying to check for multiple items in one single function, like this:
> 
> ```lua
> local phone = QBCore.Functions.HasItem("phone")
> local phone2 = QBCore.Functions.HasItem("phone2") -- Cuts the whole function here
> local phone3 = QBCore.Functions.HasItem("phone3")
> ```
> 
> What I did to solve this myself with some spaghetti code is that I added Citizen.Wait(0) between every `QBCore.Functions.HasItem(item)` which made it work for some reason.
> 
> So like this:
> 
> ```lua
> local phone = QBCore.Functions.HasItem("phone")
> Citizen.Wait(0)
> local phone2 = QBCore.Functions.HasItem("phone2") -- Doesn't cut anymore
> Citizen.Wait(0)
> local phone3 = QBCore.Functions.HasItem("phone3") -- This one also works
> ```
> 
> Not 100% sure how promises etc works, as I've not played with them yet. But I guess that is the cause and that you have to (for some reason) add those Waits to make it work. At least it did for me, so I guess that it would for everyone else too!

This might be some janky scheduling at scrt level

**Comment by Mojito-Fivem** [comment]
> Can be used amount with this functios ?
> 
> ```
> local QBCore = exports['qb-core']:GetCoreObject()
> return QBCore.Functions.HasItem("phone", 1)
> ```

No, it's not the purpose of this function to do that

**Comment by evanillaa** [comment]
Do you think this is true?

```
function QBCore.Functions.HasItem(item, amount)
    local p = promise.new()
    QBCore.Functions.TriggerCallback('QBCore:HasItem', function(result)
        if result then
            p:resolve(true)
        end
        p:resolve(false)
    end, item, amount)

    return Citizen.Await(p)
end
```
