### ISSUE TITLE
[BUG] attempt to index a nil value Player_Buckets

### ISSUE THREAD

**Issue by RadhwaneDZ** [qbcore-framework/qb-core#387]
**Describe the bug**
SCRIPT ERROR: @qb-core/server/events.lua:8: attempt to index a nil value (field 'Player_Buckets')

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] latest
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] yes
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by BerkieBb** [comment]
It should have been fixed already
