### ISSUE TITLE
[BUG] Multicharacter

### ISSUE THREAD

**Issue by LuquinhasVulgoRC** [qbcore-framework/qb-core#388]
Hi, I wanted to report a bug, I don't know if it only happens to me, but whenever I use the build tuner, there is no option to select the character
![image_2021-12-20_104842](https://user-images.githubusercontent.com/82515416/146777143-4487e515-d201-4305-b9d6-ba8422d4c148.png)

**Comment by lordfalcon22** [comment]
I have noticed this as well. Is it only happening on build tuner?

**Comment by LuquinhasVulgoRC** [comment]
> I have noticed this as well. Is it only happening on build tuner?

I haven't tried it in other builds, but in tuner it happens.

**Comment by LifeGoal** [comment]
You should make an issue in the repository for whatever resource you are having problems with, as this is the Core and not the resource that you have problems with.

**Comment by BlueSky-fur** [comment]
we are on the most recent available build, with no issues whatsoever.

**Comment by Mojito-Fivem** [comment]
I used to have this issue myself, it would happen about 40% of the time. My friend also gets this quite often. I fixed this buy upgrading my CPU

**Comment by zyn4t** [comment]
> I used to have this issue myself, it would happen about 40% of the time. My friend also gets this quite often. I fixed this buy upgrading my CPU from an i5-4460 to a Ryzen 5600X, my friend that gets this also has a bad PC so I'm 100% confident this is a hardware issue

What troubleshooting have you done? I have an old CPU (3570K) and I only recently started to get this issue on 1 small server. No issues on large populated servers.

If we restart qb-multicharacter while im at OPs screen, the char select menu will open. But in return this gives everyone else the same issue when they join (incl people on high end PCs)

**Comment by Mojito-Fivem** [comment]
> What troubleshooting have you done? 

With old CPU i get this problem maybe 50% of the time, with new CPU I get this problem 0% of the time. Only variable is the hardware

**Comment by zyn4t** [comment]
> With old CPU i get this problem maybe 50% of the time, with new CPU I get this problem 0% of the time. Only variable is the hardware

Ah we having different experiences. This happens to me 99% of the time, but doesn't happen to someone with an older CPU than me.

We can fix it temporarily, however it's not ideal and comes with its own set of issues
