### ISSUE TITLE
[BUG] No more import.lua?

### ISSUE THREAD

**Issue by BlueSky-fur** [qbcore-framework/qb-core#398]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
i cant find an import.lua in the files anymore, not even on this repo
**To Reproduce**
Download qb-core and see yourself
**Expected behavior**
usually it should contain one.
**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] newest.
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] a few
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
In case that got removed completly, what are we supposed to use then as QBCore = nil seems to not work anymore

**Comment by GhzGarage** [comment]
QBCore = exports[“qb-core”]:GetCoreObject()

**Comment by jay-fivem** [comment]
The import.lua was removed on Nov 10th. It's been replaced with QBCore = exports[“qb-core”]:GetCoreObject()

**Comment by BlueSky-fur** [comment]
Woops, sorry just forgot to close this.

**Comment by johnsmith600** [comment]
do i remove the triggerserverevent and client or do they stay

**Comment by BlueSky-fur** [comment]
> do i remove the triggerserverevent and client or do they stay

What exactly are you trying to do?
