### ISSUE TITLE
[BUG] Fix bicycles  so they are purchasable at PDM

### ISSUE THREAD

**Issue by chunce01** [qbcore-framework/qb-core#415]
**Describe the bug**
The vehicles file is missing the "Brand" for bicycles this prevents PDM /  qb-vehicleshop from pulling the bicycle for sale. The bicycle is pulled for display but you cannot purchase it and the buy options show the last vehicle on display.

**To Reproduce**
1. Go to PDM 
2. Click on Bicycle option and attempt to buy it will purchase previous vehicle on display.

**Expected behavior**
The purchase option should allow you to buy the bicycle while the bicycle is on display

**Additional context**
This can be resolve by updating the Bicycles in the vehicles file to have their brand:

['tribike'] = {
		['name'] = 'Whippet Race Bike',
		['brand'] = 'Whippet',
		['model'] = 'tribike',
		['price'] = 2500,
		['category'] = 'Bicycles',
		['hash'] = `tribike`,
		['shop'] = 'pdm',
	},
	['tribike2'] = {
		['name'] = 'Endurex Race Bike',
		['brand'] = 'Endurex ',
		['model'] = 'tribike2',
		['price'] = 2500,
		['category'] = 'Bicycles',
		['hash'] = `tribike2`,
		['shop'] = 'pdm',
	},
	['tribike3'] = {
		['name'] = 'Tri-Cycles Race Bike',
		['brand'] = 'Tri-Cycles',
		['model'] = 'tribike3',
		['price'] = 2500,
		['category'] = 'Bicycles',
		['hash'] = `tribike3`,
		['shop'] = 'pdm',
	},
	['bmx'] = {
		['name'] = 'BMX Bike',
		['brand'] = 'bmx',
		['model'] = 'bmx',
		['price'] = 750,
		['category'] = 'Bicycles',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
	['scorcher'] = {
		['name'] = 'Scorcher Mountain Bike',
		['brand'] = 'scorcher',
		['model'] = 'scorcher',
		['price'] = 1500,
		['category'] = 'Bicycles',
		['hash'] = `scorcher`,
		['shop'] = 'pdm',
	},
	['cruiser'] = {
		['name'] = 'Beach Cruiser Bike',
		['brand'] = 'cruiser',
		['model'] = 'cruiser',
		['price'] = 750,
		['category'] = 'Bicycles',
		['hash'] = `cruiser`,
		['shop'] = 'pdm',
	},

**Comment by Mojito-Fivem** [comment]
If you can pull request these changes that would be great

**Comment by chunce01** [comment]
Feel free to close this out it has been moved to a PR request.
