### ISSUE TITLE
Zeno name issue

### ISSUE THREAD

**Issue by CTRP-Framework** [qbcore-framework/qb-core#425]
['zeno'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Patriot',
		['brand'] = 'Mil-Spec',
		['model'] = 'zeno',
		['price'] = 1350000,
		['category'] = 'coupes',
		['hash'] = `zeno`,
		['shop'] = 'pdm',
	},

replace this with 

['zeno'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Zeno',
		['brand'] = 'Overflod',
		['model'] = 'zeno',
		['price'] = 1350000,
		['category'] = 'dlc',
		['hash'] = `zeno`,
		['shop'] = 'pdm',
	},

**Comment by GhzGarage** [comment]
Make a PR
