### ISSUE TITLE
[BUG] Vehicle can't save color

### ISSUE THREAD

**Issue by DxMaxi** [qbcore-framework/qb-core#428]
I dont know if its here to share this, if not im sorry

Everytime i store a vehicle on garage and take out the vehicle change everytime color and it happens with boats too

 - When you last updated: The qb-core is updated from last updates
 - Are you using custom resource? which ones? MojiaGarages
 - Have you renamed `qb-` to something custom? no

**Comment by Mojito-Fivem** [comment]
There is probably some issue with your garages / vehicleshop, if it can't find the mods to load it just defaults it to however it would naturally spawn.

**Comment by DxMaxi** [comment]
> There is probably some issue with your garages / vehicleshop, if it can't find the mods to load it just defaults it to however it would naturally spawn.

I will see, but must be garages because vehicleshops and core are defaults with alittle changes from PR, but thank you anyways <3

**Comment by JesseJames804** [comment]
Did u ever figure this out?
