### ISSUE TITLE
[BUG] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export executeSync in resource oxmysql

### ISSUE THREAD

**Issue by enekooo02** [qbcore-framework/qb-core#436]
![image](https://user-images.githubusercontent.com/97302939/148571698-7a82341a-3e5e-4d82-bc7d-69a7087688ce.png)

**Comment by izMystic** [comment]
You're missing the entirety of voice & standalone files, making this a user error

**Comment by ARSSANTO** [comment]
try to download oxmysql 1.8.7  some export deprecated from letest oxmysql
