### ISSUE TITLE
[BUG] Having an issue where after /setjob [ID] Jobname [Rank] it doesn't update. along with unable to do anything with vehicles due to a trim error.

### ISSUE THREAD

**Issue by JohnBroadway** [qbcore-framework/qb-core#438]
So my first issue is after ive set someones job and do a city restart jobs are not saving. but no error in F8 or server console.

My second issue is i have an Error

Script error: @qb-core/client/functions.lua:406: attempt to call nil value (Field 'trim') 

I have no idea on thje resolution and have searched everywhere for a fix but ended up here.

**Comment by GhzGarage** [comment]
You are missing a function located in the shared/main.lua or your core is out of date

You can get more help at discord.gg/qbcore
