### ISSUE TITLE
issues with day and nicht

### ISSUE THREAD

**Issue by MaDHouSe79** [qbcore-framework/qb-core#444]
I wonder why it's always nighttime on my server, I have to change the time every time, to get it daytime, no matter how I set it, if I turn off all timers and timesinc off then it's still always at night, really this is so annoying.

**Comment by GhzGarage** [comment]
Make an issue on qb-weathersync not here

**Comment by MaDHouSe79** [comment]
well like i said, even if i turm of the weathersync, its is stil always nicht, so i dont think the issue is on weathersync. i turn everting off and it is stil dark. i have to chenge the time by hand every time over en over again.
