### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Friskiukas** [qbcore-framework/qb-core#445]
updated to the most recent update (about 2 hrs ago?) and upon launching the server, this comes up
![CshEdie2zHa5Umx9wWrVKqlI](https://user-images.githubusercontent.com/5913581/148748226-b5bdfd6e-fcde-4ce9-bd4e-8a1dd02a7ee2.png)

**Comment by IdrisDose** [comment]
What OXMysql version are you running, the latest update is 1.9.0+ only

**Comment by Friskiukas** [comment]
nvm, i'm stupid, i got a fresh recipe like yesterday or the day before that, thought oxmysql 1,9.0+ would come with the latest recipe, forgot to check ;x

**Comment by strongprincess** [comment]
![image](https://user-images.githubusercontent.com/81395433/148845599-bb93f1cb-e785-4567-80c1-50b8452f12cd.png)
