### ISSUE TITLE
[SUGGESTION] Add persistent notifications

### ISSUE THREAD

**Issue by Brady-F** [qbcore-framework/qb-core#470]
**Is your feature request related to a problem? Please describe.**
Unoptimized and ugly DrawText

**Describe the feature you'd like**
That ability to have persistent notifications, something like what [t-notify](https://docs.tasoagc.dev/#/usage?id=examples) provides. Allows you to start, update, and end persistent notifications. 

**Describe alternatives you've considered**
To use built in DrawText however it is not as optimized as something like t-notify persistent notifications.

**Additional context**
Persistent notifications have multiple use cases, including something like the respawn timer.

**Comment by BerkieBb** [comment]
dev branch of qb-core has this now
