### ISSUE TITLE
[SUGGESTION] TR Version

### ISSUE THREAD

**Issue by BennUzi** [qbcore-framework/qb-core#475]
There is no translation for Turks, so I will translate the locales of each script and send it.

tr.lua

local Translations = {
    error = {
        not_online = 'Oyuncu aktif değil',
        wrong_format = 'Yanlış format',
        missing_args = 'Her argüman girilmedi (x, y, z)',
        missing_args2 = 'Tüm argümanlar doldurulmalı!',
        no_access = 'Bu komuta erişim yok',
        company_too_poor = 'İşvereniniz kırıldı',
        item_not_exist = 'Öğe yok',
        too_heavy = 'Üzerinizde çok fazla ağırlık var'
    },
    success = {},
    info = {
        received_paycheck = 'Maaşınızı aldınız $%{value}',
        job_info = 'Meslek: %{value} | Seviye: %{value2} | Mesai: %{value3}',
        gang_info = 'Grup: %{value} | Seviye: %{value2}',
        on_duty = 'Mesaiye girdiniz!',
        off_duty = 'Mesaiden çıktınız!'
    }
}

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})

**Comment by BerkieBb** [comment]
Make a Pull Request instead of an issue

**Comment by BennUzi** [comment]
Okay
