### ISSUE TITLE
[BUG] - Prepare Error

### ISSUE THREAD

**Issue by NocityRP** [qbcore-framework/qb-core#476]
Updated to the latest qb-core, and getting this error when trying to join my city, getting no errors in the F8 Menu, but getting this error in the console when trying to join

Console:
![image](https://user-images.githubusercontent.com/93712286/149233914-722dd93b-cc60-4d40-90f9-048e5ab257d7.png)

**Comment by NocityRP** [comment]
I have all the latest scripts that have been updated in the last week, I haven't made any edits to the files, just drag and drop.

**Comment by CROVVY** [comment]
I have the same issue here. I can't load from the multichar menu in the city

**Comment by LRemp** [comment]
Is your database plugin(oxmysql) up-to-date? If not, try updating it, because from the error it clearly fails while calling a query function from mysql plugin, if I'm not wrong.

**Comment by LRemp** [comment]
Head to the official oxmysql repository and check releases [https://github.com/overextended/oxmysql/releases/tag/v1.9.3](url) 🙂

**Comment by CROVVY** [comment]
> Head to the official oxmysql repository and check releases [https://github.com/overextended/oxmysql/releases/tag/v1.9.3](url) 🙂

I've added the newest version of oxmysql and the console was flooded by errors. Oxmysql needs server 5104 or higher (they mean FX Server I guess). How can I update that please?

**Comment by CROVVY** [comment]
I have GameBuild 2545, but dont know how to update the server version

**Comment by NocityRP** [comment]
> It basically means that Oxmysql requires server artifacts of version 5104 or greater(which could be found in [https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/](url)), if yours doesn't meet that requirment, update.

Just turned out I need to update my oxmysql
