### ISSUE TITLE
[SUGGESTION] Merge weapons as happened with vehicles previously

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-core#478]
**Is your feature request related to a problem? Please describe.**

Hello everyone, we have a clear repetition which is that the weapons file is repeated twice
Why can't the two be combined into one?
It will be better and ease of modifications by users

**Describe the feature you'd like**
Once upon a time the vehicles were duplicates and their problem was solved
Hope we get this soon

https://github.com/qbcore-framework/qb-core/blob/4490aba0f57e142fb739cf66f0354ee5b9b305bb/shared/weapons.lua#L5
https://github.com/qbcore-framework/qb-core/blob/4490aba0f57e142fb739cf66f0354ee5b9b305bb/shared/items.lua#L5

**Comment by Demo4889** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Hello everyone, we have a clear repetition which is that the weapons file is repeated twice Why can't the two be combined into one? It will be better and ease of modifications by users
> 
> **Describe the feature you'd like** Once upon a time the vehicles were duplicates and their problem was solved Hope we get this soon
> 
> https://github.com/qbcore-framework/qb-core/blob/4490aba0f57e142fb739cf66f0354ee5b9b305bb/shared/weapons.lua#L5
> 
> 
> https://github.com/qbcore-framework/qb-core/blob/4490aba0f57e142fb739cf66f0354ee5b9b305bb/shared/items.lua#L5

items and weapons are used in 2 different ways. I just updated the weapons.lua recently to remove unneeded data from it and include new data pertaining to damagereasons for the ambulancejob locales update. There will probably be more information updated regarding these 2 files in the upcoming weeks.
