### ISSUE TITLE
[BUG] QB-blackjack missing object.

### ISSUE THREAD

**Issue by MrPandaCoding** [qbcore-framework/qb-core#499]
**Describe the bug**
hey when I launched my server it keeps saying that qb-blackjack is missing an object. just looking for some help on this issue im also running the most recent build for qb-core.

**Expected behavior**
I expected it to load the resources but every time I've restarted the recourse it just says its missing an object.

**Questions (please complete the following information):**
 - When you last updated: last night
 - Are you using custom resource? which ones? no custom resources
 - Have you renamed `qb-` to something custom? no

**Comment by Treesftw** [comment]
You have to make sure the server is running on build 2060 or higher.

**Comment by MrPandaCoding** [comment]
It is running on a version higher then that though.

**Comment by Treesftw** [comment]
Try and set it to 2060. I had the same problem and after I did that it fixed itself.

**Comment by MrPandaCoding** [comment]
So change the version to what version sorry :/ got a little confused.

**Comment by Treesftw** [comment]
Haha no worries. So go into your server.cfg. Then anywhere in the cfg add "set sv_enforceGameBuild 2060" (without the quotations ofc)

**Comment by MrPandaCoding** [comment]
Let me check to see if that works!

**Comment by MrPandaCoding** [comment]
So I got the casino to work lol but I don't see how to access the blackjack aspect of it. Any help?
