### ISSUE TITLE
[BUG] connecting stuck on "Hello ____, We are checking if you are banned."

### ISSUE THREAD

**Issue by beeget** [qbcore-framework/qb-core#501]
**Describe the bug**
If a player got banned from the server and tried to rejoin, he will be stuck in the connection with this message "Hello ____, We are checking if you are banned."

**To Reproduce**
1. Banned a player from the admin menu, or using the database
2. Join the server

**Expected behavior**
Show the ban message or if the ban has been expired already, delete the result from the database.

**Questions (please complete the following information):**
 - When you last updated: Server made few minutes ago with latest files.
 - Are you using custom resource? which ones? all qbcore-framework resources, no other added.
 - Have you renamed `qb-` to something custom? no changes made.

**Additional context**
I've fixed it by replacing `result[1].reason` to `result.reason` (line 394) and `result[1].id` to `result.id` (line 396) in [server/functions.lua](https://github.com/qbcore-framework/qb-core/blob/main/server/functions.lua)

since it's a single fetch, there will be only 1 result and not an array.

**Comment by IllInuz** [comment]
Why dont u PR the fix for it if you provide it here?
