### ISSUE TITLE
[BUG] Failed to load script @qb-core/import.lua.

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-core#507]
**Describe the bug**
I have used QB-Core for a couple weeks now, all of a sudden I started getting this error for one of the scripts I am using.

**To Reproduce**
1. Download QB-Core
2. Install and start the server.

**Expected behavior**
Your not meant to receive any errors.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? Error is for Core_MDW and a free converted QBUS MDT system.
 - Have you renamed `qb-` to something custom? No

**Additional context**
I have attempted to update oxmysql with no luck to fix the error, I did this as I am also receiving an error which states "No such export fetch in resource oxmysql" I have no idea if this is related hence why I am mentioning it.

**Comment by Nico-999** [comment]
Same, waiting for help

**Comment by Newtonzz** [comment]
"No such export fetch in resource oxmysql" relates to having an outdated version of the resource.
