### ISSUE TITLE
[BUG] won’t launch menus, client requires restart 

### ISSUE THREAD

**Issue by JYNKZIE** [qbcore-framework/qb-core#511]
**Describe the bug**
inventory menu won’t launch upon pressing the TAB bind. Other menus launch, but client will lock and require a restart. Creating new character the clothing menu will not appear and launch straight to spawn locations/apartment selection. Last location seems to not be working, but I assumed that was a sql database issue (not associated with the menus but thought worth noting)

**Expected behavior**
Open a menu, phone or store. Client will lock with cursor still movable and sounds and game still working, but no keybindings can be activated, not even chat. 

**Questions (please complete the following information):**
 - When you last updated: today. 
 - Are you using custom resource? which ones? Qb-hud, menuv, qb-menu, everything dependency on qb-multi character and phone 
 - Have you renamed `qb-` to something custom? Yes

**Comment by MrKualaPT** [comment]
I am having the same issues, Inventory doesn't open, garage ... and the tunner chip and taxi meter is showing up

**Comment by izMystic** [comment]
>Have you renamed `qb-` to something custom? Yes

Then dont? You probably didnt do it right and broke it
