### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ericrosa09** [qbcore-framework/qb-core#515]
When I add some Custom EUP, Some features of QBCore does not work like going on duty etc.

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? Yes - Only custom eup
 - Have you renamed `qb-` to something custom? Nope

**Comment by MonkeyWhisper** [comment]
Unable to duplicate. Duty checks have nothing to do with streaming clothing.
