### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by gcoulby** [qbcore-framework/qb-core#522]
I've just downloaded QBcore and it wipes the floor with esx as a starting point, well done there. I have noticed that there are several interior/exterior maps that are not included, or designed to be paid addons. For example, mission row of has code to open gates but no gate, the casino is on the map, but no interior, Paleto PD doors open to brick walls, ifruit shop has no interior neither does smoke on the water. There is probably a tonne more. Obviously this code is designed around specific maps but I cannot find a list Of which ones to use neither here nor in the docs. Does this list exist? If not, could it be provided?

**Comment by izMystic** [comment]
MRPD: not sure which one has a gate there
Casino: https://forum.cfx.re/t/cayo-perico-casino-dlc-ipl-loader/2099391
Paleto PD: default gta interior
iFruit Store: still searching for a free one to include for the qb-ifruitstore
Smoke on the water: is only open during the day (gta feature)
