### ISSUE TITLE
[ISSUE] Loading Screens with mouse interactions not working with QBCore

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/qb-core#524]
I've noticed that my current loading screen, which has mouse interactivity to move your mouse around to either click on menus or just move it around messing with the effects to keep people busy while the server is loading.... the mouse is now disabled. Noticed this about a month ago.

It appears that the mouse is disabled by QBCore somewhere during the loading process. We've tried multiple loading screens with mouse interactivity and they all don't work. They do work with any other framework or if the loading screen is all by itself as a resource all alone, but the moment we pair it with QBCore, the mouse just simply doesn't work on the loading screens.

I have no idea where else to post this, thought this would be the most appropriate place here at the core.

**Comment by MonkeyWhisper** [comment]
This isn't a issue with qb-core, this is an issue with your loading screen. Ask for help in QBCore Discord.

**Comment by ItsANoBrainer** [comment]
Not an issue with the qb-core resource, call `ShutdownLoadingScreenNui()` and `ShutdownLoadingScreen()` when your player has triggered a join. See how qb-loading does it.
