### ISSUE TITLE
qbcore/shared/main.lua:23: bad argument #1 to 'find' (string expected, got nil)

### ISSUE THREAD

**Issue by KriLLTW** [qbcore-framework/qb-core#531]
qbcore/shared/main.lua:23: bad argument #1 to 'find' (string expected, got nil)

![image](https://user-images.githubusercontent.com/99408695/153790815-7a9bfb4e-d407-4d1f-b7c2-6d6ab50a20a3.png)

**Comment by MonkeyWhisper** [comment]
This isn't a bug, this is a problem with your core. Ask for help in Discord.
