### ISSUE TITLE
[SUGGESTION] PlayerData and player functions accessible for offline players

### ISSUE THREAD

**Issue by shaunhardy** [qbcore-framework/qb-core#537]
**Is your feature request related to a problem? Please describe.**
PlayerData and player functions are not accessible for offline players, making it impractical to make scripts that reference offline players.

**Describe the feature you'd like**
I would like PlayerData and player functions to be accessible even for offline players. `QBCore.Functions.GetPlayerByCitizenId()` and `QBCore.Functions.GetPlayerByPhone()` should return a Player instance with all PlayerData loaded, only without a source. An example of a script that would benefit from this would be a police MDT to look up players.

**Describe alternatives you've considered**
An alternative would be reading/writing database tables directly. This would be much less ideal as there would be no separation of responsibilities.

**Additional context**
A small amount of refactoring around saving and loading would be required, but I don't see any big blockers.

**Comment by BerkieBb** [comment]
They are accessible for offline players, just not with the default functions, to access them you need to use sql

**Comment by GhzGarage** [comment]
Been implemented

**Comment by Hryper** [comment]
Hi, this is listed as "Been implemented" however i recently tried to use QBCore.Functions.GetPlayerByCitizenId(player), which works perfectly fine on my online players, however not on offline players
