### ISSUE TITLE
[BUG] core

### ISSUE THREAD

**Issue by madalex24** [qbcore-framework/qb-core#540]
ive got severeal errors with qb core 

 c-scripting-core] Creating script environments for qb-adminmenu
[ script:qb-adminmenu] Error loading script server/server.lua in resource qb-adminmenu: citizen:/scripting/lua/scheduler.lua:867: No such export GetCoreObject in resource qb-core
[ script:qb-adminmenu] stack traceback:
[ script:qb-adminmenu] 	[C]: in function 'error'
[ script:qb-adminmenu] 	citizen:/scripting/lua/scheduler.lua:867: in metamethod 'index'
[ script:qb-adminmenu] 	@qb-adminmenu/server/server.lua:2: in main chunk
[    c-scripting-core] Failed to load script server/server.lua.
[ citizen-server-impl] Started resource qb-adminmenu
[    c-scripting-core] Creating script environments for qb-afk
[       script:qb-afk] Error loading script server/main.lua in resource qb-afk: citizen:/scripting/lua/scheduler.lua:867: No such export GetCoreObject in resource qb-core
[       script:qb-afk] stack traceback:
[       script:qb-afk] 	[C]: in function 'error'
[       script:qb-afk] 	citizen:/scripting/lua/scheduler.lua:867: in metamethod 'index'
[       script:qb-afk] 	@qb-afk/server/main.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource qb-afk
[    c-scripting-core] Creating script environments for qb-ambulancejob
[script:qb-ambulancej] Error loading script server/main.lua in resource qb-ambulancejob: citizen:/scripting/lua/scheduler.lua:867: No such export GetCoreObject in resource qb-core
[script:qb-ambulancej] stack traceback:
[script:qb-ambulancej] 	[C]: in function 'error'
[script:qb-ambulancej] 	citizen:/scripting/lua/scheduler.lua:867: in metamethod 'index'
[script:qb-ambulancej] 	@qb-ambulancejob/server/main.lua:3: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource qb-ambulancejob
[    c-scripting-core] Creating script environments for qb-anticheat
[ script:qb-anticheat] Error loading script server/main.lua in resource qb-anticheat: citizen:/scripting/lua/scheduler.lua:867: No such export GetCoreObject in resource qb-core
[ script:qb-anticheat] stack traceback:
[ script:qb-anticheat] 	[C]: in function 'error'
[ script:qb-anticheat] 	citizen:/scripting/lua/scheduler.lua:867: in metamethod 'index'
[ script:qb-anticheat] 	@qb-anticheat/server/main.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource qb-anticheat

**Comment by mk3ext** [comment]
You need to update the core and those scripts

**Comment by MonkeyWhisper** [comment]
This isn't a bug, this is a problem with your core. Ask for help in Discord.
