### ISSUE TITLE
[BUG] HELPP PLASE????/

### ISSUE THREAD

**Issue by hoodz123** [qbcore-framework/qb-core#541]
soon as i add on a vehicle in shared lua even if i replace it instead of adding it on i get this error straight away Error parsing script @qb-core/shared/vehicles.lua in resource qb-core: @qb-core/shared/vehicles.lua:1: unexpected symbol near '<\239>'
[    c-scripting-core] Failed to load script shared/vehicles.lua.

**Comment by MonkeyWhisper** [comment]
This isn't a bug, this is a problem with your core. Ask for help in Discord.

**Comment by zunq** [comment]
> 

It is saying at line 239 you've got an unexcepted symbol. I suggest reviewing your code to make sure you haven't got an extra comma or bracket anywhere.
