### ISSUE TITLE
[BUG] Black Screen

### ISSUE THREAD

**Issue by PlzAdoptMee** [qbcore-framework/qb-core#543]
I tried to stick in a new qb-core but after I select my character it stays on an infinite black screen with a white loading circle on the bottom right. I am not getting any error codes. How do I fix this?

**Comment by MonkeyWhisper** [comment]
This isn't a bug, this is a problem with your core. Ask for help in Discord.

**Comment by PlzAdoptMee** [comment]
> This isn't a bug, this is a problem with your core. Ask for help in Discord.

I have asked the discord and pretty much none of them know why. It only happens when I put in the new Core files. WHen I got back to my old ones it will open up just fine. But i can use my old one bc nothing else will work due to a Lang error

**Comment by zunq** [comment]
@PlzAdoptMee This is 100% due to an error in a shared/*.lua file. I suggest checking any of them that you've changed and ensure you haven't missed a bracket or a comma or anything like that.

**Comment by PlzAdoptMee** [comment]
> @PlzAdoptMee This is 100% due to an error in a shared/*.lua file. I suggest checking any of them that you've changed and ensure you haven't missed a bracket or a comma or anything like that.

Havent mess with it. I stuck in a fresh install and it still happens

**Comment by zunq** [comment]
> > @PlzAdoptMee This is 100% due to an error in a shared/*.lua file. I suggest checking any of them that you've changed and ensure you haven't missed a bracket or a comma or anything like that.
> 
> Havent mess with it. I stuck in a fresh install and it still happens

Interesting if you haven't touched anything, is there any errors in either client console or server console. Cause normally there would be an error on either script startup or in red when you join. Please check carefully and report back.

**Comment by ItsANoBrainer** [comment]
No reproduction, screenshots, or information we can work with. 

Bring this to discord support.

**Comment by WENKz** [comment]
> i need help with this also

Did you find any solution ?

**Comment by Townyo420** [comment]
i believe its an inventory issue i have reinstalled the core multiple times and it still has this same problem 
im not to sure if its on the inventory completely or if its on the multicharacter but the multicharacter still loads for me and shows up after it goes to a black screen and ive checked over my items multiple times there would be an orange = sign if there was something wrong with my files items / jobs but there wasnt any errors in the console so im a bit confused my self as to why this is happening even tried installing a new core at least 3 times but that didnt seem to work either and i havent messed with any files  nor does qbcore have support tickets in there discord so its almost impossible to even get a hold of someone who " might know the solution " to the problem that we all seem to be having.

**Comment by 0auro0** [comment]
Yall who are using ox inv cheat them items.lua to!

**Comment by Gambolllek** [comment]
The problem is qb-multicharacter and spawn selection. I just set the SkipSelection to true in config and resolve the problem
