### ISSUE TITLE
Paychecks

### ISSUE THREAD

**Issue by anthonyakilla93** [qbcore-framework/qb-core#547]
I do not know what happening with the older and newer QBCore no one in my server is getting paychecks at all! Seems as if i clear the server cache people get the first paycheck after reset and that is the only one they get. Did some reasearch on the disocrd and seems as if i am not the only person with the simular issue.

**Comment by zunq** [comment]
I have received a similar issue recently which I am still trying to investigate. I believe it has someone to do with extra jobs being added incorrectly. Almost as if they need to not only be put in qb-core/shared/jobs.lua but also in another section of qb-core resource to actually function correct. A temporary solution I come up with is this removing the current paycheck loop and added this one below.

```
function PaycheckLoop()
    local Players = QBCore.Functions.GetPlayers()
    for i = 1, #Players, 1 do
        local Player = QBCore.Functions.GetPlayer(Players[i])
        if Player.PlayerData.job and Player.PlayerData.job.onduty and Player.PlayerData.job.payment > 0 then
            Player.Functions.AddMoney('bank', Player.PlayerData.job.payment)
            TriggerClientEvent('QBCore:Notify', Players[i], 'You received your paycheck of $' .. Player.PlayerData.job.payment)
        end
    end
    SetTimeout(QBCore.Config.Money.PayCheckTimeOut * (60 * 1000), PaycheckLoop)
end
```

By all means this is not a perfect solution and something I am continuing to investigate as to why it won't pay certain jobs (well none to be honest) with the original paycheck loop.

If you find anything, please let me know.

**Comment by BerkieBb** [comment]
It's likely because of the players table containing nil values from people logging out and it not being checked in the paycheckloop function

**Comment by dadhatdaniel** [comment]
still getting money even though society is broke - 
QBConfig.Money.PayCheckSociety = true

qb-core updated this morning
qb-management updated
people are getting paid when their society has 0

is this a qb-bossmenu (removed) / qb-management issue? not seeing any errors

**Comment by BerkieBb** [comment]
You should've opened a new issue for that instead but that is not an issue but a feature

**Comment by dadhatdaniel** [comment]
You are probably right bob, how is that not an issue but a feature? How do I make it so it actually works the way the description and config is written?

**Comment by dadhatdaniel** [comment]
I love you, thank you.

**Comment by Xdelic** [comment]
can someone give an example of how they wrote this statement for checking jobs please? im having a really hard time with pulling it from the society account. Please forgive me as I am very knew to this side of coding (be gentle lol)
