### ISSUE TITLE
[BUG] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export single in resource oxmysql

### ISSUE THREAD

**Issue by nuage00** [qbcore-framework/qb-core#549]
**Describe the bug**
I get "SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export single in resource oxmysql" when my server starts. With the latest qb and oxmysql.

**To Reproduce**
1. Go to 'server.cfg'
2. Set the mysql connection string
3. Start your server

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] yesterday
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by nuage00** [comment]
Also there's a one more error:

`[    c-scripting-core] Creating script environments for oxmysql
[      script:oxmysql] Error loading script dist/build.js in resource oxmysql: TypeError [ERR_INVALID_URL]: Invalid URL
[      script:oxmysql] stack:
[      script:oxmysql] TypeError: Invalid URL
[      script:oxmysql]     at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
[      script:oxmysql]     at new NodeError (node:internal/errors:371:5)
[      script:oxmysql]     at onParseError (node:internal/url:552:9)
[      script:oxmysql]     at new URL (node:internal/url:628:5)
[      script:oxmysql]     at Function.parseUrl (@oxmysql/dist/build.js:13106:27)
[      script:oxmysql]     at new ConnectionConfig (@oxmysql/dist/build.js:12968:47)
[      script:oxmysql]     at new PoolConfig (@oxmysql/dist/build.js:14048:33)
[      script:oxmysql]     at Object.exports.createPool (@oxmysql/dist/build.js:14345:33)
[      script:oxmysql]     at createPool2 (@oxmysql/dist/build.js:14710:29)
[      script:oxmysql]     at @oxmysql/dist/build.js:21522:42
[    c-scripting-core] Failed to load script dist/build.js.`

**Comment by BerkieBb** [comment]
This is not a qb-core problem but it's because you have the wrong version and/or you setup oxmysql wrong, please download the **release** of oxmysql
