### ISSUE TITLE
add gang grade

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-core#55]
```
	self.Functions.SetGang = function(gang)
		local gang = gang:lower()
		if QBCore.Shared.Gangs[gang] ~= nil then
			self.PlayerData.gang.name = gang
			self.PlayerData.gang.label = QBCore.Shared.Gangs[gang].label
			self.Functions.UpdatePlayerData()
			TriggerClientEvent("QBCore:Client:OnGangUpdate", self.PlayerData.source, self.PlayerData.gang)
		end
	end
```

	["ballas"] = {
		label = "ballas gang",
		bossmenu = vector3(-124.786, -641.486, 167.820),
		grades = {
            ['0'] = {
                name = "member",
                payment = 50
            },
	['1'] = {
                name = "leader",
		isboss = true,
                payment = 150
            },
        },

**Comment by JericoFX** [comment]
make a pr, this is issues place.

**Comment by vanillla1** [comment]
Why are you closing the case?
All suggestions are closed by you
Do you think your opinion is right?
And all those who make suggestions
They offer empty things
calm down man

**Comment by vanillla1** [comment]
This is a good option for everyone @JericoFX

**Comment by JericoFX** [comment]
We are reviewing all pr and issues right now, no need for ping, thanks for the code
