### ISSUE TITLE
[BUG] petrolcan does not expire

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-core#562]
**Describe the bug**
The problem of a gallon of petrolcan does not expire
And when it ends, it reproduces itself
It fills up again

**Screenshots**
im dont have screenshot

**Questions (please complete the following information):**
 - When you last updated: [last week]
 - Are you using custom resource? which ones? [e.g. qb-target]
 - Have you renamed `qb-` to something custom? [e.g. no]

**Comment by LilWhit3ADG** [comment]
True. When using a jerry can to fuel a vehicle, if you put it away when its completed fuelling and take it back out its back at the original capacity. Meaning unlimited fuel.

**Comment by restray** [comment]
Patch on https://github.com/qbcore-framework/qb-inventory/pull/90/files

Sync issue on qb-inventory and LegacyFuel.

And actually maybe that line: https://github.com/qbcore-framework/qb-inventory/blob/daec4fe4c49085770110ed908f318f6142d2e2a8/client/main.lua#L453
