### ISSUE TITLE
[BUG] Adding Cars

### ISSUE THREAD

**Issue by Zack41199** [qbcore-framework/qb-core#563]
Im having an issue where when i add cars to vehicles.lua it deletes the entire car list in admin menu and will not display any vehicles for sale in the shop

**Comment by restray** [comment]
Hi!
Can you post your vehicles.lua please ? 
Is there any error in your FiveM Console (F8) ?
I'll try to help even if I'm not an QBCore developer :)

**Comment by GhzGarage** [comment]
discord.gg/qbcore
