### ISSUE TITLE
[BUG]error in console when using /logout

### ISSUE THREAD

**Issue by Egypt1123** [qbcore-framework/qb-core#565]
[      script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:152: attempt to index a nil value (local 'Player')
[      script:qb-core] > handler (@qb-core/server/events.lua:152)
[      script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:152: attempt to index a nil value (local 'Player')
[      script:qb-core] > handler (@qb-core/server/events.lua:152)

**To Reproduce**
use /logout to change character

**Comment by restray** [comment]
Maybe moving this line https://github.com/qbcore-framework/qb-core/blob/617dc0e760ca176fc78ee2da6d87339d19f3826a/server/events.lua#L152 in the [if-condition](https://github.com/qbcore-framework/qb-core/blob/617dc0e760ca176fc78ee2da6d87339d19f3826a/server/events.lua#L149) to avoid any sort of bug on this

**Comment by BerkieBb** [comment]
> Maybe moving this line
> 
> https://github.com/qbcore-framework/qb-core/blob/617dc0e760ca176fc78ee2da6d87339d19f3826a/server/events.lua#L152
> 
> in the [if-condition](https://github.com/qbcore-framework/qb-core/blob/617dc0e760ca176fc78ee2da6d87339d19f3826a/server/events.lua#L149) to avoid any sort of bug on this

Actually that if statement prevents these errors, so he has a modified core
