### ISSUE TITLE
[BUG] Vehicle Livery Function

### ISSUE THREAD

**Issue by NoobySloth** [qbcore-framework/qb-core#572]
**To Reproduce**
buy car > store in garage > take out of garage > bennys customs > buy cool boi livery > store in garage > take out of garage > bennys customs > livery (stock) > store in garage > take out of garage > has cool boi livery and not stock

It appears that when saving it doesn't put the livery to -1 when saving as stock.

[https://medal.tv/games/gta-v/clips/eNjmZJWjDaPC9/lktjdeDuBT4Z?invite=cr-MSxkQmIsNDM4NTI1MTEs](url)
I have a video here to help understand the process.

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-core/commit/52dc610c6c97f21fdd1090850bd34332ba05195e
Could you tell me if this fixes your issue?

**Comment by RenggoStarz** [comment]
> [52dc610](https://github.com/qbcore-framework/qb-core/commit/52dc610c6c97f21fdd1090850bd34332ba05195e) Could you tell me if this fixes your issue?

why i cant store my vehicle..  ["This vehicle can't be stored",] how to fix this

**Comment by NoobySloth** [comment]
> [52dc610](https://github.com/qbcore-framework/qb-core/commit/52dc610c6c97f21fdd1090850bd34332ba05195e) Could you tell me if this fixes your issue?

Hey! I can confirm this did not fix, the same issue persists :(

**Comment by BansaGaming** [comment]
I can also confirm this does not fix the problem.

**Comment by Rav3n95** [comment]
I just downloaded a brand new fresh core to update my garage pr, its confirmed still happening.

**Comment by DannysRP** [comment]
I am testing this well and it is still an issue

**Comment by NoobySloth** [comment]
Also, appears that neon lights aren't saving after the update?

**Comment by Gurumi-Heist** [comment]
I've also had this issue when I had a few standalone scripts messing with the vehicle like vehicle failure and other stuff which I mistakenly copied over from my ESX server to QBCore. Try removing any of those if you have them and try again

**Comment by ItsANoBrainer** [comment]
Update core fully.

**Comment by ouzg** [comment]
buy car > store in garage > take out of garage > bennys customs > buy any livery without first livery > store in garage > take out of garage > bennys customs > livery (stock) > store in garage > take out of garage > has livery and not stock

But after the updated version of core , if we want to buy stock livery after buying any livery,
 
store in garage > take out of garage > bennys customs > buy first livery > store in garage > take out of garage > bennys customs > livery (stock) > store in garage > take out of garage > has stock livery.

**It should provide for all liveries , not for first livery. How do we provide revert to stock livery after purchasing any livery?**

**Comment by ouzg** [comment]
After my research, i found a solution for basic qb package with fully updated versions of qb scripts , when i apply this pr 
" [https://github.com/qbcore-framework/qb-customs/pull/128](url) " to fixed it , my problem has been solved. Thank you @xenfovn .
