### ISSUE TITLE
[BUG] no admin

### ISSUE THREAD

**Issue by next-game** [qbcore-framework/qb-core#575]
console commands do not work, it is impossible to call the admin menu, etc.
the build was updated today via a remote txAdmin URL.
as I understand it, we made changes in the code for optimization, the files are different from the old ones
\qb-core\server\commands.lua
replaced the folder \qb-core\  with the old one from March 13 everything worked
![coommannd](https://user-images.githubusercontent.com/101860571/159744262-816f9b02-b798-4684-85d4-9027c140e540.png)

**Comment by tafabdel** [comment]
same issue

**Comment by MG79NC** [comment]
Same issue i had to roll back to older version to get into my admin, i also couldn't do any commands at all the ones i tried i got the no access message...

**Comment by next-game** [comment]
no one answered in the topic, I understand there is no solution to this problem?

**Comment by BerkieBb** [comment]
No it was fixed

**Comment by BerkieBb** [comment]
With this commit https://github.com/qbcore-framework/qb-core/commit/1dfdb46105109de58963b64a99087146c83c7215

**Comment by next-game** [comment]
> With this commit [1dfdb46](https://github.com/qbcore-framework/qb-core/commit/1dfdb46105109de58963b64a99087146c83c7215)

we added administrators to the database, to the "permissions" tab, now it does not work as before, we updated qb-core an hour ago, if I'm not mistaken, you fixed it through the webadmin panel, we have always worked with the database. Now do I need to add an administrator in some other way?      
INSERT INTO `permissions` VALUES ('1', '112m', 'license:dad702a5326e3f8a17cd7ea6c8f08cc7d91ad0', 'god');
INSERT INTO `permissions` VALUES ('2', 'John', 'license:70b637725bfe8b5963d29a2ff8e28e3a24613d', 'god');

**Comment by BerkieBb** [comment]
The database is not used anymore

**Comment by BerkieBb** [comment]
It goes through ace permissions now, you need group.admin to get the highest permission (aka god) and then you can use /addpermission to give others permission

**Comment by next-game** [comment]
> It goes through ace permissions now, you need group.admin to get the highest permission (aka god) and then you can use /addpermission to give others permission

thanks for the clarifications, we checked it worked

**Comment by CodeRedDev** [comment]
If you're interested in using the old permissions system with the database checkout my quickfix proposal #593.
