### ISSUE TITLE
[question] hello QBCore!

### ISSUE THREAD

**Issue by Ubeyds0206** [qbcore-framework/qb-core#576]
I know its not a issue, bugg or suggestion. But i got banned cause i was in to many leak servers. I left all of hem. PLS unban me i just wanna get help cause i'm new to qbcore.

My discord: dubayd#9999

**Comment by NoobySloth** [comment]
Presuming you were banned via Warden. Might be best you contact them pal.
https://discord.gg/jeFeDRasfs

**Comment by Ubeyds0206** [comment]
they blacklisted me after i made an appeal what can i do?
