### ISSUE TITLE
[BUG] can't give myself admin

### ISSUE THREAD

**Issue by Ubeyds0206** [qbcore-framework/qb-core#578]
**Describe the bug**
I want to give myself admin permissions i added everything in the permissions table on the database but it still says. can not acces this command.

**To Reproduce**

**Expected behavior**
I should get admin permissions

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [yesterday]
 - Are you using custom resource? which ones? [no]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**

**Comment by balcer64** [comment]
https://github.com/qbcore-framework/qb-core/issues/575

**Comment by Ubeyds0206** [comment]
still not working
