### ISSUE TITLE
not an issue for core (discord)

### ISSUE THREAD

**Issue by Pump-Codes** [qbcore-framework/qb-core#58]
It seems that I have been banned or kicked or something of that sort. I have tried to go back into the server, I get in for one second then kicked immediately. Help

**Comment by Tajemniaczek** [comment]
my tooo

**Comment by capocsgo** [comment]
You guys got busted by Warden for having connection with leak discord servers. Sorry to hear

**Comment by olegend965** [comment]
So what if I have connections wiht leak discord servers .. I'm trying to make my server a better place for my community ...

And its funny .. I only got 1 leak discord on my discord, and im there just becauese my friend told me to check esx_identity, and now I can't get in qbcore discord cuz of that, lul : )
