### ISSUE TITLE
[ERROR] After updating to 1.1.0

### ISSUE THREAD

**Issue by idrp** [qbcore-framework/qb-core#583]
I am getting these errors.
The files with errors are QB Core with out edits.
![coreerror](https://user-images.githubusercontent.com/88186466/160058233-60d51f10-adb5-46a4-8f4b-0f057b8ab9f8.png)

**Comment by D40G** [comment]
check your shared items.lua, it seems as though you missed a comma somewhere or have a typo in that file. all those errors in different scripts are all pointing to the same table

**Comment by idrp** [comment]
Ok will do
