### ISSUE TITLE
login it gets Stuck on "qb-core: Hello Merius. We are checking your allowance."

### ISSUE THREAD

**Issue by MeriusTz** [qbcore-framework/qb-core#584]
I just run my first qbcore server usin txAdmin and everytime i try to login it gets Stuck on "We are checking your allowance"
I tried to re install it with recent tutorials and it keep gettin the same issues.

**Comment by MeriusTz** [comment]
I re installed it again but changin db password it seem to work now ;)

**Comment by BIGMANFATJOE** [comment]
whats the db password im having this same problem and i cant figure it out
