### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DannysRP** [qbcore-framework/qb-core#586]
**Description:**
Testing latest **qb-core** update with latest **qb-garages**. When pulling out a damaged vehicle I am presented with an error. This is mainly based around the **SetVehicleDoorBroken** native. This seems to happen if I store a vehicle that has had it's doors broken off. The error will only happen after the vehicle is pulled out of the garage.

**Steps to reproduce the behavior:**
1. Grab a owned vehicle, break the doors off.
2. Store it in the garage (no problem)
3. Take it out of the garage
4. Received this error unless the vehicle is fixed.

**What is the expected behavior:**
Retrieve the vehicle with no errors and proper damage

**Screenshots**

**Code from qb-core/client/functions.lua:**
![image](https://user-images.githubusercontent.com/88177315/160178189-3e786d23-240e-4d5c-a90b-87f824ff64fc.png)

**Code from qb-garages/client/main.lua:**
![image](https://user-images.githubusercontent.com/88177315/160178029-c062aee6-fef0-4e84-8ab1-76f4b864de49.png)

**Code from qb-core/client/events.lua:**
![image](https://user-images.githubusercontent.com/88177315/160178644-63524f09-4a62-4b4c-9d8d-e0055d6ab90d.png)

**Screenshot in game:**
![image](https://user-images.githubusercontent.com/88177315/160177971-1f123418-2da3-4ca8-90d8-e2a299c1afb5.png)

**Questions (please complete the following information):**
 - When you last updated: Yesterday both qb-garages and qb-core for testing
 - Are you using custom resource?: Not with these resources
 - Have you renamed `qb-` to something custom?: No

**Comment by DannysRP** [comment]
Still experiencing this issue with tests

**Comment by jnccloud** [comment]
> Still experiencing this issue with tests

Try changing `qb-core/client/functions.lua:675` to this:

```lua
SetVehicleDoorBroken(vehicle, tonumber(doorIndex), true)
```

**Comment by DannysRP** [comment]
@jnccloud This fixed the issue I was having but now when the vehicle is fixed the doors are still missing. Body shows as 1000 in the DB

**Comment by jnccloud** [comment]
I'm not 100% positive on this but I think the function in qb-garages (doCarDamage(), client/main.lua) is interfering with this. I commented everything in that function and it seems to work for me but I just started testing this today as well.

**Comment by Rav3n95** [comment]
Are you using qb-core 1.1 version?

Im still using 1.0, on 1.1 vehicle prop saving are changed. Propably that's causing the issue. There is only one know bugs on my pr, the windshield pop out not updated when you repair.
