### ISSUE TITLE
admin still not working

### ISSUE THREAD

**Issue by vvnino** [qbcore-framework/qb-core#589]
Admin permissions are disabled upon flying out. When regiven to admins it disables chat box and emotes

**Comment by BerkieBb** [comment]
Try the new permissions system which just got pushed

**Comment by sebastianqntnll** [comment]
> Try the new permissions system which just got pushed

where is this new persmission system?

**Comment by BerkieBb** [comment]
In qb-core

**Comment by sebastianqntnll** [comment]
> In qb-core

i cant find it can you name de location?

**Comment by nullvariable** [comment]
> > In qb-core
> 
> i cant find it can you name de location?

you need to update to the latest release: https://github.com/qbcore-framework/qb-core/releases

**Comment by nullvariable** [comment]
Also you'll need to update your server.cfg like this:
https://github.com/qbcore-framework/txAdminRecipe/blob/3840defa89a45118e8528168bf9670888a0710bc/server.cfg#L92

full details can be found here: https://discord.com/channels/831626422232678481/852748355838410762/958862662396174347

**Comment by BerkieBb** [comment]
> > > In qb-core
> > 
> > 
> > i cant find it can you name de location?
> 
> you need to update to the latest release: https://github.com/qbcore-framework/qb-core/releases

The latest release is not the latest version, the latest release currently (1.0.0) is an old version which still uses the database for permissions

**Comment by BerkieBb** [comment]
So download the source code instead, it's stable

**Comment by nullvariable** [comment]
> > > > In qb-core
> > > 
> > > 
> > > i cant find it can you name de location?
> > 
> > 
> > you need to update to the latest release: https://github.com/qbcore-framework/qb-core/releases
> 
> The latest release is not the latest version, the latest release currently (1.0.0) is an old version which still uses the database for permissions

ah, my bad, thanks for correcting that

**Comment by elmschaym** [comment]
still not working after
