### ISSUE TITLE
[BUG] No such export GetCoreObject in resource qb-core

### ISSUE THREAD

**Issue by W0lv3sxD** [qbcore-framework/qb-core#590]
**Describe the bug**
There are several Script errors on a fresh install. It says "citizen:/scripting/lua/scheduler.lua:867: No such export GetCoreObject in resource qb-core"

**To Reproduce**
Startup the FXServer

**Expected behavior**
I expected it to start without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/93610323/160290281-0dc30e88-c7c3-43c9-9acf-e6b0ac4c3af8.png)
![image](https://user-images.githubusercontent.com/93610323/160290295-4f58e480-1379-46be-915c-1ec1c1c05c2c.png)
![image](https://user-images.githubusercontent.com/93610323/160290306-b50f59ab-8ccf-446f-8026-cfd8d8c775ce.png)

**Questions (please complete the following information):**
 - When you last updated: Everything was downloaded freshly today.
 - Are you using custom resource? Which ones?: I dont use any custom resources. Only the ones that were in the Recipe.
 - Have you renamed `qb-` to something custom?: No I did not.

**Additional context**
I hope to get fast help from y'all.
Thanks in advance.

**Comment by BerkieBb** [comment]
Make sure qb-core is updated
Make sure qb-core is started
Make sure qb-core is started without error

**Comment by W0lv3sxD** [comment]
Found the issue. QB-Core has to be the very first resource started.

**Comment by CashTrouble** [comment]
i have the same issue how do i fix it?

**Comment by UnboundGodz** [comment]
> i have the same issue how do i fix it?

Although you probably nolonger require the help, add "ensure qb-core" to your server.cfg first. It must be first. This can resolve alot of those GetCoreObject errors.
