### ISSUE TITLE
qb core- allowence screen stuck

### ISSUE THREAD

**Issue by Juu0** [qbcore-framework/qb-core#591]
![Screenshot 2022-03-27 221218](https://user-images.githubusercontent.com/102496654/160315323-2f95e01a-dfda-48f3-a88d-9d8986b515f7.jpg)

I don't know what is causing this, but i checked all the permissions and license files but nothing. I even checked the SQL file went into the ban database etc but still couldn't fix this issue.

**Comment by robnbie99** [comment]
Having this issue as well, do not know how to fix the issue

**Comment by BerkieBb** [comment]
Nothing in the server console and/or F8?

**Comment by secretdk** [comment]
Have the same issue :\

**Comment by Juu0** [comment]
> Having this issue as well, do not know how to fix the issue

I found a fix. What I did was just delete the entire code in the section that contains the allowance verification. After that I was able to get to my server with qb core working fully functional.

**Comment by izMystic** [comment]
> > Having this issue as well, do not know how to fix the issue
> 
> I found a fix. What I did was just delete the entire code in the section that contains the allowance verification. After that I was able to get to my server with qb core working fully functional. I believe it’s located it the shared folder inside of ab core/players/then the code should be there just scroll down until you see anything related to “checking allowance” 

That's not a "fix", that's a remove the problem
