### ISSUE TITLE
Permission Tree

### ISSUE THREAD

**Issue by CodeRedDev** [qbcore-framework/qb-core#592]
**Is your feature request related to a problem? Please describe.**
Some servers require a levelled support hierarchy for special cases where e.g project leaders are not involved in. Moderators or supporters should have a more restricted selection of commands. Unfortunately the new permission system does only support `admin` / `god` or `user`.

**Describe the feature you'd like**
The new permission system should support adding several groups into the permission tree. E.g.:

```
add_principal identifier.fivem:xxxxxxxxx group.mod
add_principal identifier.fivem:xxxxxxxxx group.support
```

**Additional context**
The login algorithm does not pay attention to already set permission groups in `QBCore.Player.CheckPlayerData()`

**Comment by GhzGarage** [comment]
Would like your input https://github.com/qbcore-framework/qb-core/pull/594

**Comment by BerkieBb** [comment]
This has been added with the permissions system linked above this message
