### ISSUE TITLE
Stuck on a loading screen after character creation!

### ISSUE THREAD

**Issue by Ocean-19** [qbcore-framework/qb-core#60]
**Hi,** I have a problem where my server gets stuck on a loading screen that, turns and turns when you press "Create Character" in the starting menu. I have restarted my server and my FiveM, but nothing has fixed it. 

You can either respond here or you can message my discord: **_Ocean# 0130._**
Thanks.

https://user-images.githubusercontent.com/67462632/126367962-4da78cb9-4a2d-47ab-aded-e2cf62036547.mp4

**Comment by Tajemniaczek** [comment]
You have to wait for everything to load. If you are on the premises, it will take a while. Change the view settings of the download: P
