### ISSUE TITLE
[ Vehicle Mod Neon Not saving ]

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-core#602]
**Describe the bug**
Vehicle mod neon color not saving 

**Screenshots**
after mod
![image](https://user-images.githubusercontent.com/55808925/160580158-6b0d08fb-b997-4ffd-ae23-c21cc2ec02a3.png)

after take out from garage
![image](https://user-images.githubusercontent.com/55808925/160579310-35f4e3dc-ac0c-42b6-9ea7-990cf59a3978.png)

**Questions (please complete the following information):**
 - 10 mins ago cuz i have  server running i was updating and noticed neon not saving then i downloaded fresh recipe and double check that

 - qb-target by default 
 - Have you renamed `qb-` to something custom? [no]

**Comment by BerkieBb** [comment]
Have you updated qb-core?

**Comment by ItsANoBrainer** [comment]
update core
