### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by suryabhaiin** [qbcore-framework/qb-core#605]
Bug in RemoveItem function in qb-core/server/player.lua file

**Comment by BerkieBb** [comment]
That will be fixed in qb-inventory, should already be fixed actually on the dev branch of qb-inventory

**Comment by suryabhaiin** [comment]
> That will be fixed in qb-inventory, should already be fixed actually on the dev branch of qb-inventory

i reinstalled server but still this bug exist in qb-inventery and qb-core. this is major bug. because if some one did this the he get unlimited item with 0 weight.

**Comment by BerkieBb** [comment]
The dev branch doesn't automatically get installed with the recipe
