### ISSUE TITLE
Server log in-game [BUG]

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-core#610]
**Describe the bug**
Added an image, seems like server log is turned on. to post in city. intended or a option I can turn off. thanks.

**To Reproduce**
So say I go to a shop. I use use my 3rd eye to get a snack, that action is reported in the server, server log. but with this new update it also posts in the city, as you can see from my image, 

**Expected behavior**
not to post the server, log actions in city.

**Screenshots**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/7rGDhJh/set.png" alt="set" border="0"></a>
**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? [e.g. qb-target]
 - Have you renamed `qb-` to something custom? [e.g. no]

**Additional context**

"/-playerFocus" tends to be posted in the server/server logs. not in the city, can this be turned off.

**Comment by BerkieBb** [comment]
Your description of the bug and the screenshot don't match, could you please edit your message and fill in the rest of the fields and give more details?

**Comment by BerkieBb** [comment]
That might be something from your chat

**Comment by Andyauk** [comment]
> That might be something from your chat

this could be true, but its never done it since the latest version of qb-core. but its worth looking at I guess.

**Comment by Andyauk** [comment]
> That might be something from your chat

no, not my chat. I tried it with a fresh server, still the same. 
something in qb-cure, is posting this message. must be a false somewhere. 

<a href="https://ibb.co/x8sDf8s"><img src="https://i.ibb.co/tPh4xPh/Untitled.png" alt="Untitled" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>image upload site</a><br />

**Comment by GhzGarage** [comment]
I will add some code which prevents this from happening

**Comment by Andyauk** [comment]
> I will add some code which prevents this from happening

PS keep up the great work./ x

**Comment by Andyauk** [comment]
> I will add some code which prevents this from happening

this issue went, but now its back. not sure what happened/

**Comment by TheOldHook** [comment]
how did you fix ? we have problems on our server with this issue after updating to lates version.

**Comment by Andyauk** [comment]
> how did you fix ? we have problems on our server with this issue after updating to lates version.

The -engine one, not fixed yet I don't think. As not been on today, but the playerFocus was fixed though qb-menu update.

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-core/pull/613
This should fix it

**Comment by Andyauk** [comment]
> #613 This should fix it

I did see that, wasn't sure if it would be what were after. I'll try it later thanks buddy

**Comment by MadManDanCat** [comment]
this fixed it not showing up in the chat however it still highlights the chat box which is really annoying

**Comment by MadManDanCat** [comment]
So everytime you use target or showui export it will just bring up the chat but not actually put anything in there

**Comment by BerkieBb** [comment]
You should comment that on that pull request

**Comment by MadManDanCat** [comment]
> You should comment that on that pull request

I don't know where the pull request is im new to github yesterday.

**Comment by BerkieBb** [comment]
The one with the fix

**Comment by Andyauk** [comment]
> The one with the fix

They did it I see, so will wait to see if a suggestion. Fix
