### ISSUE TITLE
[      script:qb-core] SCRIPT ERROR: @qb-core/server/main.lua:29: attempt to get length of a nil value (field 'AllPermissions')

### ISSUE THREAD

**Issue by DamziDDK** [qbcore-framework/qb-core#612]
anyone tell me what to type in the server.cfg?

**Comment by BerkieBb** [comment]
From that script error you don't seem to have updated the config of qb-core

**Comment by DamziDDK** [comment]
> 

im using the latest qb-core update, but i see is still in WIP :/

**Comment by GhzGarage** [comment]
Why you asking what to type in the config if you can just check the config right here on GitHub?

**Comment by DamziDDK** [comment]
> Why you asking what to type in the config if you can just check the config right here on GitHub?

i know the config is here, but i need some more im not the best dev, but ill just w8 for the finish product :)

**Comment by GhzGarage** [comment]
It is finished

**Comment by DamziDDK** [comment]
> It is finished

well im getting that error but after i used this one `QBCore = {}
QBCore.Config = QBConfig
QBCore.Shared = QBShared
QBCore.ServerCallbacks = {}
QBCore.UseableItems = {}

exports('GetCoreObject', function()
    return QBCore
end)

-- To use this export in a script instead of manifest method
-- Just put this line of code below at the very top of the script
-- local QBCore = exports['qb-core']:GetCoreObject()` i can't use the adminmenu anymore.

**Comment by DamziDDK** [comment]
My question is just what to type insinde the server.cfg to get the permission :)
