### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rcl1y48** [qbcore-framework/qb-core#615]
Hello so I am having issues with adding myself to the QbCore Admin, I cannot add myself for some reason.  I have asked so many people and no help what so ever. 

Any help would be greatly appreciated!!

![Permissions mysql](https://user-images.githubusercontent.com/88553010/161395545-d6cf06d7-e78a-405d-b4cf-512ec9062b92.png)
![txadmin](https://user-images.githubusercontent.com/88553010/161395576-49ba9991-60d3-40e0-b7db-a8065fb43f85.png)

**Comment by rcl1y48** [comment]
I cannot find the permissions area in mysql to add myself to qbcore admin.

**Comment by dusan01** [comment]
Permissions were removed from the database after the new update.
There is more info about that in Discord, in the #set-permissions channel

**Comment by rcl1y48** [comment]
I do not have the new discord link for qbcore, so I am unable to join.

**Comment by dusan01** [comment]
https://discord.gg/qbcore

**Comment by GhzGarage** [comment]
what new discord link?

**Comment by rcl1y48** [comment]
> https://discord.gg/qbcore

Won't allow me to join for some reason, can u post what it says in here?

**Comment by rcl1y48** [comment]
It says the invite link is invalid

**Comment by dusan01** [comment]
![m0kXDCHsKh](https://user-images.githubusercontent.com/7904473/161395991-368ce5a5-b012-47fb-81ce-0fdf0e2908e8.png)

**Comment by Soldierofthelam** [comment]
I've been all through the discord there is no information I can find about where to set god mode in permissions

**Comment by EthanPendowski** [comment]
> I've been all through the discord there is no information I can find about where to set god mode in permissions

The way you set god is in the CFG file.
