### ISSUE TITLE
[BUG] with /-engine appearing in chat log

### ISSUE THREAD

**Issue by Monkey1995** [qbcore-framework/qb-core#616]
when ever someone hits y no matter if they are in a car or not it put /-engine in the chat log? not sure if this is meant to do this or not but in previous builds i haven't seen this before 
![image](https://user-images.githubusercontent.com/98919002/161439963-8d2ad21b-c0b3-49bf-a815-86f57cfe56d4.png)

**Comment by smoke8989** [comment]
Same with me. (It's G for me) It is the same key I use to turn engine on and off, but I also get /-engine everytime I press the key no matter if I am in car or not. Been looking for a fix.

**Comment by instigate77** [comment]
Same, people spam it now and fill up chat, need a fix!!!

**Comment by Monkey1995** [comment]
ive fixed it but i'm actually unsure how if im honest with you... im now trying to work out what i have done to sort it, ill keep you updated

**Comment by instigate77** [comment]
I used this fix in qbcore, it's not in the main branch yet, but worked for me...
https://github.com/qbcore-framework/qb-core/pull/613/commits/aab215334f0b82a2fa5b5901dcde53ddfdf57d8e

**Comment by Andyauk** [comment]
> I used this fix in qbcore, it's not in the main branch yet, but worked for me... [aab2153](https://github.com/qbcore-framework/qb-core/commit/aab215334f0b82a2fa5b5901dcde53ddfdf57d8e)

qb-menu fixes one of the messages, but the link you posted does work,. but when you press G it shows last messages. try it, /ooc hi then wait for it to go. then press G it will pop up the chat. but its ok for now.
