### ISSUE TITLE
[BUG] Script Error Citizen/scripting/lua/Scheduler:867: No such export HideText in resource qb-core

### ISSUE THREAD

**Issue by Harley2787** [qbcore-framework/qb-core#618]
Log into the server:
[BUG] Script Error Citizen/scripting/lua/Scheduler:867: No such export HideText in resource qb-core
error is there!

**Comment by Harley2787** [comment]
![image](https://user-images.githubusercontent.com/83428883/161790823-fc34ddea-57fe-417b-bd39-04c246d59e30.png)

**Comment by DevilJackttv** [comment]
If you installed qbcore 1.0.0 it doesn't include the drawtext.lua which u need for Hidetext. Download the earlier version and take the drawtext.lua and place it in your qbcore -> client folder

**Comment by ItsANoBrainer** [comment]
Update qb core to latest version.
