### ISSUE TITLE
Position is not saved correctly in database

### ISSUE THREAD

**Issue by iglesiiaskeviin** [qbcore-framework/qb-core#619]
For any reason when i join and exit server my coords are not saved correcly and appear like that in database position table:

{"x":0.0,"y":2.035092233620972e-10,"z":NaN}

**Comment by roobr** [comment]
I believe this is to do with onesync not being enabled correctly!

Just tested it on my server
<img width="512" alt="image" src="https://user-images.githubusercontent.com/9066749/162102820-9296d33d-12e6-4e97-ac9f-1b9c32f2d2cf.png">

please try do 

`+set onesync on` in your run.bat or enable it through txadmin

**Comment by roobr** [comment]
@IdrisDose Give me lead dev now thanks
