### ISSUE TITLE
[BUG] drawtext.lua (cilent folder) file not included in latest qbcore 1.0.0 file

### ISSUE THREAD

**Issue by DevilJackttv** [qbcore-framework/qb-core#626]
Hi, so basically when you guys updated the qbcore to 1.0.0 and uploaded it you guys didnt include drawtext.lua which includes the HideText() which is causing people to have a lot of issues when updating. Picture below shows that its in the older version but not the newer one would be really helpful if you guys fixed this ASAP 
![unknown](https://user-images.githubusercontent.com/101954029/162547931-cb294e5e-691c-4cd3-8d63-071212882f90.png)

**Comment by GhzGarage** [comment]
It’s called 1.0.0 for a reason, it’s the old version

**Comment by DevilJackttv** [comment]
![image](https://user-images.githubusercontent.com/101954029/162548011-036aaffe-9f4a-4ea3-8e69-c64529bfe5e0.png)
Why is it labeled as newest version and uploaded 17 days ago?

**Comment by DevilJackttv** [comment]
That there makes people download it bc we think its the newest version bc it says "Latest"

**Comment by GhzGarage** [comment]
It’s just a release for those who didn’t want to update

**Comment by DevilJackttv** [comment]
Ok
