### ISSUE TITLE
[TURBO MOD NOT STICKING ON Vehicle]

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-core#627]
**Describe the bug**
Few days ago i was testing vehicle mods on a freash qbcore server so on that time neon was not working as per as i noticed and after few days there was a bug with a turbo mods too turbo also not working 
**To Reproduce**
1. Go to 'qb-customs and try apply turbo any any veh apply it leave the customs menu and put it back will see turbo need to buy again ' 

**Expected behavior**
Turbo mods need to be shown as purchased

**Questions (please complete the following information):**
 - When you last updated: [last week when qbcore-framework updated the client functions file ]
 - Are you using custom resource? [no]
 - Have you renamed `qb-` to something custom? [no]

**Comment by nullvariable** [comment]
I can verify this issue exists for me in the latest version. This issue should be moved to the `qb-customs` repository: https://github.com/qbcore-framework/qb-customs/issues

**Comment by ARSSANTO** [comment]
Its fixed now can be closed
