### ISSUE TITLE
[BUG]Seems like there no Hebrew language in the "/me" chat command

### ISSUE THREAD

**Issue by dvaturi** [qbcore-framework/qb-core#631]
Hi,
I am having an issue with one of my chat commands, actually, it's "/me"
when I am trying to type something in the Hebrew language it just shows squares on the screen.
when I am using different chat command it actually works, and I can see Hebrew
I am adding a picture of the command 
![image](https://user-images.githubusercontent.com/57751780/163034930-45998936-7c11-489e-9276-282defa561a6.png)
and its outcome
![image](https://user-images.githubusercontent.com/57751780/163034995-49e90125-bd93-482b-8692-a558c19e0203.png)
thanks in advance

**Comment by izMystic** [comment]
The font type doesn't allow it then
https://github.com/qbcore-framework/qb-core/blob/main/client/events.lua#L192

**Comment by dvaturi** [comment]
> The font type doesn't allow it then https://github.com/qbcore-framework/qb-core/blob/main/client/events.lua#L192

so what do I need to change in order to make it work? please help

**Comment by dvaturi** [comment]
@izMystic is there a way to solve this?
