### ISSUE TITLE
Missing trigger in multiply scripts that use this trigger.

### ISSUE THREAD

**Issue by MaDHouSe79** [qbcore-framework/qb-core#642]
the missing trigger in the framework
```lua
TriggerEvent('qb-policealerts:client:AddPoliceAlert', {
                timeOut = 10000,
                alertTitle = "Pacific Standard Bank robbery attempt",
                coords = {
                    x = coords.x,
                    y = coords.y,
                    z = coords.z,
                },
                details = {
                    [1] = {
                        icon = '<i class="fas fa-university"></i>',
                        detail = bank,
                    },
                    [2] = {
                        icon = '<i class="fas fa-video"></i>',
                        detail = "1 | 2 | 3",
                    },
                    [3] = {
                        icon = '<i class="fas fa-globe-europe"></i>',
                        detail = "Alta St",
                    },
                },
                callSign = QBCore.Functions.GetPlayerData().metadata["callsign"],
            })
            ```
            it is in more scripts but this trigger does not exsist.

where is this trigger registered cause i cant find it?

**Comment by izMystic** [comment]
no where, it was removed for a different system, use 

TriggerServerEvent('police:server:policeAlert​'​, ​'Message you want'​)

**Comment by MaDHouSe79** [comment]
but this code i post here is al over my other code... i did not put it there, it was already there,
but this hole trigger is not exsist... and the trigger you say is not the same with al the parameters init, cause its an arrat table that is put in as data and not a single text sting.

**Comment by izMystic** [comment]
qb-policejob has that code in it, the one you posted was removed for the one I posted

**Comment by MaDHouSe79** [comment]
ok but why is it in all other code still there? houserobberies bank heist also use that trigger
