### ISSUE TITLE
Cannot get past "We are checking your allowance"

### ISSUE THREAD

**Issue by lvto2000** [qbcore-framework/qb-core#644]
I cannot get past the, "We are checking your allowance" screen.  I have rebuilt the server several times from scratch.  I have tweaked the whitelist and queue settings.  I have turned them all off.  The only thing that works is if I start the server without QBCORE.  Then I connect perfectly.

**Comment by JajarGaming** [comment]
Probably an SQL problem. Check your SQL connection settings and server side errors

**Comment by BIGMANFATJOE** [comment]
how do i check sql settings im new to this stuff

**Comment by Many-Cuba** [comment]
I have the same issue

**Comment by alfonsoiriarte** [comment]
Make sure you have your XAMPP turned on (apache and mysql), then log in to txAmin, then open Fxserver (or whatever you use).

**Comment by Tamer173** [comment]
![image](https://user-images.githubusercontent.com/105336574/176995203-99a17987-673d-435c-b869-cfbe6122f17c.png)
The above name of your server should match The one with the newly Created Database or the one you replaced for example check-in your heidi Sql as shown below 
![image](https://user-images.githubusercontent.com/105336574/176995259-f684444f-fd5c-43b2-b2ae-40b82550a344.png)
Note Capital Letters Should be used.
