### ISSUE TITLE
walk style

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-core#65]
I love your project, that's why I offer suggestions
But you have deleted the following from the main version
It was there, but it wasn't working
It memorizes the way of walking
Even when off the server
It returns to the same way of walking

PlayerData.metadata["walk"] = PlayerData.metadata["walk"] ~= nil and PlayerData.metadata["walk"] or "reset"

**Comment by BerkieBb** [comment]
We don't have it because we don't have our own system for saving this so it was useless
