### ISSUE TITLE
[BUG] QBShared not being updated client side for new clients

### ISSUE THREAD

**Issue by mmoftah** [qbcore-framework/qb-core#651]
**Describe the bug**
When updating QBShared through a function like `QBCore.Functions.AddJob` the code updates the server side QBShared, and all existing clients' QBShared. If a new client connects, they do not have that update.

**To Reproduce**
1. Write a script that calls `QBCore.Functions.AddJob`
2. Printing client side the `QBCore.Shared.Jobs` table will show you this new job.
3. Disconnect + reconnect. Printing the client side `QBCore.Shared.Jobs` table will not have the new job.

**Expected behavior**
It is expected that all clients will get this new job in their `QBCore.Shared.Jobs` table even if they connect after the call was made.

**Questions (please complete the following information):**
 - When you last updated: Used the recipe to create a new server as of about a week ago
 - Are you using custom resource? which ones? No, vanilla build
 - Have you renamed `qb-` to something custom? no

**Comment by BerkieBb** [comment]
You have to update it manually by listening to the event called by that function

**Comment by BerkieBb** [comment]
QBCore:Client:OnSharedUpdate

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-core/blob/main/server/exports.lua#L12

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-core/blob/main/client/events.lua#L218

**Comment by mmoftah** [comment]
As I said, this is for existing clients. If a new client connects, then the updated shared is not there

**Comment by BerkieBb** [comment]
Where do you check if the new job exists or not?

**Comment by mmoftah** [comment]
Anywhere client side after a new connection it will not exist in `QBCore.Shared.Jobs`, but it will server side

**Comment by erikmeyer08** [comment]
What happens if the clients clear there cache?

**Comment by mmoftah** [comment]
This has nothing to do with cache, it's the fact that the QBShared object client side is only updated when the change is made server side. If the change is made before a connection, that client gets the default QBShared object, not the updated one.

**Comment by Xerrass** [comment]
im Having the same problem i think, any update on this?
