### ISSUE TITLE
[BUG] SetVehicleDoorBroken?

### ISSUE THREAD

**Issue by NoobySloth** [qbcore-framework/qb-core#653]
**Describe the bug**
Well, only getting an error and the photo shows that

**To Reproduce**
Uh, yeah idk? Break doors, store car and take it out again?

**Expected behavior**
Doors to be broken I guess?

**Screenshots**
![image](https://user-images.githubusercontent.com/6962192/164498388-a660a7e2-1e4c-428a-983d-ba0a86a7af58.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 16 days ago
 - Are you using custom resource? which ones? https://github.com/JonasDev99/qb-garages
 - Have you renamed `qb-` to something custom? no

**Additional context**
I see in the garage script it also handles door damage but yeah im not sure? sorry for the terrible bug report.. I only have an error to go off

**Comment by nullvariable** [comment]
Best guess here is that the call from the 3rd party garage library is not sending back the same formatted object as what QBCore is using.

You can test this by modifying the garage library here:
https://github.com/JonasDev99/qb-garages/blob/main/client/main.lua#L527
change the line above this to:
```
properties.doorStatus = nil
```
Then test and see if the error is gone or a new error occurs. If the error is gone, there is a problem with the custom resource and it will need to be updated to pass that data in to QBCore correctly.

**Comment by 19adorest** [comment]
> Best guess here is that the call from the 3rd party garage library is not sending back the same formatted object as what QBCore is using.
> 
> You can test this by modifying the garage library here: https://github.com/JonasDev99/qb-garages/blob/main/client/main.lua#L527 change the line above this to:
> 
> ```
> properties.doorStatus = nil
> ```
> 
> Then test and see if the error is gone or a new error occurs. If the error is gone, there is a problem with the custom resource and it will need to be updated to pass that data in to QBCore correctly.

not working.

**Comment by 19adorest** [comment]
> 

this is what happen after i try to set this **SetVehicleDoorBroken(vehicle, tonumber(doorIndex), true)**
[](https://streamable.com/phkecl)

**Comment by 19adorest** [comment]
> Alter line 650 in functions.lua so that it shows tonumber(doorIndex) instead of just doorindex.
> 
> Old/Busted: SetVehicleDoorBroken(vehicle, doorIndex, true) New/Not Busted: SetVehicleDoorBroken(vehicle, tonumber(doorIndex), true)

this is what happen after i try to set **SetVehicleDoorBroken(vehicle, tonumber(doorIndex), true)**
[https://streamable.com/phkecl](url)
