### ISSUE TITLE
qbcore stuck on loading screen

### ISSUE THREAD

**Issue by JimSta32** [qbcore-framework/qb-core#673]
I have had an issue now where I am stucking just loading in after using the multicharacter selection. Now, I left my pc on all night attempting to see if it would actually load in by waiting but it didn't do anything. I am also very new to developing a fivem server so this is a bit of a struggle to me to fix. I have fixed a few things in the past but this is one thing I have been unable to.

If anything knows how to fix this please either reply to this or dm me on Discord:
 
Jimmy Bald#8494

Thankyou.

**Comment by FrogCF** [comment]
Hi, 

This was known bug was fixed in the latest update, please follow the doc on here : https://github.com/qbcore-framework/qb-core/issues/604

**Comment by JimSta32** [comment]
> 

Thanks, mate. This has helped me out
