### ISSUE TITLE
[BUG] Spawning as Random Ped

### ISSUE THREAD

**Issue by SantyR0** [qbcore-framework/qb-core#688]
**Describe the bug**
When joining my server I get spawn as a random ped for like 5 seconds sometimes longer sometimes shorter and then after that I can choose which character I will play. What could cause this? I just got the latest qbcore setup from txadmin.

Also happens sometimes after choosing a character, it becomes a random ped for 1 sec and goes back to my character.

**To Reproduce**
1. Go to 'server folder'
2. Click on 'start.bat from txAdmin'
3. Use this item '....' (item's name from shared.lua if applicable) -----

**Expected behavior**
Hoping to get to character selection without this bug.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/96814650/167172517-7b58cbbf-29a7-4096-85c8-3a00a963eccf.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]; May 4, 2022.
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] All of my resources comes with the recipe from txAdmin
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No. This already occurs before I added few new scripts.

**Additional context**
Tried to have a fresh copy from recipe (which is from popular template) but still having this bug. If it helps, I tried search "random ped" on qbcore's discord. I have same guys who's having the same bug as me. 

Not mine but like this:
https://streamable.com/kxes0c

**Comment by JericoFX** [comment]
please use the template to create a bug.

**Comment by SantyR0** [comment]
Hello. Sorry, I updated it my post into the template.

**Comment by SantyR0** [comment]
Hello. I recorded the issue that I'm experiencing, hoping to have a solution or to make it more clearer.
https://streamable.com/w4yxuo

**Comment by jennibeaver** [comment]
i am also having this issue. is there a fix?

**Comment by DubdieD** [comment]
Bump 😅

**Comment by WesFillings** [comment]
Check your console for errors, see if all scripts are launching correctly, ensure you have the correct load order for qb resources. If that is all good open your Database and ensure you executed the correct SQLs for your resources. @SantyR0

**Comment by GhzGarage** [comment]
This behavior is normal at the moment until we update it in multi-character
