### ISSUE TITLE
some ques

### ISSUE THREAD

**Issue by Dyumessi10** [qbcore-framework/qb-core#70]
**How to set yourself up as an admin，I can't wokr with it**，
I already set this：
![image](https://user-images.githubusercontent.com/64605693/126968112-222784c4-c889-4c02-af47-9d36ed687c4c.png)

**Comment by BerkieBb** [comment]
QBCore doesn't work with cfg permissions (cfg permissions only enable commands like /ensure), it has it's own permissions system that uses the database, join the discord and see the #set-permissions channel https://discord.gg/qbcore
