### ISSUE TITLE
[BUG] attempt to index a nil value (global 'QBCore')

### ISSUE THREAD

**Issue by cezeulor** [qbcore-framework/qb-core#708]
Trying to put a new vehicleshop to my server I got this error and I can not find the problem

![Error](https://user-images.githubusercontent.com/106556095/171051085-11b7e6b4-2bfe-48b6-9e99-132a316db8e2.PNG)
![Code](https://user-images.githubusercontent.com/106556095/171051086-3cf796ac-5800-424d-baf2-fe376ced264b.PNG)
m

**Comment by Newtonzz** [comment]
This isn’t an issue with the core resource but rather your resource missing the correct export.

Add to both client & server file at the top 
`local QBCore = exports['qb-core']:GetCoreObject()`

If other issues come up please refer to the author of the resource.

**Comment by cezeulor** [comment]
> This isn’t an issue with the core resource but rather your resource missing the correct export.
> 
> Add to both client & server file at the top `local QBCore = exports['qb-core']:GetCoreObject()`
> 
> If other issues come up please refer to the author of the resource.

THX SO MUCH
