### ISSUE TITLE
Why remove steam?

### ISSUE THREAD

**Issue by dulkith** [qbcore-framework/qb-core#71]
I want to know why remove steam id save

**Comment by RadhwaneDZ** [comment]
i think its very bad idea to remove the steam from qbcore , why ? some players using same rockstar account so when they join to a specified server they will registred in PLAYERS table with same rockstar license 
player A enter the game and register his character and he logout 
player B have same account as player A and when he login to same server he will not register his character but Player A character will appear on the screen even CITIZENID are different 
so we need a solution to prevent using same rockstar license 
if player A login and register his account 
another player with same rockstar license when joined the core must check if the license already exsist on database or not 
if same license found he cannot join until he login to another rockstar account

**Comment by GhzGarage** [comment]
Steam is an old unneeded practice and the duplicate rockstar license issue has been solved
