### ISSUE TITLE
[BUG] Menu interaction (LSC, custom Scripts) only with left mouse button

### ISSUE THREAD

**Issue by jvmpman** [qbcore-framework/qb-core#710]
**Describe the bug**
For example when I want to select a tuning category inside the LSC menu, I cant confirm with enter. I always have to press left mouse button, even I am navigating with arrow up and down. This becomes a problem when using a custom script, because I have to navigate through the menu while driving or while on foot. When I confirm with left mouse button, I accidentally shoot or hit people around me. Is it possible to change the "select" key from mouse button to enter?

**To Reproduce**
I don't know, I think this is standard.

**Expected behavior**
I want my submit button changed to enter.

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? Only MLOs, cars and Police Interaction Script
 - Have you renamed `qb-` to something custom? no

**Comment by ChristianLanctot** [comment]
Any resolution for this? I have same issue
