### ISSUE TITLE
[BUG] Permissions problems

### ISSUE THREAD

**Issue by iglesiiaskeviin** [qbcore-framework/qb-core#711]
## Permissions ##
add_ace group.admin command allow # allow all commands
add_principal identifier.fivem:292***** group.admin #Icep2

# Resources
add_ace resource.qb-core command allow # Allow qb-core to execute commands

# Gods
add_ace qbcore.god command allow # Allow all commands

# Inheritance
add_principal qbcore.god group.admin # Allow gods access to the main admin group used to get all default permissions
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

# Players
add_principal qbcore.god identifier.license:aa*********************************** # Player Name

Im using this config into my server.cfg but when i try to execute a command appear this on my console: Access denied for command noclip.

**Comment by GhzGarage** [comment]
Fix the format
