### ISSUE TITLE
[BUG] Generating phone number

### ISSUE THREAD

**Issue by RavenIL12** [qbcore-framework/qb-core#717]
Go to qb-core/server/player.lua
Click on function QBCore.Functions.CreatePhoneNumber()

error:
trying to generate phone number that starts with "0" but its skips it

Expected behavior:
generate phone number with "0"

Screenshots
![image](https://user-images.githubusercontent.com/106778383/172212557-8dcdc291-50be-4233-8961-23894b8ccffc.png)
![image](https://user-images.githubusercontent.com/106778383/172212666-02d55cb4-f4bc-483a-90e4-409cf7d7eefa.png)

**Questions (please complete the following information):**
 - When you last updated: [two weeks ago]
 - Are you using custom resource? which ones? [qs-smartphone]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
![image](https://user-images.githubusercontent.com/106778383/172212666-02d55cb4-f4bc-483a-90e4-409cf7d7eefa.png)

**Comment by RestrictedNova** [comment]
This should do what you're looking for
`PhoneNumber = '0' .. math.random(52,54) .. math.random(1000000,9999999)`

**Comment by ItsANoBrainer** [comment]
Do what Restricted said.
