### ISSUE TITLE
its just super bad

### ISSUE THREAD

**Issue by Monotoxal** [qbcore-framework/qb-core#719]
needs lots of fixing to update on an older server!

**Comment by JustBlou** [comment]
![image](https://user-images.githubusercontent.com/61672613/173385745-c0ddb9fb-4ab2-4b2b-b48d-894e7ff2ffb3.png)

**Comment by ItsANoBrainer** [comment]
![bye](https://i.giphy.com/media/m9eG1qVjvN56H0MXt8/giphy.webp)
