### ISSUE TITLE
Doors Suggestion

### ISSUE THREAD

**Issue by menkzy** [qbcore-framework/qb-core#73]
In the future, could we get a system like [nui_doorlock](https://github.com/thelindat/nui_doorlock) where you can create a new door on the fly? as opposed to the long and tedious config editing.

**Comment by BerkieBb** [comment]
nui_doorlock is on my github for the moment being, we are currently working on the main resources and making sure they work 100% and later we can migrate some resources and add some new ones

**Comment by GhzGarage** [comment]
Suggestion belongs on https://github.com/qbcore-framework/qb-doorlock
