### ISSUE TITLE
[BUG] Phone contacts still appearing offline after revert

### ISSUE THREAD

**Issue by bruinp8n** [qbcore-framework/qb-core#736]
**Describe the bug**
Phone numbers appearing offline still after the core revert on phone number changes... and any new phone numbers for whatever reason show nil!

**Questions (please complete the following information):**
Is my current database now screwed? is there a way to fix this?

**Comment by Howsn** [comment]
I have the same problem, i hope if this is a db problem it can be fixed. But I have no idea where to look, i havent seen any change in the database.

**Comment by DB00001010** [comment]
Same issue here, I think any body who did the lasts commits got their phone numbers messed up, cannot call or see if the player is online. Can only call through the Services app. It does not appear to be db related

**Comment by Howsn** [comment]
> Same issue here, I think any body who did the lasts commits got their phone numbers messed up, cannot call or see if the player is online. Can only call through the Services app. It does not appear to be db related

How could the phone number be messed up? I dont get it. I have checked the db and everything looks the same.

**Comment by peppinoita** [comment]
Yes right. Delete the phone number from the database and try again

**Comment by Howsn** [comment]
> Yes right. Delete the phone number from the database and try again

Not sure where and what to delete. I tried making 2 new characters, everything works then.
There should be a way to fix the phone numbers again right?

**Comment by Howsn** [comment]
Finally last night I found the solution, I dident wanna delte all the phone mimbers so I found the problem that caused this in the database.

All the phone number that had problem looked like this: "phone":123456789,
They needs to look like this: "phone":"123456789",

I editet all the numbers in the db that had this prolem and the phone works again.

**Comment by peppinoita** [comment]
This can be closed

**Comment by nzkfc** [comment]
@peppinoita why was it fixed?

**Comment by bruinp8n** [comment]
I have over 1000 characters in my database, anyone got a quick solution for fixing this?

**Comment by mhnl3** [comment]
> I have over 1000 characters in my database, anyone got a quick solution for fixing this?
Change the functions.lua and player.lua to set the number tostring until all of your numbers are converted. Then revert the setting back so that you future proof your QBCore.


```
function QBCore.Functions.GetPlayerByPhone(number)
    for src, _ in pairs(QBCore.Players) do
        if QBCore.Players[src].PlayerData.charinfo.phone == tostring(number) then
            return QBCore.Players[src]
        end
    end
```




`    PlayerData.charinfo.phone = tostring(PlayerData.charinfo.phone) or QBCore.Functions.CreatePhoneNumber()`

**Comment by bruinp8n** [comment]
mhnl3 thank you, I did try this once as i thought this might work aswell, and then I had some people strangely still appearing offline on contacts when online... 

Imma try again though maybe i scuffed something originally when I tried, thank you!

**Comment by nzkfc** [comment]
Only need to use the tostring  one in player.lua, run server then you can
replace it back to the latest line and ya goochi
