### ISSUE TITLE
[BUG] Multiple isboss = true on jobs breaks gangs breaks menu

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-core#738]
**Describe the bug**
If you set more then one rank as boss, the gang menu (qb-management) breaks and doesn't appear

**To Reproduce**
1. Set two ranks as boss
2. Restart

**Expected behavior**
Should be able to set any rank as boss (multiple)

**Questions (please complete the following information):**
 - When you last updated: Last week
 - Are you using custom resource? which ones? N/A
 - Have you renamed `qb-` to something custom? No

**Comment by T-Caster** [comment]
Can u screenshot the error if there is any?(in client/server console)

**Comment by nzkfc** [comment]
Oddly what was happening was the menus  and input menus never show up, unless we remove isboss from multiple ranks and just leave it on one.

However I've seen it working before fine with multiple boss ranks, so it might be someone being silly on our side with the adding locations or something. I'll do some more testing.

**Comment by ChatDisabled** [comment]
Can this problem be confirmed and tested again? Or isn't it relevant anymore?

**Comment by nzkfc** [comment]
Can confirm this is now fixed
