### ISSUE TITLE
[BUG] Paychecks not removing money from society money for jobs

### ISSUE THREAD

**Issue by Xdelic** [qbcore-framework/qb-core#740]
**Describe the bug**
I am currently using QB-Core, I have QB-management where i have jobs (example of jobs, Police, UwU, Burgershot, Mechanic shops, etc) for society money (pictured below for database backend, table is named management_funds)
 However qb-core paycheck loop is not removing money from the society accounts. Configurations (pictured below) Is what it is currently set in place.

**Screenshots**
qbcore/server/main.lua (paycheck statement)
https://i.imgur.com/7Upym7y.png

qbcore/config
https://i.imgur.com/0PTRgV9.png

qbcore/client/jobs.lua
https://i.imgur.com/PnArT8L.png

database table (management funds)
https://i.imgur.com/sXxEj0b.png

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - qb-core, qb-management
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no.

**Additional context**
![WinSCP_pTxiuS9V5c](https://user-images.githubusercontent.com/96322790/176566041-b0bfed86-3d8a-46e2-bd60-e89393ea1769.png)
![WinSCP_yHPRqMDaIG](https://user-images.githubusercontent.com/96322790/176566049-b4c92b2d-86b8-43be-8d09-5c6adae7068c.png)
![heidisql_2UueJEpT7s](https://user-images.githubusercontent.com/96322790/176566056-84d0c32d-1903-40b7-9ebf-1a3276d032f1.png)
![WinSCP_a4qRROEVn9](https://user-images.githubusercontent.com/96322790/176566062-f0aaeb84-6f62-4ef3-a9d6-b2c6db606602.png)

**Comment by nzkfc** [comment]
@Xdelic just a tip if you're not sure, set language to lua in your editor so it's not all white text, will help ya eyes :)

**Comment by Xdelic** [comment]
[Fixed] This is the line that it needs to be, to correctly pull from the society money =) instead of triggerevents

exports["qb-management"]:RemoveMoney(Player.PlayerData.job.name, payment)

**Comment by D4isDAVID** [comment]
Fixed by 3f703a2, this can be closed.

**Comment by nzkfc** [comment]
> Fixed by [3f703a2](https://github.com/qbcore-framework/qb-core/commit/3f703a2950689ff63988b01a60a6a81a35d37128), this can be closed.

We already have that line but still not working...
