### ISSUE TITLE
[SUGGESTION] Inventory weight and slots changeable by function

### ISSUE THREAD

**Issue by BoutProduction** [qbcore-framework/qb-core#746]
My suggestion would be to add functionality to set the maximum weight and slots from the player inventory as this would be useful for a backpack system for example, allowing you to add backpacks that allow you to carry more

**Comment by ChatDisabled** [comment]
Backpack --> Create or get a third party resource to make this possible

Max weight and slots refer too [`this`](https://github.com/qbcore-framework/qb-inventory/blob/e14b28d7d4f9ad5a690bca61cc13e08297f83e57/config.lua#L5-L6)
