### ISSUE TITLE
A compleet new install with TxAdmin fails to work after creating your character (BLACKSCREEN) [BUG] and [FIX]

### ISSUE THREAD

**Issue by MaDHouSe79** [qbcore-framework/qb-core#763]
I just install a compleet new server with TxAdmin, i did this today just 30min ago...

But a new install TxAdmin server fails to work, cause the qb-multicharacter and or qb-spawn don't work for some reason, and it keep in a blacksreeen after you creating a character, to fix this, downgrade qb-multicharacter and qb-spawn, and it works again I dont know why it keeps in blackscreen, cause i don't get any errors or any indecators why this happens.

This was the only thing that came to my mind, cause my previous server was just working fine, so I transferred those 2 scripts and it works again on a fresh install.

**Comment by ChatDisabled** [comment]
As this is already an old issue and doesn't seem to be relevant anymore, pretty sure it's fixed already / working. Close issue?
