### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by DroneN1456** [qbcore-framework/qb-core#766]
the ability to inspect a player inventory when he is down, or just inspect the inventory while he is alive as police for example, don't know if this is already a feature but i dint figured out how to inspect a player inventory when he dies

**Comment by ChatDisabled** [comment]
Already part of the framework
https://github.com/qbcore-framework/qb-inventory/blob/19baee5a662797b9894057f8440bb5fea16172b8/server/main.lua#L2130-L2132
