### ISSUE TITLE
Phone is not working?

### ISSUE THREAD

**Issue by fivemuser69** [qbcore-framework/qb-core#767]
Basically i had 2 different QB-Core servers, i actually went ahead and tried to pick up the phone on both of those. But still on no one it's not working, it says in the client.lua in qb-phone that it is the key "M" to pick your phone up? Correct me if i am wrong.

It was the same thing on my friend Jame's server when he just made a new qb-core server. The phone wont work while pressing M.

The things is, there is no errors either in the TxAdmin or in the F8 console or any in the "qb-phone" folder

Is there something i have done wrong? Because all i did was just to download the server and fix it, didn't change anything.

Hopefully you understand this well! Regards - Robin!

**Comment by Z3rio** [comment]
I would recommend you to create an issue on the qb-phone resource and not the qb-core resource.

**Comment by ChatDisabled** [comment]
@fivemuser69 you created another Issue yet or did it get resolved? Please close this one then.
