### ISSUE TITLE
[BUG] Checking allowance 

### ISSUE THREAD

**Issue by JukzyYT** [qbcore-framework/qb-core#769]
it's stuck on checking allowanc
![FiveM® by Cfx re 7_28_2022 12_50_09 AM](https://user-images.githubusercontent.com/110150201/181423126-730f3c83-ad42-4569-82a2-88698b01c53f.png)
e

**Comment by Griefa** [comment]
Not a bug

**Comment by JukzyYT** [comment]
> 

then what is it?

**Comment by JukzyYT** [comment]
> Not a bug

also I think I found a fix you should check the yaml it might have been updated

**Comment by ChatDisabled** [comment]
Has nothing to do with yaml or whatever. Your database is simply not connected.
