### ISSUE TITLE
Ped Duplications 

### ISSUE THREAD

**Issue by Jaymxs1** [qbcore-framework/qb-core#771]
When at place of where you can be giving work or to interact with ped, there is always two peds there instead of just one ped   

**Expected behavior**
One ped to be spawned 

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [Up to date]
-
 - Have you renamed `qb-` to something custom? [no]

**Comment by FlizzyDev** [comment]
I am having this issue too. have you been able to fix it?

**Comment by ChatDisabled** [comment]
@Jaymxs1 shouldn't you create an issue [here](https://github.com/qbcore-framework/qb-cityhall/issues) then? Has nothing to do with the core. Also, did it get resolved or not? Otherwise just close this issue

**Comment by Jaymxs1** [comment]
> I am having this issue too. have you been able to fix it?

we ending up getting a new store script that don't include ped's and that stoped any ped duplicates must be the store script that is included with qb core
