### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Svenhr** [qbcore-framework/qb-core#791]
**Describe the bug**
When i give admin to player via menu in game /admin after server restart server player no longer have admin.

**To Reproduce**
1. Go to 'Type /admin and open admin menu go set player admin and restart server'
3. Use this item '....' (item's name from shared.lua if applicable)
4. No error

**Expected behavior**
Save a player permison and after server restart player should have admin

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 23 Mar 2022 latest realase
 - Are you using custom resource? which ones? using all resource coming with this framework
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by peppinoita** [comment]
Seriously why don’t you read the beautiful qbcore documentation?

**Comment by Svenhr** [comment]
I read and know how it work there is for reason id admin menu to add player as admin

**Comment by peppinoita** [comment]
You have to put all others admin in the server.CFC as you have done with your account. The option in the admin menu is only temporary

**Comment by Svenhr** [comment]
I dont know this is temporary hope in next update will be pernament permission thanks
