### ISSUE TITLE
edit this

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-core#84]
["printerdocument"] 			 = {["name"] = "printerdocument", 				["label"] = "Document", 				["weight"] = 500, 		["type"] = "item", 		["image"] = "printerdocument.png", 		["unique"] = true, 	["useable"] = true, 	["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "A nice document"},

ATTENTION: To have this working correctly you MUST change shared.lua as follows: Search for "printerdocument" and make ["unique"] = true otherwise documents WILL STACK and You'll be able to see only latest.

**Comment by BerkieBb** [comment]
Why don't you make a pull request instead of an issue?
