### ISSUE TITLE
[BUG] command error

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-core#841]
### Summary

I have a strange error in qb-core, what is it?

### Reproduction

I installed qbcore and it was already

### Expected behavior

absence of this error

### Actual behavior

a strange error has started to pop up

### Additional context

[    c-scripting-core] Creating script environments for qb-core
[      script:qb-core] Warning: Missing phrase for key: "command.tp.help"
[      script:qb-core] Warning: Missing phrase for key: "command.tp.params.x.name"
[      script:qb-core] Warning: Missing phrase for key: "command.tp.params.x.help"
[      script:qb-core] Warning: Missing phrase for key: "command.tp.params.y.name"
[      script:qb-core] Warning: Missing phrase for key: "command.tp.params.y.help"
[      script:qb-core] Warning: Missing phrase for key: "command.tp.params.z.name"
[      script:qb-core] Warning: Missing phrase for key: "command.tp.params.z.help"
[      script:qb-core] Warning: Missing phrase for key: "command.tpm.help"
[      script:qb-core] Warning: Missing phrase for key: "command.togglepvp.help"
[      script:qb-core] Warning: Missing phrase for key: "command.addpermission.help"
[      script:qb-core] Warning: Missing phrase for key: "command.addpermission.params.id.name"
[      script:qb-core] Warning: Missing phrase for key: "command.addpermission.params.id.help"
[      script:qb-core] Warning: Missing phrase for key: "command.addpermission.params.permission.name"
[      script:qb-core] Warning: Missing phrase for key: "command.addpermission.params.permission.help"
[      script:qb-core] Warning: Missing phrase for key: "command.removepermission.help"
[      script:qb-core] Warning: Missing phrase for key: "command.removepermission.params.id.name"
[      script:qb-core] Warning: Missing phrase for key: "command.removepermission.params.id.help"
[      script:qb-core] Warning: Missing phrase for key: "command.removepermission.params.permission.name"
[      script:qb-core] Warning: Missing phrase for key: "command.removepermission.params.permission.help"
[      script:qb-core] Warning: Missing phrase for key: "command.openserver.help"
[      script:qb-core] Warning: Missing phrase for key: "command.closeserver.help"
[      script:qb-core] Warning: Missing phrase for key: "command.closeserver.params.reason.name"
[      script:qb-core] Warning: Missing phrase for key: "command.closeserver.params.reason.help"
[      script:qb-core] Warning: Missing phrase for key: "command.car.help"
[      script:qb-core] Warning: Missing phrase for key: "command.car.params.model.name"
[      script:qb-core] Warning: Missing phrase for key: "command.car.params.model.help"
[      script:qb-core] Warning: Missing phrase for key: "command.dv.help"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.help"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.params.id.name"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.params.id.help"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.params.moneytype.name"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.params.moneytype.help"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.params.amount.name"
[      script:qb-core] Warning: Missing phrase for key: "command.givemoney.params.amount.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.params.id.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.params.id.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.params.moneytype.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.params.moneytype.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.params.amount.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setmoney.params.amount.help"
[      script:qb-core] Warning: Missing phrase for key: "command.job.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.params.id.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.params.id.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.params.job.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.params.job.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.params.grade.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setjob.params.grade.help"
[      script:qb-core] Warning: Missing phrase for key: "command.gang.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.params.id.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.params.id.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.params.gang.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.params.gang.help"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.params.grade.name"
[      script:qb-core] Warning: Missing phrase for key: "command.setgang.params.grade.help"
[      script:qb-core] Warning: Missing phrase for key: "command.ooc.help"
[      script:qb-core] Warning: Missing phrase for key: "command.me.help"
[      script:qb-core] Warning: Missing phrase for key: "command.me.params.message.name"
[      script:qb-core] Warning: Missing phrase for key: "command.me.params.message.help"
[ citizen-server-impl] Started resource qb-core

### Last Updated

yesterday

### Custom Resources

no

### Resource Rename

no

**Comment by tom-osborne** [comment]
This is related to translation files. Are you using a language other than English on your server?

**Comment by alfiswielki** [comment]
> Wiąże się to z plikami tłumaczeniowymi. Czy używasz na swoim serwerze języka innego niż angielski?

I'm editing the en files to en, but I haven't done this yet, could this be to blame?
sets locale "pl-PL"

**Comment by alfiswielki** [comment]
goods fixed. It was about the locale/en.lua file

**Comment by tom-osborne** [comment]
Great, thanks for the update

**Comment by alfiswielki** [comment]
> Świetnie, dzięki za aktualizację

Do you perhaps want all the locale/pl files for qbcore?

**Comment by tom-osborne** [comment]
@alfiswielki Yes, if you can create a pull request that would be much appreciated.
