### ISSUE TITLE
[BUG] items drop

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-core#843]
### Summary

Is it possible to set it so that an item does not disappear on death? If so, how is this done?

### Reproduction

nothing

### Expected behavior

.

### Actual behavior

Wants the item not to fall off after death

### Additional context

.

### Last Updated

never

### Custom Resources

no

### Resource Rename

no

**Comment by TheRealCasiv2** [comment]
Currently no, well atleast not with the current setup. You lose all your items since when you respawn [qb-ambulance](https://github.com/qbcore-framework/qb-ambulancejob) clears your entire inventory without checking which items not to delete.
