### ISSUE TITLE
Server just got removed/blocked from FiveM for using QB Framework 

### ISSUE THREAD

**Issue by dulkith** [qbcore-framework/qb-core#85]
My Server just got removed/blocked from FiveM for using QB Framework which apparently violates their TOS.?

<img width="774" alt="Screenshot 2021-08-03 at 3 40 05 AM" src="https://user-images.githubusercontent.com/11438978/127930130-4693dd6e-d64d-446e-ba5f-ac664f3aa58d.png">

**Comment by MCarvalho-dev** [comment]
I had the same problem but after a few hours it was resolved without me doing anything

**Comment by Developer-Bear** [comment]
This has been resolved.
