### ISSUE TITLE
Reload Weapons [BUG]

### ISSUE THREAD

**Issue by Zwou** [qbcore-framework/qb-core#850]
### Summary

When I try to enter the server it gets stuck

### Reproduction

Update QBCore 
Update qs-inventory (FROM QUASAR)

### Expected behavior

That everything worked correctly

### Actual behavior

SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741 SCRIPT  ERROR: @qb-core/server/player.lua:162: No such export LoadInventory in resoruce qs-inventory

![console](https://user-images.githubusercontent.com/112919896/191623880-2241bcd5-b7e6-4c91-9896-51da3a871119.png)
![ingame](https://user-images.githubusercontent.com/112919896/191623912-dff2742d-7215-42a1-8b67-20e02cea885e.png)

### Last Updated

Yesterday

### Custom Resources

qs-inventory

### Resource Rename

no

**Comment by Molicheu** [comment]
This has nothing to do with QBCore, talk to QUASAR about the issue

**Comment by peppinoita** [comment]
you missed some steps of the quasar documentation
