### ISSUE TITLE
[BUG] exports['qb-core']AddItems(items)

### ISSUE THREAD

**Issue by ElusionPDX** [qbcore-framework/qb-core#854]
### Summary

When using the export the items are added but not all core systems see them client side.

### Reproduction

Add files via export, we are adding a pick axe
 
Ran server side. QBCore.Shared.Items["pickaxe"]["label"] returns "PickAxe"
Ran client side.  QBCore.Shared.Items["pickaxe"]["label"] returns nil

### Expected behavior

To give label names on client 

### Actual behavior

Ran server side. QBCore.Shared.Items["pickaxe"]["label"] returns "PickAxe"
Ran client side.  QBCore.Shared.Items["pickaxe"]["label"] returns nil

### Last Updated

9/22/22

### Custom Resources

nope

### Resource Rename

nope

**Comment by JustCarry** [comment]
Hello ElusionPDX,

First, you have to check out the `QBCore` object and make sure it is accessible from the client side via `exports['qb-core']:GetCoreObject()`

Second, if QBCore is accessible and it gives you the core object then I would double check the rest whether if they return anything or not such as "Shared", "Items" if they do then lastly check the "pickaxe" item and make sure it is under Items objects in shared/items.lua file.


If none of these works, then put your code down.

**Comment by ElusionPDX** [comment]
The items label works when the item is added to the stock shared items list. Its only when items are added via export that the label is not working

**Comment by JustCarry** [comment]
When you add it via exports, it may haven't added by the time you calling the item's label. So, make sure that the item is correctly added via exports then make sure that the code order is correct as well.

**Comment by ElusionPDX** [comment]
The items get added right after the core starts to make sure they are in before any scripts look for them.

**Comment by TAGaming20** [comment]
I'm having a similiar issue. Adding items directly to qbcore.items.shared works. Adding items via exports['qb-core']:AddItems({}) is only visible to the resource exporting the items. Other resources return nil to those items.

**Comment by TAGaming20** [comment]
I seemed to have fixed it. I added this block from the server/exports.lua to client/functions.lua and it worked.

```
local function AddItems(items)
    local shouldContinue = true
    local message = "success"
    local errorItem = nil

    for key, value in pairs(items) do
        if type(key) ~= "string" then
            message = "invalid_item_name"
            shouldContinue = false
            errorItem = items[key]
            break
        end

        if QBCore.Shared.Items[key] then
            message = "item_exists"
            shouldContinue = false
            errorItem = items[key]
            break
        end

        QBCore.Shared.Items[key] = value
    end

    if not shouldContinue then return false, message, errorItem end
    TriggerClientEvent('QBCore:Client:OnSharedUpdateMultiple', -1, 'Items', items)
    TriggerEvent('QBCore:Server:UpdateObject')
    return true, message, nil
end

QBCore.Functions.AddItems = AddItems
exports('AddItems', AddItems)

```
