### ISSUE TITLE
[BUG] Cant Find Field 'Vehicles' In All QB Scripts 

### ISSUE THREAD

**Issue by Fear6682** [qbcore-framework/qb-core#863]
### Summary

In All Of My QB Scripts that use vehicles like garages and phone

### Reproduction

1. I added some vehicles to vehicles.lua in Shared in the Qb-Core folder (i have checked for issues)
2. i joined the server.
3. the scripts were broken

Idk if this is for a new update or something but i can't find the root of the problem 

The error: 
SCRIPT ERROR [the resource] to index a nil value (field 'Vehicles')

### Expected behavior

The Server to work fine

### Actual behavior

All qb scripts are broken

### Last Updated

1 Month Ago

### Custom Resources

all qb scripts from qb github

### Resource Rename

none

**Comment by Kosminisk** [comment]
Have the same problem Vehicles.lua seems to be like it needs to be but in the server garages,vehicle shop nothing opens with errors qb-garages/client/main.lua:247: attempt to index a nil value (field 'Vehicles')
but if i replace the vehicles.lua with a deafult one it works?
any help?

**Comment by Fear6682** [comment]
Its because there's an error in 'qb-core/shared/vehicles' file
