### ISSUE TITLE
Player not save character, in steam this player have 1 emoji like this " 🩸"

### ISSUE THREAD

**Issue by MCarvalho-dev** [qbcore-framework/qb-core#87]
Player not save character, in steam this player have 1 emoji like this " 🩸"

I have a error in cosole in insert player name

**Comment by MCarvalho-dev** [comment]
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\xA9\xB8' for column `zap781571-1`.`players`.`name` at row 1
 
 i have this error can help me?

**Comment by MCarvalho-dev** [comment]
I change in database Collation from latin1_swedish_ci to utf8mb4_general_ci, but dont work

**Comment by BerkieBb** [comment]
Steam has been removed so steam names have nothing to do with it

**Comment by MCarvalho-dev** [comment]
But if player remove emoji no have errors...

**Comment by MCarvalho-dev** [comment]
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\xA9\xB8' for column `zap781571-1`.`players`.`name` at row 1 
this is the error that comes to me, and the character after being created by the player who has an emoji in the name, the character is not saved. and other players named steam without emojis works correctly without errors. That's why I say it's by the name of steam

**Comment by BerkieBb** [comment]
Yeah I found out that the native `GetPlayerName` gets the steam name if steam is present

**Comment by MCarvalho-dev** [comment]
how can i solve this? in database i change encoding to unicode but dont solve. No save player in database

**Comment by BerkieBb** [comment]
I'll check for a solution tomorrow

**Comment by sinfuljosh** [comment]
You need to ensure that everything is set to utf8mb4. 

If you are using the connect string in server.cfg make sure it has the charset:

`mysql_connection_string "mysql://user:password@host/database?charset=utf8mb4"
`
If you are using the config file have something like this:

```
    host : 'localhost',
    user : 'root',
    password : '',
    database : 'db',
    charset : 'utf8mb4'
```

**Comment by MCarvalho-dev** [comment]
> You need to ensure that everything is set to utf8mb4.
> 
> If you are using the connect string in server.cfg make sure it has the charset:
> 
> `mysql_connection_string "mysql://user:password@host/database?charset=utf8mb4" `
> If you are using the config file have something like this:
> 
> ```
> {
>   "user": "root",
>   "password": "",
>   "host": "localhost",
>   "port": 3306,
>   "database": "db",
>   "charset" : "utf8mb4"
> }
> ```

thank you that solved my problem
