### ISSUE TITLE
[POSSIBLE BUG] QBCore:ToggleDuty event not firing in latest verion.

### ISSUE THREAD

**Issue by ItsVinnyX** [qbcore-framework/qb-core#880]
### Summary

QBCore:ToggleDuty event is not firing.

### Reproduction

1. Using latest qb-core.
2. Using latest qb-policejob.
3. Using latest qb-target.
4. Clock in via qb-target.
5. No duty prompt.
6. Debug statements in the event, none are firing.
7. Take the contents from the event and put it into a command and it works as intended.

### Expected behavior

I should be able to go on duty.

### Actual behavior

Nothing runs, event is not triggered.

### Last Updated

Today.

### Custom Resources

N/A

### Resource Rename

No.

**Comment by ItsVinnyX** [comment]
QB-CORE:
Not firing this event.
```lua
RegisterNetEvent('QBCore:ToggleDuty', function()
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if not Player then return end
    if Player.PlayerData.job.onduty then
        Player.Functions.SetJobDuty(false)
        TriggerClientEvent('QBCore:Notify', src, Lang:t('info.off_duty'))
    else
        Player.Functions.SetJobDuty(true)
        TriggerClientEvent('QBCore:Notify', src, Lang:t('info.on_duty'))
    end
    TriggerClientEvent('QBCore:Client:SetDuty', src, Player.PlayerData.job.onduty)
end)
```

QB-POLICEJOB:
```lua
RegisterNetEvent('qb-policejob:ToggleDuty', function()
    onDuty = not onDuty -- WORKING
    TriggerServerEvent("QBCore:ToggleDuty") <--- NOT TRIGGERING
    TriggerServerEvent("police:server:UpdateCurrentCops") <--- TRIGGERING
    TriggerServerEvent("police:server:UpdateBlips") <--- TRIGGERING
end)
```

My Command (Works):
```lua
QBCore.Commands.Add('onduty', 'Go on duty.', {}, true, function(source, args)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    
    local PlayerJob = Player.PlayerData.job.name
    
    if PlayerJob == "police" then
        if not Player then return end
        if Player.PlayerData.job.onduty then
            Player.Functions.SetJobDuty(false)
            TriggerClientEvent('QBCore:Notify', src, Lang:t('info.off_duty'))
        else
            Player.Functions.SetJobDuty(true)
            TriggerClientEvent('QBCore:Notify', src, Lang:t('info.on_duty'))
        end
        TriggerClientEvent('QBCore:Client:SetDuty', src, Player.PlayerData.job.onduty)
        TriggerClientEvent('qb-policejob:ToggleDuty', src)
    end
end, 'user')
```

**Comment by singh-manavv** [comment]
@ItsVinnyX try putting a print statement at the start of the event like this and see if it gets printed in your F8 console or not .
`RegisterNetEvent('QBCore:ToggleDuty', function()
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    print(' Its in here ') ---- Debugging test
    if not Player then return end
    if Player.PlayerData.job.onduty then
        Player.Functions.SetJobDuty(false)
        TriggerClientEvent('QBCore:Notify', src, Lang:t('info.off_duty'))
    else
        Player.Functions.SetJobDuty(true)
        TriggerClientEvent('QBCore:Notify', src, Lang:t('info.on_duty'))
    end
    TriggerClientEvent('QBCore:Client:SetDuty', src, Player.PlayerData.job.onduty)
end)`

**Comment by ItsVinnyX** [comment]
> @ItsVinnyX try putting a print statement at the start of the event like this and see if it gets printed in your F8 console or not .
> 
> ```
> RegisterNetEvent('QBCore:ToggleDuty', function()
>     local src = source
>     local Player = QBCore.Functions.GetPlayer(src)
>     print(' Its in here ') ---- Debugging test
>     if not Player then return end
>     if Player.PlayerData.job.onduty then
>         Player.Functions.SetJobDuty(false)
>         TriggerClientEvent('QBCore:Notify', src, Lang:t('info.off_duty'))
>     else
>         Player.Functions.SetJobDuty(true)
>         TriggerClientEvent('QBCore:Notify', src, Lang:t('info.on_duty'))
>     end
>     TriggerClientEvent('QBCore:Client:SetDuty', src, Player.PlayerData.job.onduty)
> end)
> ```

Already have, the event isn't being run. I duplicated the event, through it in QB-POLICEJOB and it fixed the duty system in all other resources. Something is wrong with the core.

**Comment by singh-manavv** [comment]
> > @ItsVinnyX try putting a print statement at the start of the event like this and see if it gets printed in your F8 console or not .
> > ```
> > RegisterNetEvent('QBCore:ToggleDuty', function()
> >     local src = source
> >     local Player = QBCore.Functions.GetPlayer(src)
> >     print(' Its in here ') ---- Debugging test
> >     if not Player then return end
> >     if Player.PlayerData.job.onduty then
> >         Player.Functions.SetJobDuty(false)
> >         TriggerClientEvent('QBCore:Notify', src, Lang:t('info.off_duty'))
> >     else
> >         Player.Functions.SetJobDuty(true)
> >         TriggerClientEvent('QBCore:Notify', src, Lang:t('info.on_duty'))
> >     end
> >     TriggerClientEvent('QBCore:Client:SetDuty', src, Player.PlayerData.job.onduty)
> > end)
> > ```
> 
> Already have, the event isn't being run. I duplicated the event, through it in QB-POLICEJOB and it fixed the duty system in all other resources. Something is wrong with the core.

Did u check if it goes in the if condition or now ? by debugging

**Comment by ItsVinnyX** [comment]
> > > @ItsVinnyX try putting a print statement at the start of the event like this and see if it gets printed in your F8 console or not .
> > > ```
> > > RegisterNetEvent('QBCore:ToggleDuty', function()
> > >     local src = source
> > >     local Player = QBCore.Functions.GetPlayer(src)
> > >     print(' Its in here ') ---- Debugging test
> > >     if not Player then return end
> > >     if Player.PlayerData.job.onduty then
> > >         Player.Functions.SetJobDuty(false)
> > >         TriggerClientEvent('QBCore:Notify', src, Lang:t('info.off_duty'))
> > >     else
> > >         Player.Functions.SetJobDuty(true)
> > >         TriggerClientEvent('QBCore:Notify', src, Lang:t('info.on_duty'))
> > >     end
> > >     TriggerClientEvent('QBCore:Client:SetDuty', src, Player.PlayerData.job.onduty)
> > > end)
> > > ```
> > 
> > 
> > Already have, the event isn't being run. I duplicated the event, through it in QB-POLICEJOB and it fixed the duty system in all other resources. Something is wrong with the core.
> 
> Did u check if it goes in the if condition or not ? by debugging

Every possible line has been debugged. Nothing is running. I can confirm I am not the only one with this issue. I opened a thread in Discord and many others spoke up and said they had the same experience.

**Comment by MaybeAU** [comment]
Any update on this?
