### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MDGamesmaster** [qbcore-framework/qb-core#889]
### Summary

throwing an error when i do the taxi job or the bus job

### Reproduction

https://cdn.discordapp.com/attachments/1050087527580696600/1050814598586056764/image.png

fresh install of qbcore > then do busjob or taxijob. happens when vehicle spawns. also keep getting the screenshot-basic error from fresh install. have done a fresh install multiple times

### Expected behavior

no errors

### Actual behavior

errors but the job scripts works as should

### Last Updated

20 mins ago

### Custom Resources

no

### Resource Rename

no

**Comment by MDGamesmaster** [comment]
![image](https://user-images.githubusercontent.com/117952305/206763927-ae59e211-374b-4e53-a5b6-31a08caaefe5.png
there while im doing the towing job

**Comment by OudeGuru** [comment]
Try installing the updated progressbar: https://github.com/qbcore-framework/progressbar

**Comment by JericoFX** [comment]
sound like a notification issue, check in the code for the type of the notification, QBCore.Functions.Notify("","LOOK HERE",type)
