### ISSUE TITLE
QBCore.Functions.Progressbar throws warnings in command console on every use of this function [BUG]

### ISSUE THREAD

**Issue by OudeGuru** [qbcore-framework/qb-core#892]
### Summary

When iI use function QBCore.Functions.Progressbar and then open on client console command (F8), it will have generated 4 the same warning lines: script:progressbar:warning:entity Warning: GetNetworkObject: no object by ID 0

### Reproduction

It's very simple to replicate:

Go to a shop buy bandages an then use 1 bandage.
open F8 before use and open f8 after use: u will have 4 warning lines added.

I also have tried it with a fresh downloaded & install of qbcore and it also gave these warnings.
![image](https://user-images.githubusercontent.com/116972742/207160727-c03ceae2-4312-4eea-9352-08b7fc2ed58b.png)
![image](https://user-images.githubusercontent.com/116972742/207160798-24db861d-a523-47fa-aa7b-8b3098c3699f.png)

### Expected behavior

I didn't expect a warning to appear (besides that everything works as expected)

### Actual behavior

As stated before: 4 warning lines, and the script itself works as expected

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by XxDeezixX** [comment]
im  getting the samething just started 3-4 days ago any help....thank you ...

**Comment by XxDeezixX** [comment]
i wander why qbcore updated and made things worse

**Comment by OudeGuru** [comment]
This is not beacause qbcore did an update, it's FiveM who did some update's....

**Comment by OudeGuru** [comment]
Problem is solved: download the new updated progressbar here: https://github.com/qbcore-framework/progressbar
