### ISSUE TITLE
Error for QBcore

### ISSUE THREAD

**Issue by aaaaadasdasdasdaw** [qbcore-framework/qb-core#894]
### Summary

I get multiple errors like SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')

### Reproduction

1. I added a car to my QBcore dealership
2. when going to go next to any car in the dealer and pressing L-Alt when it says vehicle options, it closes imediatly
3. I get 4 errors like this:SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
4. I cannt find help anywhere

### Expected behavior

To allow me to open vehicle options and swap the vehicle for the one I added and/or buy a new one

### Actual behavior

this is the WHOLE error i got:
[      script:qb-core] [qb-core:LOG] Donald J. Trump PLAYER SAVED!
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[ citizen-server-impl] Server list query returned an error: System.Net.Sockets.SocketException: Operation timed out <- System.Net.Http.HttpRequestException: Operation timed out (197.93.146.173:30120)
> txaEvent "adminsUpdated" "[1]"
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] [qb-core:LOG] Donald J. Trump PLAYER SAVED!
[      script:oxmysql] [WARNING] qb-inventory took 544.8872ms to execute a query!
[      script:oxmysql]     UPDATE players SET inventory = ? WHERE citizenid = ? ["[{\"info\":[],\"name\":\"phone\",\"type\":\"item\",\"amount\":1,\"slot\":1},{\"info\":{\"lastname\":\"Jogan\",\"firstname\":\"Mark\",\"birthdate\":\"2022-12-14\",\"type\":\"Class C Driver License\"},\"name\":\"driver_license\",\"type\":\"item\",\"amount\":1,\"slot\":2},{\"info\":{\"nationality\":\"United States\",\"firstname\":\"Mark\",\"birthdate\":\"2022-12-14\",\"citizenid\":\"ZNK97253\",\"gender\":0,\"lastname\":\"Jogan\"},\"name\":\"id_card\",\"type\":\"item\",\"amount\":1,\"slot\":3},{\"info\":{\"lastname\":\"Jogan\",\"firstname\":\"Mark\",\"birthdate\":\"2022-12-14\",\"type\":\"Class C Driver License\"},\"name\":\"driver_license\",\"type\":\"item\",\"amount\":1,\"slot\":4}]","ZNK97253"]
[      script:oxmysql] [WARNING] qb-core took 676.8072ms to execute a query!
[      script:oxmysql]     INSERT INTO players (citizenid, cid, license, name, money, charinfo, job, gang, position, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE cid = ?, name = ?, money = ?, charinfo = ?, job = ?, gang = ?, position = ?, metadata = ? ["ZNK97253",2,"license:8e9878f0d79efde6a1f810ecf62921189c028e5a","Donald J. Trump","{\"bank\":9127850,\"crypto\":13000,\"cash\":410}","{\"birthdate\":\"2022-12-14\",\"gender\":0,\"backstory\":\"placeholder backstory\",\"firstname\":\"Mark\",\"nationality\":\"United States\",\"lastname\":\"Jogan\",\"phone\":\"9864621892\",\"cid\":2,\"account\":\"US07QBCore1970221745\"}","{\"name\":\"reporter\",\"payment\":50,\"onduty\":true,\"type\":\"none\",\"isboss\":false,\"grade\":{\"name\":\"Journalist\",\"level\":0},\"label\":\"Reporter\"}","{\"name\":\"none\",\"isboss\":false,\"grade\":{\"name\":\"none\",\"level\":0},\"label\":\"No Gang Affiliaton\"}","{\"x\":-38.84835052490234,\"y\":-1104.2109375,\"z\":26.4154052734375}","{\"inside\":{\"apartment\":[]},\"criminalrecord\":{\"hasRecord\":false},\"injail\":0,\"fitbit\":[],\"inlaststand\":false,\"phonedata\":{\"SerialNumber\":13634186,\"InstalledApps\":[]},\"thirst\":39.20000000000004,\"bloodtype\":\"O+\",\"licences\":{\"business\":false,\"weapon\":false,\"driver\":true},\"phone\":[],\"dealerrep\":0,\"armor\":0,\"tracker\":false,\"status\":[],\"commandbinds\":{\"F3\":{\"command\":\"/dpdpdpdp\",\"argument\":\"\"},\"F2\":{\"command\":\"/NOCLIP\",\"argument\":\"\"},\"F5\":{\"command\":\"/EASYADMIN\",\"argument\":\"\"},\"F10\":{\"command\":\"A\",\"argument\":\"\"},\"F9\":{\"command\":\"a\",\"argument\":\"\"},\"F6\":{\"command\":\"/txadmin\",\"argument\":\"open TXADMIN MENU\"},\"F7\":{\"command\":\"a\",\"argument\":\"\"}},\"jailitems\":[],\"walletid\":\"QB-69501786\",\"craftingrep\":0,\"isdead\":false,\"callsign\":\"NO CALLSIGN\",\"hunger\":32.79999999999993,\"fingerprint\":\"xO503O24Iym9084\",\"ishandcuffed\":false,\"stress\":7,\"attachmentcraftingrep\":0,\"jobrep\":{\"tow\":0,\"hotdog\":0,\"taxi\":0,\"trucker\":0}}",2,"Donald J. Trump","{\"bank\":9127850,\"crypto\":13000,\"cash\":410}","{\"birthdate\":\"2022-12-14\",\"gender\":0,\"backstory\":\"placeholder backstory\",\"firstname\":\"Mark\",\"nationality\":\"United States\",\"lastname\":\"Jogan\",\"phone\":\"9864621892\",\"cid\":2,\"account\":\"US07QBCore1970221745\"}","{\"name\":\"reporter\",\"payment\":50,\"onduty\":true,\"type\":\"none\",\"isboss\":false,\"grade\":{\"name\":\"Journalist\",\"level\":0},\"label\":\"Reporter\"}","{\"name\":\"none\",\"isboss\":false,\"grade\":{\"name\":\"none\",\"level\":0},\"label\":\"No Gang Affiliaton\"}","{\"x\":-38.84835052490234,\"y\":-1104.2109375,\"z\":26.4154052734375}","{\"inside\":{\"apartment\":[]},\"criminalrecord\":{\"hasRecord\":false},\"injail\":0,\"fitbit\":[],\"inlaststand\":false,\"phonedata\":{\"SerialNumber\":13634186,\"InstalledApps\":[]},\"thirst\":39.20000000000004,\"bloodtype\":\"O+\",\"licences\":{\"business\":false,\"weapon\":false,\"driver\":true},\"phone\":[],\"dealerrep\":0,\"armor\":0,\"tracker\":false,\"status\":[],\"commandbinds\":{\"F3\":{\"command\":\"/dpdpdpdp\",\"argument\":\"\"},\"F2\":{\"command\":\"/NOCLIP\",\"argument\":\"\"},\"F5\":{\"command\":\"/EASYADMIN\",\"argument\":\"\"},\"F10\":{\"command\":\"A\",\"argument\":\"\"},\"F9\":{\"command\":\"a\",\"argument\":\"\"},\"F6\":{\"command\":\"/txadmin\",\"argument\":\"open TXADMIN MENU\"},\"F7\":{\"command\":\"a\",\"argument\":\"\"}},\"jailitems\":[],\"walletid\":\"QB-69501786\",\"craftingrep\":0,\"isdead\":false,\"callsign\":\"NO CALLSIGN\",\"hunger\":32.79999999999993,\"fingerprint\":\"xO503O24Iym9084\",\"ishandcuffed\":false,\"stress\":7,\"attachmentcraftingrep\":0,\"jobrep\":{\"tow\":0,\"hotdog\":0,\"taxi\":0,\"trucker\":0}}"]
[ citizen-server-impl] Server list query returned an error: System.Threading.Tasks.TaskCanceledException: A task was canceled. <- System.TimeoutException: A task was canceled. <- System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

### Additional context

PLEASE HELP

### Last Updated

today

### Custom Resources

none

### Resource Rename

nope

**Comment by Z3rio** [comment]
Not an issue.
