### ISSUE TITLE
Issue with qb-radialmenu (field metadata)

### ISSUE THREAD

**Issue by MrTraxx** [qbcore-framework/qb-core#912]
### Summary

attempt to index a nil value (filed 'metadata')

### Reproduction

i only installed with txAdmin the template

### Expected behavior

the script work

### Actual behavior

it didnt worked

### Additional context

![image](https://user-images.githubusercontent.com/68795372/210440867-d5c47ee0-2471-46bf-8954-c5ad8f5d97cd.png)

### Last Updated

today

### Custom Resources

no

### Resource Rename

qb-radialmenu

**Comment by jellyton69** [comment]
You should make an issue in the qb-radialmenu repository, this repo is for bugs with the core itself.
