### ISSUE TITLE
[BUG] Open focus menu (Third eye/ L ALT) Not working

### ISSUE THREAD

**Issue by Luggyv** [qbcore-framework/qb-core#915]
### Summary

My ingame third eye menu isn't working whatsoever. I can't interact with many of the things ingame. I've tried every UI fix, reinstalled both FiveM & GTAV, and still not luck.

### Reproduction

Nothing

### Expected behavior

Nothing

### Actual behavior

Nothing

### Last Updated

Today

### Custom Resources

N/A

### Resource Rename

No

**Comment by Kolvyy** [comment]
Do you have onesync enabled? I know this catches some of my devs off guard.

**Comment by jellyton69** [comment]
qb-core isn't a targeting resource, if you're using qb-target, create an issue in that repo, if you don't have one at all, you would need to get one first.
