### ISSUE TITLE
[BUG] Jobs Not saving | SQL is changing upon Joining!

### ISSUE THREAD

**Issue by Itzhazy** [qbcore-framework/qb-core#921]
### Summary

Jobs of players do not save. I have tried every job that is in QBCore Default and cannot get them to stay. I use the command and the player receives the job. The SQL says that the job is on the player. But when the player rejoins they go back to freelancer. Even the SQL Database is changing when they join. Something is making the job reset on the QBCore end.

### Reproduction

Using the /setjob [ID] [Job] [Grade] Command is not saving upon player rejoining.

### Expected behavior

The job should be saved to player even while the player rejoins.

### Actual behavior

Job is not saved and has to be given back to them.

### Last Updated

Used last update and reinstalled.

### Custom Resources

None

### Resource Rename

I have not

**Comment by lenzh** [comment]
got the same

**Comment by ryan1018** [comment]
same issue

**Comment by lenzh** [comment]
do u use the renewed qb-phone?

**Comment by ryan1018** [comment]
yes I do

**Comment by lenzh** [comment]
make sure to follow that read me carefully i thought i did everystep but i didnt and make sure to do the merge thingy they explain. that fixed it for me

**Comment by AG-FW** [comment]
Same issue I'm having

**Comment by mean1611** [comment]
any one fix this?

**Comment by adss12341** [comment]
The fix is easy just 
Head over to qb-phone/server/employment.lua and change local FirstStart from false to true like shown below

```lua
    local FirstStart = true
```

**Comment by GhzGarage** [comment]
Issue from external resource

**Comment by userefe** [comment]
I still couldn't handle it also I dont use qb-phone, I use high_phone but I still have the same problem, can you explain external resource. if you want ı can share the details
