### ISSUE TITLE
[BUG] vehicles not able to be stored 

### ISSUE THREAD

**Issue by thegreattoker** [qbcore-framework/qb-core#922]
### Summary

using admin menu to spawn cars but not able to buy them or store them as well.

### Reproduction

i added vehicles

### Expected behavior

buy addon cars 

### Actual behavior

spawns car, just not able to buy the vehicle.

### Last Updated

month ago

### Custom Resources

none

### Resource Rename

qb-core

**Comment by Casitrompeta** [comment]
To be able to purchase it you must add it to the vehicleshop

**Comment by GhzGarage** [comment]
If you added custom vehicles then you must add them to the shared/vehicles.lua in order to save/buy them
