### ISSUE TITLE
[BUG] Doesnt work.

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-core#923]
### Summary

doesnt work

### Reproduction

I have a fresh install of QBCore and It already had this on here but its still doesnt work.
![idk what](https://user-images.githubusercontent.com/113321753/213066290-ce885e30-d90e-439f-bb44-278b748305e4.PNG)

### Expected behavior

for it to work

### Actual behavior

warnings

### Additional context

----

### Last Updated

today

### Custom Resources

default

### Resource Rename

no

**Comment by GhzGarage** [comment]
This is an old issue but if it's not resolved please let me know.

**Comment by xxUnknown13xx** [comment]
> This is an old issue but if it's not resolved please let me know.

![baseevnt](https://github.com/qbcore-framework/qb-core/assets/113321753/8dbfa793-45aa-4162-87de-ea3ca6b95b14)
It happens when i spawn a custom car/item and i even installed another fresh qbcore
