### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ZysticV2** [qbcore-framework/qb-core#932]
### Summary

qb-menu isnt loading properly and is causing things to not recognize the export

### Reproduction

Im not sure what happened I was messing with polyzones and it suddenly happened

### Expected behavior

Work

### Actual behavior

not loading right

### Last Updated

I have few days ago

### Custom Resources

no

### Resource Rename

no

**Comment by GhzGarage** [comment]
I've been using qb-menu while making qb-customs and haven't had an issue, I imagine this issue is resolved.
