### ISSUE TITLE
[BUG] Armor metadata not saving

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-core#950]
### Summary

Armor meta not saving on F8 quit, only /logout command.

### Reproduction

1. Create character and spawn armor and use it, you should be a 50 armor.
2. Now use /logout
3a. Spawn back in with same character, armor shhould load to 50%
3b. F8 quit and rejoin server, should again have 50% armor

Now the metadata has been saved due to it being updated on /logout so everytime you come into the server, unless you /logout when the value has gone up/down it will always apply correctly.

Now to recreate the bug:
1. Remove all armor
2. Apply armor
3. Should be 50% armor now
4. F8 quit and re-join server, should now have 0 armor due to it not updating on quit

### Expected behavior

When F8 quitting, metadata for armor should save, 99% of players quit this way generally because some servers don't use the logout option (to stop metagaming/switching characters for loot etc) and then they don't use the fivem close client function.

### Actual behavior

Armor doesn't update metadata unless you use /logout function.

### Last Updated

Today

### Custom Resources

None

### Resource Rename

No

**Comment by ChickenDipper1** [comment]
Use this to fix: https://discord.com/channels/831626422232678481/959862921243005029/991722333305831444

**Comment by eygi** [comment]
> https://discord.com/channels/831626422232678481/959862921243005029/991722333305831444

do you have latest snippet?

**Comment by nzkfc** [comment]
Yep, but that started to break also....

**Comment by GhzGarage** [comment]
We'll make sure to get this fixed, thanks

**Comment by Pyth3rEx** [comment]
> Use this to fix: https://discord.com/channels/831626422232678481/959862921243005029/991722333305831444

link is dead, does someone have the snippet they can share?

**Comment by ChickenDipper1** [comment]
> > Use this to fix: https://discord.com/channels/831626422232678481/959862921243005029/991722333305831444
> 
> link is dead, does someone have the snippet they can share?

Link works fine you need to be in the QBCore Framwork Discord Server.

**Comment by Pyth3rEx** [comment]
> > > Use this to fix: https://discord.com/channels/831626422232678481/959862921243005029/991722333305831444
> > 
> > 
> > link is dead, does someone have the snippet they can share?
> 
> Link works fine you need to be in the QBCore Framwork Discord Server.

Found it!
I'm adding it below to link it to all the other concerned issues. I edited it a tiny bit to fit to present QB-core (eg added 'reason' to leave log entry). gotta add it as a fork someday tho. It's been here since summer 2022 [looking at you dev team who refused @drakortha 's PR]
PS. Thx to @drakortha on discord for his code!

> 1. qb-core/server/player.lua
> add this line below PlayerData.metadata = PlayerData.metadata or {}
`PlayerData.metadata['health'] = PlayerData.metadata['health'] or 200`

> 2. qb-core/server/events.lua
> search AddEventHandler('playerDropped', function(reason)
> and replace with this
```
AddEventHandler('playerDropped', function(reason)
    local src = source
    local ped = GetPlayerPed(src)
    local armor = GetPedArmour(ped)
    local health = GetEntityHealth(ped)

    if not QBCore.Players[src] then return end
    local Player = QBCore.Players[src]
    TriggerEvent('qb-log:server:CreateLog', 'joinleave', 'Dropped', 'red', '**' .. GetPlayerName(src) .. '** (' .. Player.PlayerData.license .. ') left..' .. '\n **Reason:** ' .. reason)
    Player.Functions.SetMetaData('health', health)
    Player.Functions.SetMetaData('armor', armor)
    Player.Functions.Save()
    QBCore.Player_Buckets[Player.PlayerData.license] = nil
    QBCore.Players[src] = nil
end)
```

> 3. qb-ambulancejob/client/job.lua
> search RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
> and replace with this
```
RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
    exports.spawnmanager:setAutoSpawn(false)
    local ped = PlayerPedId()
    TriggerServerEvent("hospital:server:SetDoctor")
    CreateThread(function()
        Wait(5000)
        -- SetEntityMaxHealth(ped, 200)
        -- SetEntityHealth(ped, 200)
        SetPlayerHealthRechargeMultiplier(ped, 0.0)
        SetPlayerHealthRechargeLimit(ped, 0.0)
    end)
    CreateThread(function()
        Wait(1000)
        QBCore.Functions.GetPlayerData(function(PlayerData)
            PlayerJob = PlayerData.job
            onDuty = PlayerData.job.onduty
            SetEntityHealth(PlayerPedId(), PlayerData.metadata["health"])
            SetPedArmour(PlayerPedId(), PlayerData.metadata["armor"])
            if (not PlayerData.metadata["inlaststand"] and PlayerData.metadata["isdead"]) then
                deathTime = Laststand.ReviveInterval
                OnDeath()
                DeathTimer()
            elseif (PlayerData.metadata["inlaststand"] and not PlayerData.metadata["isdead"]) then
                SetLaststand(true)
            else
                TriggerServerEvent("hospital:server:SetDeathStatus", false)
                TriggerServerEvent("hospital:server:SetLaststandStatus", false)
            end

            if PlayerJob.name == 'ambulance' and onDuty then
                TriggerServerEvent("hospital:server:AddDoctor", PlayerJob.name)
            end
        end)
    end)
end)
```

> 4. qb-ambulancejob/server/main.lua
> search RegisterNetEvent('hospital:server:SetArmor', function(amount)
> and replace with this
```
RegisterNetEvent('hospital:server:SetArmor', function(amount)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if not Player then return end
    if amount <= 0 then
       amount = 0
    end
    Player.Functions.SetMetaData('armor', amount)
    Player.Functions.Save()
end)
```

**Comment by nzkfc** [comment]
Real fix is to use qbx lel

**Comment by missing372** [comment]
> > > > 使用此方法修復：https://discord.com/channels/831626422232678481/959862921243005029/991722333305831444
> > > 
> > > 
> > > 連結已失效，有人有可以分享的片段嗎？
> > 
> > 
> > 連結工作正常，您需要進入 QBCore Framwork Discord 伺服器。
> 
> 找到啦！ 我將其添加到下面，以便將其連結到所有其他相關問題。我對它進行了一些微小的編輯以適應當前的 QB 核心（例如，添加了離開日誌條目的“原因”）。但有一天必須將其添加為叉子。它從 2022 年夏天就在這裡了 [看看你們開發團隊拒絕了[@Drakortha](https://github.com/Drakortha)的PR] PS。謝謝[@Drakortha](https://github.com/Drakortha)在 discord 上查看他的程式碼！
> 
> > 1. qb-core/server/player.lua
> >    在 PlayerData.metadata = PlayerData.metadata 或 {} 下方加入此行
> 
> `PlayerData.metadata['health'] = PlayerData.metadata['health'] or 200`
> 
> > 2. qb-core/server/events.lua
> >    搜尋 AddEventHandler('playerDropped', function(reason)
> >    並替換為
> 
> ```
> AddEventHandler('playerDropped', function(reason)
>     local src = source
>     local ped = GetPlayerPed(src)
>     local armor = GetPedArmour(ped)
>     local health = GetEntityHealth(ped)
> 
>     if not QBCore.Players[src] then return end
>     local Player = QBCore.Players[src]
>     TriggerEvent('qb-log:server:CreateLog', 'joinleave', 'Dropped', 'red', '**' .. GetPlayerName(src) .. '** (' .. Player.PlayerData.license .. ') left..' .. '\n **Reason:** ' .. reason)
>     Player.Functions.SetMetaData('health', health)
>     Player.Functions.SetMetaData('armor', armor)
>     Player.Functions.Save()
>     QBCore.Player_Buckets[Player.PlayerData.license] = nil
>     QBCore.Players[src] = nil
> end)
> ```
> 
> > 3. qb-ambulancejob/client/job.lua
> >    搜尋 RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
> >    並替換為
> 
> ```
> RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
>     exports.spawnmanager:setAutoSpawn(false)
>     local ped = PlayerPedId()
>     TriggerServerEvent("hospital:server:SetDoctor")
>     CreateThread(function()
>         Wait(5000)
>         -- SetEntityMaxHealth(ped, 200)
>         -- SetEntityHealth(ped, 200)
>         SetPlayerHealthRechargeMultiplier(ped, 0.0)
>         SetPlayerHealthRechargeLimit(ped, 0.0)
>     end)
>     CreateThread(function()
>         Wait(1000)
>         QBCore.Functions.GetPlayerData(function(PlayerData)
>             PlayerJob = PlayerData.job
>             onDuty = PlayerData.job.onduty
>             SetEntityHealth(PlayerPedId(), PlayerData.metadata["health"])
>             SetPedArmour(PlayerPedId(), PlayerData.metadata["armor"])
>             if (not PlayerData.metadata["inlaststand"] and PlayerData.metadata["isdead"]) then
>                 deathTime = Laststand.ReviveInterval
>                 OnDeath()
>                 DeathTimer()
>             elseif (PlayerData.metadata["inlaststand"] and not PlayerData.metadata["isdead"]) then
>                 SetLaststand(true)
>             else
>                 TriggerServerEvent("hospital:server:SetDeathStatus", false)
>                 TriggerServerEvent("hospital:server:SetLaststandStatus", false)
>             end
> 
>             if PlayerJob.name == 'ambulance' and onDuty then
>                 TriggerServerEvent("hospital:server:AddDoctor", PlayerJob.name)
>             end
>         end)
>     end)
> end)
> ```
> 
> > 4. qb-ambulancejob/server/main.lua
> >    搜尋 RegisterNetEvent('hospital:server:SetArmor', function(amount)
> >    並替換為
> 
> ```
> RegisterNetEvent('hospital:server:SetArmor', function(amount)
>     local src = source
>     local Player = QBCore.Functions.GetPlayer(src)
>     if not Player then return end
>     if amount <= 0 then
>        amount = 0
>     end
>     Player.Functions.SetMetaData('armor', amount)
>     Player.Functions.Save()
> end)
> ```

I only need to add steps 1 and 2, and the subsequent qb-ambulance does not need to be replaced.
why is that? I have also tested the original qb-ambulance with osp-ambulance and the results are the same
