### ISSUE TITLE
[SUGGESTION] Add HasItemCount Function

### ISSUE THREAD

**Issue by MyNamesVanMan** [qbcore-framework/qb-core#954]
### The problem

In order to fetch the item amount you need to use a MySQL function to fetch the item from a table, Creating this function would allow people to fetch the item amounts a lot easier

### Ideal solution

QBCore.Functions.HasItemCount('whateveritem') Then it would return the itemData.count of whatever item was entered so you could write a function like this:   if QBCore.Functions.HasItemCount('goldbar') > 10 then ....

**Comment by GodyFromDiscord** [comment]
Can you not just use HasItem? It takes an amount?

QBCore.Functions.HasItem('goldbar', 10) ?

if QBCore.Functions.HasItem('goldbar', 10) then ...

**Comment by MyNamesVanMan** [comment]
Nio

**Comment by MyNamesVanMan** [comment]
No if you use the has item it returns a bool, Not a value because I want to be able to sell fish, but I cant fetch the item amount because I need it to return an amount not just if there is that many

**Comment by Sharkiiie** [comment]
You can also loop through the inventory with GetItemByName.
Check qb-diving for an example.

**Comment by MyNamesVanMan** [comment]
I ended up writing my own function that loops thru them like you said with GetItemByName It would still be cool to see it as a stock function so people dont need to write there own
