### ISSUE TITLE
[BUG] QBCore.Functions.AddItem(itemName, info) has never worked as intended

### ISSUE THREAD

**Issue by jimathy** [qbcore-framework/qb-core#961]
### Summary

QBCore.Functions.AddItem(itemName, info) has never worked as intended

### Reproduction

I've been trying to make a resource for a few days now and debugging the shared exports/functions to add AddItems to the shared

From what I can tell is, it only shares to players/other scripts if that script client side of the script is started when the items are added.

I managed to get it working fine (with insane lag per item) if I was connected to the server at the time.
The second I tried to make it load at server launch then make use of the items after connecting, they are `nil`

Anyone connecting after the items are added seems to not get the updated list, just the default shared list.

### Expected behavior

Shared item list is supposed to be shared to everyone when UpdateObject is used.

### Actual behavior

Clients connecting AFTER the shared is updated don't seem to get the new shared tables.

### Additional context

This is me after a day of debugging my script for issues: Don't advertise this AddItem feature as working if it doesn't work.

This seems to have been the case since it was added last year.

### Last Updated

This month

### Custom Resources

My own testing script

### Resource Rename

N/A

**Comment by kushuser** [comment]
having a similar issue with RemoveItem

**Comment by Xerrass** [comment]
can Confirm! NEther the export nor the function work as intendet

**Comment by zjdaniels1985** [comment]
Function doesn't work still.

**Comment by GhzGarage** [comment]
Thanks, I'll check this out

**Comment by bandgeekndb** [comment]
@GhzGarage has there been any progress on this?

Before this gets closed for inactivity, this is still a bug that needs addressing before we can call the AddItem/AddJob/etc. exports functional.

I don't know where the best spot in the core would be, but can we update the players shared tables with copies from the server upon loading in? That way, they always get the most updated tables upon login, and if scripts update the tables while they are online, they will get the UpdateCoreObject events as expected. If someone can direct me where the best spot for this might be, I'm happy to submit a PR to try and get the ball rolling. Thanks!

**Comment by GhzGarage** [comment]
Was waiting on a few changes but it's free to try out now before i merge! https://github.com/qbcore-framework/qb-core/pull/988
