### ISSUE TITLE
[BUG] If I remove any car from the list, it starts dropping the car in random places, and I get the following error.

### ISSUE THREAD

**Issue by nagy1991** [qbcore-framework/qb-core#969]
### Summary

If I remove any car from the list, it starts dropping the car in random places, and I get the following error.

### Reproduction

If I remove any car from the list, it starts dropping the car in random places, and I get the following error.

[    156422] [b2802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @qb-vehicleshop/client.lua:97: attempt to index a nil value (field '?')^7
[    156422] [b2802_GTAProce]             MainThrd/ ^3> getVehBrand^7 (^5@qb-vehicleshop/client.lua^7:97)
[    156422] [b2802_GTAProce]             MainThrd/ ^3> fn^7 (^5@qb-vehicleshop/client.lua^7:225)
[    251843] [b2802_GTAProce]                21116/ ResourceCache::AddEntry: Saved cache:v1:e4407570dbc9e86417cb9015a68baa02a6632ea0 to the index cache.
[    259672] [b2802_GTAProce]                21116/ ResourceCache::AddEntry: Saved cache:v1:55bdecb385c2d5bc3f7aaf85eaefb918b200abe9 to the index cache.
[    259781] [b2802_GTAProce]                21116/ ResourceCache::AddEntry: Saved cache:v1:859603e83891c769b1818177460b502bec6e875f to the index cache.
[    273437] [b2802_GTAProce]             MainThrd/ crash
[    307484] [b2802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @qb-vehicleshop/client.lua:97: attempt to index a nil value (field '?')^7
[    307484] [b2802_GTAProce]             MainThrd/ ^3> getVehBrand^7 (^5@qb-vehicleshop/client.lua^7:97)
[    307484] [b2802_GTAProce]             MainThrd/ ^3> fn^7 (^5@qb-vehicleshop/client.lua^7:225)

### Expected behavior

function normally

### Actual behavior

If I remove any car from the list, it starts dropping the car in random places, and I get the following error.

### Last Updated

version '1.2.6'

### Custom Resources

no

### Resource Rename

qb

**Comment by 0xtasty** [comment]
What do you mean by remove? Are you running /dv on the showroom cars? I really don't get it
