### ISSUE TITLE
Add myself Admin

### ISSUE THREAD

**Issue by LsPlayer** [qbcore-framework/qb-core#970]
### The problem

![Bild_2023-04-12_153537200](https://user-images.githubusercontent.com/75249030/231474649-25629fd1-4069-4808-b85e-633feb3900f5.png)
Hey, I wanna set myself to an admin on my own server but like you can see I don't have the "Permissions" which I would need to set myself to an admin. 

### Ideal solution

So I want to know where or how I can add myself as an admin.
Can you please help me?

**Comment by Rtextbook** [comment]
This is not entirely true . 
add_principal identifier.fivem:1721355 group.admin #0xtasty 
you have to use qbcore not group ............. 
add_principal identifier.fivem:1721355 qbcore.admin #0xtasty
add_principal identifier.fivem:1721355 group.god #0xtasty

**Comment by MentalIllness** [comment]
https://docs.qbcore.org/qbcore-documentation/guides/setting-permissions
