### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BillyDrake1** [qbcore-framework/qb-core#973]
### Summary

My third eye L Alt isn't working in my server, is there anyway to fix this?

### Reproduction

Using

### Expected behavior

None

### Actual behavior

None

### Additional context

None

### Last Updated

Today

### Custom Resources

qb-target

### Resource Rename

No

**Comment by GhzGarage** [comment]
Make sure the convar in your server.cfg is set to true here https://github.com/qbcore-framework/txAdminRecipe/blob/7d3b8e30dbeb38777a45c49f707ef6d753a4ea80/server.cfg#L41
