### ISSUE TITLE
Could not find any saved UI settings data.

### ISSUE THREAD

**Issue by xForrestx** [qbcore-framework/qb-core#974]
### Summary

Spawn is a issue

### Reproduction

1.Spawn
2.Load
3.Issue

### Expected behavior

Load and Spawn Muliplayer Charakter

### Actual behavior

Could not find any saved UI settings data.

### Additional context

Not Spawn the MP Char. Spawn as NPC

[     52985] [b2802_GTAProce]             MainThrd/ [Wraith ARS 2X]: Attempting to load saved UI settings data.
[     52985] [b2802_GTAProce]             MainThrd/ [Wraith ARS 2X]: Could not find any saved UI settings data.
[     52985] [b2802_GTAProce]             MainThrd/ [Wraith ARS 2X]: Attempting to load saved operator menu data.
[     52985] [b2802_GTAProce]             MainThrd/ [Wraith ARS 2X]: Could not find any saved operator menu data.

### Last Updated

today

### Custom Resources

-

### Resource Rename

-

**Comment by GhzGarage** [comment]
This resource is unrelated to qbcore
