### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Svenhr** [qbcore-framework/qb-core#976]
### Summary

In last update broken something

### Reproduction

1. Goto qb-core-shared/locale.lua
2. Find line 23 or just search local templateToFind = '%{' .. k .. '}' 
3.There is removed one % and this cause % appear like in garage text screnshot below
![image](https://user-images.githubusercontent.com/60672948/235212345-5f41f96d-0d1a-4a7c-b170-fe9e17f3462a.png)
4. To fix just add one more % in code or copy this local templateToFind = '%%{' .. k .. '}' 

### Expected behavior

This simbol % should not be visible in garage menu

### Actual behavior

% Simbol apper in garage menu

### Last Updated

Today

### Custom Resources

no

### Resource Rename

no

**Comment by Andyauk** [comment]
> ### Summary
> In last update broken something
> 
> ### Reproduction
> 1. Goto qb-core-shared/locale.lua
> 2. Find line 23 or just search local templateToFind = '%{' .. k .. '}'
>    3.There is removed one % and this cause % appear like in garage text screnshot below
>    ![image](https://user-images.githubusercontent.com/60672948/235212345-5f41f96d-0d1a-4a7c-b170-fe9e17f3462a.png)
> 3. To fix just add one more % in code or copy this local templateToFind = '%%{' .. k .. '}'
> 
> ### Expected behavior
> This simbol % should not be visible in garage menu
> 
> ### Actual behavior
> % Simbol apper in garage menu
> 
> ### Additional context
> _No response_
> 
> ### Last Updated
> Today
> 
> ### Custom Resources
> no
> 
> ### Resource Rename
> no

nice you posted that, as I was about to. , my latest PR fixes this issue also.
https://github.com/qbcore-framework/qb-core/pull/977
