### ISSUE TITLE
[BUG] Vehicles don't spawn with a full tank

### ISSUE THREAD

**Issue by Troughy** [qbcore-framework/qb-core#981]
### Summary

When you spawn a vehicle with /car, it doesn't spawn with a full tank

### Reproduction

1. Spawn any vehicle with /car
and that's it, after the engine turns on you can see the fuel level

### Expected behavior

I expect the vehicle to have a full tank.

### Actual behavior

Steps I took between taking these pics: Spawn vehicle, drive a few meters, take pic, /dv, repeat
![image](https://github.com/qbcore-framework/qb-core/assets/76389815/03c195f0-7da7-4a3d-9e3f-f9e875b57b1a)
![image](https://github.com/qbcore-framework/qb-core/assets/76389815/c291f33d-de5a-4294-8fe3-12026ffeb8bc)
![image](https://github.com/qbcore-framework/qb-core/assets/76389815/44ae73ac-5714-4f5a-a563-a3ec4e2e43c5)

### Additional context

#655 fixes this issue. I actually changed the same thing without having seen the PR and it worked. 
I noticed that by default the fuel only 'fills up' on the hud after the engine starts (still takes like half a second even after the car is drivable, BUT even this behaviour is inconsistent as shown on the vid below), and with the LegacyFuel export the fuel is shown instantly after the vehicle spawns
this is the default script https://streamable.com/58gssb (sorry about the lag)
as you can see, sometimes when the car spawns you can already see the fuel level, sometimes you can't, sometimes it's more than half full, sometimes it's almost empty
and this is with the legacyfuel export https://streamable.com/3p1zt0

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by Edvo1901** [comment]
Lol, that is NOT a bug though, you can set the fuel yourself

**Comment by Troughy** [comment]
So vehicles are meant to spawn with different fuel level each time?
