### ISSUE TITLE
[BUG] Bug with lattest version

### ISSUE THREAD

**Issue by TheS1lenT619** [qbcore-framework/qb-core#986]
### Summary

ToggleDuty

### Reproduction

When i try to go On Duty or Off duty (Police) and qb-core start to spam notifys that i joined on duty and gone off duty.

OS: Linux
tx version: v6.0.0 atop FXServer 6468
QB-Core version: 1.2.6

### Expected behavior

To join On Duty or Off duty

### Actual behavior

The event ToggleDuty spaming and got a lot of notifys and loud of QB-Core going to 0.20ms+

### Last Updated

Today

### Custom Resources

No

### Resource Rename

No

**Comment by GhzGarage** [comment]
I'll check this out thank you

**Comment by CoZmoTheGod** [comment]
Having the same issue, will have to revert to my old version since no one can go on-duty

**Comment by TheS1lenT619** [comment]
> I'll check this out thank you

Btw, i fix it. Just need to be with the latest qb-policejob.

**Comment by TheKingsman11** [comment]
I have the same issue. I have a FRESH installation of qb-core. and no added server files. When i go to the PDHQ desk. it says "E- Off duty". in the files I have DEFAULT ON DUTY - OFF.

**Comment by TheKingsman11** [comment]
> > I'll check this out thank you
> 
> Btw, i fix it. Just need to be with the latest qb-policejob.

I tried that and still doesnt work

**Comment by Zotactiks** [comment]
I have the same issue, Lastest qb-core & qb-policejob. I find stopping policejob everything else works fine.

https://i.imgur.com/UNaca4U.png
