### ISSUE TITLE
[BUG] Infinite loading with multicharacter

### ISSUE THREAD

**Issue by HumiPen** [qbcore-framework/qb-core#987]
### Summary

Infinite loading with multicharacter

### Reproduction

It seems that once in service after a reboot it is impossible not to completely backup "resources" if you want to reconnect

### Expected behavior

/

### Actual behavior

![image](https://github.com/qbcore-framework/qb-core/assets/135251316/b35ca863-d9f3-4277-8ffc-acbbb90228ca)

### Additional context

This has been happening for 4 days now, after several attempts, several tries, impossible to know why after a random reboot, the loading becomes infinite on a black background.

### Last Updated

Today

### Custom Resources

QBCORE

### Resource Rename

No

**Comment by GhzGarage** [comment]
My best guess is if your machine rebooted then your database service is not running

**Comment by HumiPen** [comment]
> My best guess is if your machine rebooted then your database service is not running

As soon as the resources are changed, everything works again, including the characters.

**Comment by HumiPen** [comment]
Only by putting the backup back and everything works again, until the problem appears randomly.
We make a backup every 6 hours in the meantime..

**Comment by GhzGarage** [comment]
Did you delete a job from your shared/jobs.lua?

**Comment by HumiPen** [comment]
No, good idea, I keep that aside if the problem persists after the backup is done.
Thanks to you in advance

**Comment by GhzGarage** [comment]
If it's not that then it would also appear that you have a syntax error in your jobs.lua file preventing it from loading properly
