### ISSUE TITLE
[BUG] Missing Square out of part of my custom pause map

### ISSUE THREAD

**Issue by BandmanZeek** [qbcore-framework/qb-core#991]
### Summary

ive tried to install different maps as well but all have the missing square

### Reproduction

I first installed the map into the selected folders i was told for it too go into ensured the file and restarted and the map still wouldnt take out the missing piece 
![Screenshot (369)](https://github.com/qbcore-framework/qb-core/assets/117245363/4a89834f-54d4-4b7b-8d23-2455fdc0c61c)

### Expected behavior

For it too chance the map on my pause menu completely 

### Actual behavior

Bugged out and made a missing square within the custom map

### Last Updated

Today 

### Custom Resources

none just the map resource itself

### Resource Rename

no

**Comment by Bongmasta406** [comment]
Can you close this Bug report and please come to qbcore Discord and we all there would not mind helping with this resource problem your having, as it does not pertain to anything actually with qbcore or the framework. Thank you cant wait to help in the free community https://discord.gg/qbcore
