### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MacroMods** [qbcore-framework/qb-core#997]
### Summary

i dont even know i tried to install custom peds with assestpeds and this happend

### Reproduction

i just went into the game and this happend

### Expected behavior

Expected to work

### Actual behavior

![image](https://github.com/qbcore-framework/qb-core/assets/109301778/431eb18a-b9f6-4952-99c4-dc47d6d4bd97)

### Last Updated

a day ago

### Custom Resources

qb-clothing qb-adminmenu

### Resource Rename

nope

**Comment by Bongmasta406** [comment]
Sir Could you close this Bug report please, as it does not come directly from an issue with the Core or Any the prebuilt scripts, We would love to assist you in the free Community Discord with your particular issue https://discord.gg/qbcore
